// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

/* global window */
import type * as gax from 'google-gax';
import type {Callback, CallOptions, Descriptors, ClientOptions, PaginationCallback, GaxCall} from 'google-gax';
import {Transform} from 'stream';
import * as protos from '../../protos/protos';
import jsonProtos = require('../../protos/protos.json');
import {loggingUtils as logging, decodeAnyProtosInArray} from 'google-gax';

/**
 * Client JSON configuration object, loaded from
 * `src/v1/adaptation_client_config.json`.
 * This file defines retry strategy and timeouts for all API methods in this library.
 */
import * as gapicConfig from './adaptation_client_config.json';
const version = require('../../../package.json').version;

/**
 *  Service that implements Google Cloud Speech Adaptation API.
 * @class
 * @memberof v1
 */
export class AdaptationClient {
  private _terminated = false;
  private _opts: ClientOptions;
  private _providedCustomServicePath: boolean;
  private _gaxModule: typeof gax | typeof gax.fallback;
  private _gaxGrpc: gax.GrpcClient | gax.fallback.GrpcClient;
  private _protos: {};
  private _defaults: {[method: string]: gax.CallSettings};
  private _universeDomain: string;
  private _servicePath: string;
  private _log = logging.log('speech');

  auth: gax.GoogleAuth;
  descriptors: Descriptors = {
    page: {},
    stream: {},
    longrunning: {},
    batching: {},
  };
  warn: (code: string, message: string, warnType?: string) => void;
  innerApiCalls: {[name: string]: Function};
  pathTemplates: {[name: string]: gax.PathTemplate};
  adaptationStub?: Promise<{[name: string]: Function}>;

  /**
   * Construct an instance of AdaptationClient.
   *
   * @param {object} [options] - The configuration object.
   * The options accepted by the constructor are described in detail
   * in [this document](https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md#creating-the-client-instance).
   * The common options are:
   * @param {object} [options.credentials] - Credentials object.
   * @param {string} [options.credentials.client_email]
   * @param {string} [options.credentials.private_key]
   * @param {string} [options.email] - Account email address. Required when
   *     using a .pem or .p12 keyFilename.
   * @param {string} [options.keyFilename] - Full path to the a .json, .pem, or
   *     .p12 key downloaded from the Google Developers Console. If you provide
   *     a path to a JSON file, the projectId option below is not necessary.
   *     NOTE: .pem and .p12 require you to specify options.email as well.
   * @param {number} [options.port] - The port on which to connect to
   *     the remote host.
   * @param {string} [options.projectId] - The project ID from the Google
   *     Developer's Console, e.g. 'grape-spaceship-123'. We will also check
   *     the environment variable GCLOUD_PROJECT for your project ID. If your
   *     app is running in an environment which supports
   *     {@link https://cloud.google.com/docs/authentication/application-default-credentials Application Default Credentials},
   *     your project ID will be detected automatically.
   * @param {string} [options.apiEndpoint] - The domain name of the
   *     API remote host.
   * @param {gax.ClientConfig} [options.clientConfig] - Client configuration override.
   *     Follows the structure of {@link gapicConfig}.
   * @param {boolean} [options.fallback] - Use HTTP/1.1 REST mode.
   *     For more information, please check the
   *     {@link https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md#http11-rest-api-mode documentation}.
   * @param {gax} [gaxInstance]: loaded instance of `google-gax`. Useful if you
   *     need to avoid loading the default gRPC version and want to use the fallback
   *     HTTP implementation. Load only fallback version and pass it to the constructor:
   *     ```
   *     const gax = require('google-gax/build/src/fallback'); // avoids loading google-gax with gRPC
   *     const client = new AdaptationClient({fallback: true}, gax);
   *     ```
   */
  constructor(opts?: ClientOptions, gaxInstance?: typeof gax | typeof gax.fallback) {
    // Ensure that options include all the required fields.
    const staticMembers = this.constructor as typeof AdaptationClient;
    if (opts?.universe_domain && opts?.universeDomain && opts?.universe_domain !== opts?.universeDomain) {
      throw new Error('Please set either universe_domain or universeDomain, but not both.');
    }
    const universeDomainEnvVar = (typeof process === 'object' && typeof process.env === 'object') ? process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'] : undefined;
    this._universeDomain = opts?.universeDomain ?? opts?.universe_domain ?? universeDomainEnvVar ?? 'googleapis.com';
    this._servicePath = 'speech.' + this._universeDomain;
    const servicePath = opts?.servicePath || opts?.apiEndpoint || this._servicePath;
    this._providedCustomServicePath = !!(opts?.servicePath || opts?.apiEndpoint);
    const port = opts?.port || staticMembers.port;
    const clientConfig = opts?.clientConfig ?? {};
    const fallback = opts?.fallback ?? (typeof window !== 'undefined' && typeof window?.fetch === 'function');
    opts = Object.assign({servicePath, port, clientConfig, fallback}, opts);

    // Request numeric enum values if REST transport is used.
    opts.numericEnums = true;

    // If scopes are unset in options and we're connecting to a non-default endpoint, set scopes just in case.
    if (servicePath !== this._servicePath && !('scopes' in opts)) {
      opts['scopes'] = staticMembers.scopes;
    }

    // Load google-gax module synchronously if needed
    if (!gaxInstance) {
      gaxInstance = require('google-gax') as typeof gax;
    }

    // Choose either gRPC or proto-over-HTTP implementation of google-gax.
    this._gaxModule = opts.fallback ? gaxInstance.fallback : gaxInstance;

    // Create a `gaxGrpc` object, with any grpc-specific options sent to the client.
    this._gaxGrpc = new this._gaxModule.GrpcClient(opts);

    // Save options to use in initialize() method.
    this._opts = opts;

    // Save the auth object to the client, for use by other methods.
    this.auth = (this._gaxGrpc.auth as gax.GoogleAuth);

    // Set useJWTAccessWithScope on the auth object.
    this.auth.useJWTAccessWithScope = true;

    // Set defaultServicePath on the auth object.
    this.auth.defaultServicePath = this._servicePath;

    // Set the default scopes in auth client if needed.
    if (servicePath === this._servicePath) {
      this.auth.defaultScopes = staticMembers.scopes;
    }

    // Determine the client header string.
    const clientHeader = [
      `gax/${this._gaxModule.version}`,
      `gapic/${version}`,
    ];
    if (typeof process === 'object' && 'versions' in process) {
      clientHeader.push(`gl-node/${process.versions.node}`);
    } else {
      clientHeader.push(`gl-web/${this._gaxModule.version}`);
    }
    if (!opts.fallback) {
      clientHeader.push(`grpc/${this._gaxGrpc.grpcVersion}`);
    } else {
      clientHeader.push(`rest/${this._gaxGrpc.grpcVersion}`);
    }
    if (opts.libName && opts.libVersion) {
      clientHeader.push(`${opts.libName}/${opts.libVersion}`);
    }
    // Load the applicable protos.
    this._protos = this._gaxGrpc.loadProtoJSON(jsonProtos);

    // This API contains "path templates"; forward-slash-separated
    // identifiers to uniquely identify resources within the API.
    // Create useful helper objects for these.
    this.pathTemplates = {
      customClassPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/customClasses/{custom_class}'
      ),
      locationPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}'
      ),
      phraseSetPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/locations/{location}/phraseSets/{phrase_set}'
      ),
      projectPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}'
      ),
    };

    // Some of the methods on this service return "paged" results,
    // (e.g. 50 results at a time, with tokens to get subsequent
    // pages). Denote the keys used for pagination and results.
    this.descriptors.page = {
      listPhraseSet:
          new this._gaxModule.PageDescriptor('pageToken', 'nextPageToken', 'phraseSets'),
      listCustomClasses:
          new this._gaxModule.PageDescriptor('pageToken', 'nextPageToken', 'customClasses')
    };

    // Put together the default options sent with requests.
    this._defaults = this._gaxGrpc.constructSettings(
        'google.cloud.speech.v1.Adaptation', gapicConfig as gax.ClientConfig,
        opts.clientConfig || {}, {'x-goog-api-client': clientHeader.join(' ')});

    // Set up a dictionary of "inner API calls"; the core implementation
    // of calling the API is handled in `google-gax`, with this code
    // merely providing the destination and request information.
    this.innerApiCalls = {};

    // Add a warn function to the client constructor so it can be easily tested.
    this.warn = this._gaxModule.warn;
  }

  /**
   * Initialize the client.
   * Performs asynchronous operations (such as authentication) and prepares the client.
   * This function will be called automatically when any class method is called for the
   * first time, but if you need to initialize it before calling an actual method,
   * feel free to call initialize() directly.
   *
   * You can await on this method if you want to make sure the client is initialized.
   *
   * @returns {Promise} A promise that resolves to an authenticated service stub.
   */
  initialize() {
    // If the client stub promise is already initialized, return immediately.
    if (this.adaptationStub) {
      return this.adaptationStub;
    }

    // Put together the "service stub" for
    // google.cloud.speech.v1.Adaptation.
    this.adaptationStub = this._gaxGrpc.createStub(
        this._opts.fallback ?
          (this._protos as protobuf.Root).lookupService('google.cloud.speech.v1.Adaptation') :
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (this._protos as any).google.cloud.speech.v1.Adaptation,
        this._opts, this._providedCustomServicePath) as Promise<{[method: string]: Function}>;

    // Iterate over each of the methods that the service provides
    // and create an API call method for each.
    const adaptationStubMethods =
        ['createPhraseSet', 'getPhraseSet', 'listPhraseSet', 'updatePhraseSet', 'deletePhraseSet', 'createCustomClass', 'getCustomClass', 'listCustomClasses', 'updateCustomClass', 'deleteCustomClass'];
    for (const methodName of adaptationStubMethods) {
      const callPromise = this.adaptationStub.then(
        stub => (...args: Array<{}>) => {
          if (this._terminated) {
            return Promise.reject('The client has already been closed.');
          }
          const func = stub[methodName];
          return func.apply(stub, args);
        },
        (err: Error|null|undefined) => () => {
          throw err;
        });

      const descriptor =
        this.descriptors.page[methodName] ||
        undefined;
      const apiCall = this._gaxModule.createApiCall(
        callPromise,
        this._defaults[methodName],
        descriptor,
        this._opts.fallback
      );

      this.innerApiCalls[methodName] = apiCall;
    }

    return this.adaptationStub;
  }

  /**
   * The DNS address for this API service.
   * @deprecated Use the apiEndpoint method of the client instance.
   * @returns {string} The DNS address for this service.
   */
  static get servicePath() {
    if (typeof process === 'object' && typeof process.emitWarning === 'function') {
      process.emitWarning('Static servicePath is deprecated, please use the instance method instead.', 'DeprecationWarning');
    }
    return 'speech.googleapis.com';
  }

  /**
   * The DNS address for this API service - same as servicePath.
   * @deprecated Use the apiEndpoint method of the client instance.
   * @returns {string} The DNS address for this service.
   */
  static get apiEndpoint() {
    if (typeof process === 'object' && typeof process.emitWarning === 'function') {
      process.emitWarning('Static apiEndpoint is deprecated, please use the instance method instead.', 'DeprecationWarning');
    }
    return 'speech.googleapis.com';
  }

  /**
   * The DNS address for this API service.
   * @returns {string} The DNS address for this service.
   */
  get apiEndpoint() {
    return this._servicePath;
  }

  get universeDomain() {
    return this._universeDomain;
  }

  /**
   * The port for this API service.
   * @returns {number} The default port for this service.
   */
  static get port() {
    return 443;
  }

  /**
   * The scopes needed to make gRPC calls for every method defined
   * in this service.
   * @returns {string[]} List of default scopes.
   */
  static get scopes() {
    return [
      'https://www.googleapis.com/auth/cloud-platform'
    ];
  }

  getProjectId(): Promise<string>;
  getProjectId(callback: Callback<string, undefined, undefined>): void;
  /**
   * Return the project ID used by this class.
   * @returns {Promise} A promise that resolves to string containing the project ID.
   */
  getProjectId(callback?: Callback<string, undefined, undefined>):
      Promise<string>|void {
    if (callback) {
      this.auth.getProjectId(callback);
      return;
    }
    return this.auth.getProjectId();
  }

  // -------------------
  // -- Service calls --
  // -------------------
/**
 * Create a set of phrase hints. Each item in the set can be a single word or
 * a multi-word phrase. The items in the PhraseSet are favored by the
 * recognition model when you send a call that includes the PhraseSet.
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.parent
 *   Required. The parent resource where this phrase set will be created.
 *   Format:
 *
 *   `projects/{project}/locations/{location}`
 *
 *   Speech-to-Text supports three locations: `global`, `us` (US North America),
 *   and `eu` (Europe). If you are calling the `speech.googleapis.com`
 *   endpoint, use the `global` location. To specify a region, use a
 *   [regional endpoint](https://cloud.google.com/speech-to-text/docs/endpoints)
 *   with matching `us` or `eu` location value.
 * @param {string} request.phraseSetId
 *   Required. The ID to use for the phrase set, which will become the final
 *   component of the phrase set's resource name.
 *
 *   This value should restrict to letters, numbers, and hyphens, with the first
 *   character a letter, the last a letter or a number, and be 4-63 characters.
 * @param {google.cloud.speech.v1.PhraseSet} request.phraseSet
 *   Required. The phrase set to create.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Promise} - The promise which resolves to an array.
 *   The first element of the array is an object representing {@link protos.google.cloud.speech.v1.PhraseSet|PhraseSet}.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
 *   for more details and examples.
 * @example <caption>include:samples/generated/v1/adaptation.create_phrase_set.js</caption>
 * region_tag:speech_v1_generated_Adaptation_CreatePhraseSet_async
 */
  createPhraseSet(
      request?: protos.google.cloud.speech.v1.ICreatePhraseSetRequest,
      options?: CallOptions):
      Promise<[
        protos.google.cloud.speech.v1.IPhraseSet,
        protos.google.cloud.speech.v1.ICreatePhraseSetRequest|undefined, {}|undefined
      ]>;
  createPhraseSet(
      request: protos.google.cloud.speech.v1.ICreatePhraseSetRequest,
      options: CallOptions,
      callback: Callback<
          protos.google.cloud.speech.v1.IPhraseSet,
          protos.google.cloud.speech.v1.ICreatePhraseSetRequest|null|undefined,
          {}|null|undefined>): void;
  createPhraseSet(
      request: protos.google.cloud.speech.v1.ICreatePhraseSetRequest,
      callback: Callback<
          protos.google.cloud.speech.v1.IPhraseSet,
          protos.google.cloud.speech.v1.ICreatePhraseSetRequest|null|undefined,
          {}|null|undefined>): void;
  createPhraseSet(
      request?: protos.google.cloud.speech.v1.ICreatePhraseSetRequest,
      optionsOrCallback?: CallOptions|Callback<
          protos.google.cloud.speech.v1.IPhraseSet,
          protos.google.cloud.speech.v1.ICreatePhraseSetRequest|null|undefined,
          {}|null|undefined>,
      callback?: Callback<
          protos.google.cloud.speech.v1.IPhraseSet,
          protos.google.cloud.speech.v1.ICreatePhraseSetRequest|null|undefined,
          {}|null|undefined>):
      Promise<[
        protos.google.cloud.speech.v1.IPhraseSet,
        protos.google.cloud.speech.v1.ICreatePhraseSetRequest|undefined, {}|undefined
      ]>|void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    }
    else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'parent': request.parent ?? '',
    });
    this.initialize().catch(err => {throw err});
    this._log.info('createPhraseSet request %j', request);
    const wrappedCallback: Callback<
        protos.google.cloud.speech.v1.IPhraseSet,
        protos.google.cloud.speech.v1.ICreatePhraseSetRequest|null|undefined,
        {}|null|undefined>|undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('createPhraseSet response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls.createPhraseSet(request, options, wrappedCallback)
      ?.then(([response, options, rawResponse]: [
        protos.google.cloud.speech.v1.IPhraseSet,
        protos.google.cloud.speech.v1.ICreatePhraseSetRequest|undefined,
        {}|undefined
      ]) => {
        this._log.info('createPhraseSet response %j', response);
        return [response, options, rawResponse];
      }).catch((error: any) => {
        if (error && 'statusDetails' in error && error.statusDetails instanceof Array) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(jsonProtos) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(error.statusDetails, protos);
        }
        throw error;
      });
  }
/**
 * Get a phrase set.
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.name
 *   Required. The name of the phrase set to retrieve. Format:
 *
 *   `projects/{project}/locations/{location}/phraseSets/{phrase_set}`
 *
 *   Speech-to-Text supports three locations: `global`, `us` (US North America),
 *   and `eu` (Europe). If you are calling the `speech.googleapis.com`
 *   endpoint, use the `global` location. To specify a region, use a
 *   [regional endpoint](https://cloud.google.com/speech-to-text/docs/endpoints)
 *   with matching `us` or `eu` location value.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Promise} - The promise which resolves to an array.
 *   The first element of the array is an object representing {@link protos.google.cloud.speech.v1.PhraseSet|PhraseSet}.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
 *   for more details and examples.
 * @example <caption>include:samples/generated/v1/adaptation.get_phrase_set.js</caption>
 * region_tag:speech_v1_generated_Adaptation_GetPhraseSet_async
 */
  getPhraseSet(
      request?: protos.google.cloud.speech.v1.IGetPhraseSetRequest,
      options?: CallOptions):
      Promise<[
        protos.google.cloud.speech.v1.IPhraseSet,
        protos.google.cloud.speech.v1.IGetPhraseSetRequest|undefined, {}|undefined
      ]>;
  getPhraseSet(
      request: protos.google.cloud.speech.v1.IGetPhraseSetRequest,
      options: CallOptions,
      callback: Callback<
          protos.google.cloud.speech.v1.IPhraseSet,
          protos.google.cloud.speech.v1.IGetPhraseSetRequest|null|undefined,
          {}|null|undefined>): void;
  getPhraseSet(
      request: protos.google.cloud.speech.v1.IGetPhraseSetRequest,
      callback: Callback<
          protos.google.cloud.speech.v1.IPhraseSet,
          protos.google.cloud.speech.v1.IGetPhraseSetRequest|null|undefined,
          {}|null|undefined>): void;
  getPhraseSet(
      request?: protos.google.cloud.speech.v1.IGetPhraseSetRequest,
      optionsOrCallback?: CallOptions|Callback<
          protos.google.cloud.speech.v1.IPhraseSet,
          protos.google.cloud.speech.v1.IGetPhraseSetRequest|null|undefined,
          {}|null|undefined>,
      callback?: Callback<
          protos.google.cloud.speech.v1.IPhraseSet,
          protos.google.cloud.speech.v1.IGetPhraseSetRequest|null|undefined,
          {}|null|undefined>):
      Promise<[
        protos.google.cloud.speech.v1.IPhraseSet,
        protos.google.cloud.speech.v1.IGetPhraseSetRequest|undefined, {}|undefined
      ]>|void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    }
    else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'name': request.name ?? '',
    });
    this.initialize().catch(err => {throw err});
    this._log.info('getPhraseSet request %j', request);
    const wrappedCallback: Callback<
        protos.google.cloud.speech.v1.IPhraseSet,
        protos.google.cloud.speech.v1.IGetPhraseSetRequest|null|undefined,
        {}|null|undefined>|undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('getPhraseSet response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls.getPhraseSet(request, options, wrappedCallback)
      ?.then(([response, options, rawResponse]: [
        protos.google.cloud.speech.v1.IPhraseSet,
        protos.google.cloud.speech.v1.IGetPhraseSetRequest|undefined,
        {}|undefined
      ]) => {
        this._log.info('getPhraseSet response %j', response);
        return [response, options, rawResponse];
      }).catch((error: any) => {
        if (error && 'statusDetails' in error && error.statusDetails instanceof Array) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(jsonProtos) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(error.statusDetails, protos);
        }
        throw error;
      });
  }
/**
 * Update a phrase set.
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {google.cloud.speech.v1.PhraseSet} request.phraseSet
 *   Required. The phrase set to update.
 *
 *   The phrase set's `name` field is used to identify the set to be
 *   updated. Format:
 *
 *   `projects/{project}/locations/{location}/phraseSets/{phrase_set}`
 *
 *   Speech-to-Text supports three locations: `global`, `us` (US North America),
 *   and `eu` (Europe). If you are calling the `speech.googleapis.com`
 *   endpoint, use the `global` location. To specify a region, use a
 *   [regional endpoint](https://cloud.google.com/speech-to-text/docs/endpoints)
 *   with matching `us` or `eu` location value.
 * @param {google.protobuf.FieldMask} request.updateMask
 *   The list of fields to be updated.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Promise} - The promise which resolves to an array.
 *   The first element of the array is an object representing {@link protos.google.cloud.speech.v1.PhraseSet|PhraseSet}.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
 *   for more details and examples.
 * @example <caption>include:samples/generated/v1/adaptation.update_phrase_set.js</caption>
 * region_tag:speech_v1_generated_Adaptation_UpdatePhraseSet_async
 */
  updatePhraseSet(
      request?: protos.google.cloud.speech.v1.IUpdatePhraseSetRequest,
      options?: CallOptions):
      Promise<[
        protos.google.cloud.speech.v1.IPhraseSet,
        protos.google.cloud.speech.v1.IUpdatePhraseSetRequest|undefined, {}|undefined
      ]>;
  updatePhraseSet(
      request: protos.google.cloud.speech.v1.IUpdatePhraseSetRequest,
      options: CallOptions,
      callback: Callback<
          protos.google.cloud.speech.v1.IPhraseSet,
          protos.google.cloud.speech.v1.IUpdatePhraseSetRequest|null|undefined,
          {}|null|undefined>): void;
  updatePhraseSet(
      request: protos.google.cloud.speech.v1.IUpdatePhraseSetRequest,
      callback: Callback<
          protos.google.cloud.speech.v1.IPhraseSet,
          protos.google.cloud.speech.v1.IUpdatePhraseSetRequest|null|undefined,
          {}|null|undefined>): void;
  updatePhraseSet(
      request?: protos.google.cloud.speech.v1.IUpdatePhraseSetRequest,
      optionsOrCallback?: CallOptions|Callback<
          protos.google.cloud.speech.v1.IPhraseSet,
          protos.google.cloud.speech.v1.IUpdatePhraseSetRequest|null|undefined,
          {}|null|undefined>,
      callback?: Callback<
          protos.google.cloud.speech.v1.IPhraseSet,
          protos.google.cloud.speech.v1.IUpdatePhraseSetRequest|null|undefined,
          {}|null|undefined>):
      Promise<[
        protos.google.cloud.speech.v1.IPhraseSet,
        protos.google.cloud.speech.v1.IUpdatePhraseSetRequest|undefined, {}|undefined
      ]>|void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    }
    else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'phrase_set.name': request.phraseSet!.name ?? '',
    });
    this.initialize().catch(err => {throw err});
    this._log.info('updatePhraseSet request %j', request);
    const wrappedCallback: Callback<
        protos.google.cloud.speech.v1.IPhraseSet,
        protos.google.cloud.speech.v1.IUpdatePhraseSetRequest|null|undefined,
        {}|null|undefined>|undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('updatePhraseSet response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls.updatePhraseSet(request, options, wrappedCallback)
      ?.then(([response, options, rawResponse]: [
        protos.google.cloud.speech.v1.IPhraseSet,
        protos.google.cloud.speech.v1.IUpdatePhraseSetRequest|undefined,
        {}|undefined
      ]) => {
        this._log.info('updatePhraseSet response %j', response);
        return [response, options, rawResponse];
      }).catch((error: any) => {
        if (error && 'statusDetails' in error && error.statusDetails instanceof Array) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(jsonProtos) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(error.statusDetails, protos);
        }
        throw error;
      });
  }
/**
 * Delete a phrase set.
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.name
 *   Required. The name of the phrase set to delete. Format:
 *
 *   `projects/{project}/locations/{location}/phraseSets/{phrase_set}`
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Promise} - The promise which resolves to an array.
 *   The first element of the array is an object representing {@link protos.google.protobuf.Empty|Empty}.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
 *   for more details and examples.
 * @example <caption>include:samples/generated/v1/adaptation.delete_phrase_set.js</caption>
 * region_tag:speech_v1_generated_Adaptation_DeletePhraseSet_async
 */
  deletePhraseSet(
      request?: protos.google.cloud.speech.v1.IDeletePhraseSetRequest,
      options?: CallOptions):
      Promise<[
        protos.google.protobuf.IEmpty,
        protos.google.cloud.speech.v1.IDeletePhraseSetRequest|undefined, {}|undefined
      ]>;
  deletePhraseSet(
      request: protos.google.cloud.speech.v1.IDeletePhraseSetRequest,
      options: CallOptions,
      callback: Callback<
          protos.google.protobuf.IEmpty,
          protos.google.cloud.speech.v1.IDeletePhraseSetRequest|null|undefined,
          {}|null|undefined>): void;
  deletePhraseSet(
      request: protos.google.cloud.speech.v1.IDeletePhraseSetRequest,
      callback: Callback<
          protos.google.protobuf.IEmpty,
          protos.google.cloud.speech.v1.IDeletePhraseSetRequest|null|undefined,
          {}|null|undefined>): void;
  deletePhraseSet(
      request?: protos.google.cloud.speech.v1.IDeletePhraseSetRequest,
      optionsOrCallback?: CallOptions|Callback<
          protos.google.protobuf.IEmpty,
          protos.google.cloud.speech.v1.IDeletePhraseSetRequest|null|undefined,
          {}|null|undefined>,
      callback?: Callback<
          protos.google.protobuf.IEmpty,
          protos.google.cloud.speech.v1.IDeletePhraseSetRequest|null|undefined,
          {}|null|undefined>):
      Promise<[
        protos.google.protobuf.IEmpty,
        protos.google.cloud.speech.v1.IDeletePhraseSetRequest|undefined, {}|undefined
      ]>|void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    }
    else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'name': request.name ?? '',
    });
    this.initialize().catch(err => {throw err});
    this._log.info('deletePhraseSet request %j', request);
    const wrappedCallback: Callback<
        protos.google.protobuf.IEmpty,
        protos.google.cloud.speech.v1.IDeletePhraseSetRequest|null|undefined,
        {}|null|undefined>|undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('deletePhraseSet response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls.deletePhraseSet(request, options, wrappedCallback)
      ?.then(([response, options, rawResponse]: [
        protos.google.protobuf.IEmpty,
        protos.google.cloud.speech.v1.IDeletePhraseSetRequest|undefined,
        {}|undefined
      ]) => {
        this._log.info('deletePhraseSet response %j', response);
        return [response, options, rawResponse];
      }).catch((error: any) => {
        if (error && 'statusDetails' in error && error.statusDetails instanceof Array) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(jsonProtos) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(error.statusDetails, protos);
        }
        throw error;
      });
  }
/**
 * Create a custom class.
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.parent
 *   Required. The parent resource where this custom class will be created.
 *   Format:
 *
 *   `projects/{project}/locations/{location}/customClasses`
 *
 *   Speech-to-Text supports three locations: `global`, `us` (US North America),
 *   and `eu` (Europe). If you are calling the `speech.googleapis.com`
 *   endpoint, use the `global` location. To specify a region, use a
 *   [regional endpoint](https://cloud.google.com/speech-to-text/docs/endpoints)
 *   with matching `us` or `eu` location value.
 * @param {string} request.customClassId
 *   Required. The ID to use for the custom class, which will become the final
 *   component of the custom class' resource name.
 *
 *   This value should restrict to letters, numbers, and hyphens, with the first
 *   character a letter, the last a letter or a number, and be 4-63 characters.
 * @param {google.cloud.speech.v1.CustomClass} request.customClass
 *   Required. The custom class to create.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Promise} - The promise which resolves to an array.
 *   The first element of the array is an object representing {@link protos.google.cloud.speech.v1.CustomClass|CustomClass}.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
 *   for more details and examples.
 * @example <caption>include:samples/generated/v1/adaptation.create_custom_class.js</caption>
 * region_tag:speech_v1_generated_Adaptation_CreateCustomClass_async
 */
  createCustomClass(
      request?: protos.google.cloud.speech.v1.ICreateCustomClassRequest,
      options?: CallOptions):
      Promise<[
        protos.google.cloud.speech.v1.ICustomClass,
        protos.google.cloud.speech.v1.ICreateCustomClassRequest|undefined, {}|undefined
      ]>;
  createCustomClass(
      request: protos.google.cloud.speech.v1.ICreateCustomClassRequest,
      options: CallOptions,
      callback: Callback<
          protos.google.cloud.speech.v1.ICustomClass,
          protos.google.cloud.speech.v1.ICreateCustomClassRequest|null|undefined,
          {}|null|undefined>): void;
  createCustomClass(
      request: protos.google.cloud.speech.v1.ICreateCustomClassRequest,
      callback: Callback<
          protos.google.cloud.speech.v1.ICustomClass,
          protos.google.cloud.speech.v1.ICreateCustomClassRequest|null|undefined,
          {}|null|undefined>): void;
  createCustomClass(
      request?: protos.google.cloud.speech.v1.ICreateCustomClassRequest,
      optionsOrCallback?: CallOptions|Callback<
          protos.google.cloud.speech.v1.ICustomClass,
          protos.google.cloud.speech.v1.ICreateCustomClassRequest|null|undefined,
          {}|null|undefined>,
      callback?: Callback<
          protos.google.cloud.speech.v1.ICustomClass,
          protos.google.cloud.speech.v1.ICreateCustomClassRequest|null|undefined,
          {}|null|undefined>):
      Promise<[
        protos.google.cloud.speech.v1.ICustomClass,
        protos.google.cloud.speech.v1.ICreateCustomClassRequest|undefined, {}|undefined
      ]>|void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    }
    else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'parent': request.parent ?? '',
    });
    this.initialize().catch(err => {throw err});
    this._log.info('createCustomClass request %j', request);
    const wrappedCallback: Callback<
        protos.google.cloud.speech.v1.ICustomClass,
        protos.google.cloud.speech.v1.ICreateCustomClassRequest|null|undefined,
        {}|null|undefined>|undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('createCustomClass response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls.createCustomClass(request, options, wrappedCallback)
      ?.then(([response, options, rawResponse]: [
        protos.google.cloud.speech.v1.ICustomClass,
        protos.google.cloud.speech.v1.ICreateCustomClassRequest|undefined,
        {}|undefined
      ]) => {
        this._log.info('createCustomClass response %j', response);
        return [response, options, rawResponse];
      }).catch((error: any) => {
        if (error && 'statusDetails' in error && error.statusDetails instanceof Array) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(jsonProtos) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(error.statusDetails, protos);
        }
        throw error;
      });
  }
/**
 * Get a custom class.
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.name
 *   Required. The name of the custom class to retrieve. Format:
 *
 *   `projects/{project}/locations/{location}/customClasses/{custom_class}`
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Promise} - The promise which resolves to an array.
 *   The first element of the array is an object representing {@link protos.google.cloud.speech.v1.CustomClass|CustomClass}.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
 *   for more details and examples.
 * @example <caption>include:samples/generated/v1/adaptation.get_custom_class.js</caption>
 * region_tag:speech_v1_generated_Adaptation_GetCustomClass_async
 */
  getCustomClass(
      request?: protos.google.cloud.speech.v1.IGetCustomClassRequest,
      options?: CallOptions):
      Promise<[
        protos.google.cloud.speech.v1.ICustomClass,
        protos.google.cloud.speech.v1.IGetCustomClassRequest|undefined, {}|undefined
      ]>;
  getCustomClass(
      request: protos.google.cloud.speech.v1.IGetCustomClassRequest,
      options: CallOptions,
      callback: Callback<
          protos.google.cloud.speech.v1.ICustomClass,
          protos.google.cloud.speech.v1.IGetCustomClassRequest|null|undefined,
          {}|null|undefined>): void;
  getCustomClass(
      request: protos.google.cloud.speech.v1.IGetCustomClassRequest,
      callback: Callback<
          protos.google.cloud.speech.v1.ICustomClass,
          protos.google.cloud.speech.v1.IGetCustomClassRequest|null|undefined,
          {}|null|undefined>): void;
  getCustomClass(
      request?: protos.google.cloud.speech.v1.IGetCustomClassRequest,
      optionsOrCallback?: CallOptions|Callback<
          protos.google.cloud.speech.v1.ICustomClass,
          protos.google.cloud.speech.v1.IGetCustomClassRequest|null|undefined,
          {}|null|undefined>,
      callback?: Callback<
          protos.google.cloud.speech.v1.ICustomClass,
          protos.google.cloud.speech.v1.IGetCustomClassRequest|null|undefined,
          {}|null|undefined>):
      Promise<[
        protos.google.cloud.speech.v1.ICustomClass,
        protos.google.cloud.speech.v1.IGetCustomClassRequest|undefined, {}|undefined
      ]>|void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    }
    else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'name': request.name ?? '',
    });
    this.initialize().catch(err => {throw err});
    this._log.info('getCustomClass request %j', request);
    const wrappedCallback: Callback<
        protos.google.cloud.speech.v1.ICustomClass,
        protos.google.cloud.speech.v1.IGetCustomClassRequest|null|undefined,
        {}|null|undefined>|undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('getCustomClass response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls.getCustomClass(request, options, wrappedCallback)
      ?.then(([response, options, rawResponse]: [
        protos.google.cloud.speech.v1.ICustomClass,
        protos.google.cloud.speech.v1.IGetCustomClassRequest|undefined,
        {}|undefined
      ]) => {
        this._log.info('getCustomClass response %j', response);
        return [response, options, rawResponse];
      }).catch((error: any) => {
        if (error && 'statusDetails' in error && error.statusDetails instanceof Array) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(jsonProtos) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(error.statusDetails, protos);
        }
        throw error;
      });
  }
/**
 * Update a custom class.
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {google.cloud.speech.v1.CustomClass} request.customClass
 *   Required. The custom class to update.
 *
 *   The custom class's `name` field is used to identify the custom class to be
 *   updated. Format:
 *
 *   `projects/{project}/locations/{location}/customClasses/{custom_class}`
 *
 *   Speech-to-Text supports three locations: `global`, `us` (US North America),
 *   and `eu` (Europe). If you are calling the `speech.googleapis.com`
 *   endpoint, use the `global` location. To specify a region, use a
 *   [regional endpoint](https://cloud.google.com/speech-to-text/docs/endpoints)
 *   with matching `us` or `eu` location value.
 * @param {google.protobuf.FieldMask} request.updateMask
 *   The list of fields to be updated.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Promise} - The promise which resolves to an array.
 *   The first element of the array is an object representing {@link protos.google.cloud.speech.v1.CustomClass|CustomClass}.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
 *   for more details and examples.
 * @example <caption>include:samples/generated/v1/adaptation.update_custom_class.js</caption>
 * region_tag:speech_v1_generated_Adaptation_UpdateCustomClass_async
 */
  updateCustomClass(
      request?: protos.google.cloud.speech.v1.IUpdateCustomClassRequest,
      options?: CallOptions):
      Promise<[
        protos.google.cloud.speech.v1.ICustomClass,
        protos.google.cloud.speech.v1.IUpdateCustomClassRequest|undefined, {}|undefined
      ]>;
  updateCustomClass(
      request: protos.google.cloud.speech.v1.IUpdateCustomClassRequest,
      options: CallOptions,
      callback: Callback<
          protos.google.cloud.speech.v1.ICustomClass,
          protos.google.cloud.speech.v1.IUpdateCustomClassRequest|null|undefined,
          {}|null|undefined>): void;
  updateCustomClass(
      request: protos.google.cloud.speech.v1.IUpdateCustomClassRequest,
      callback: Callback<
          protos.google.cloud.speech.v1.ICustomClass,
          protos.google.cloud.speech.v1.IUpdateCustomClassRequest|null|undefined,
          {}|null|undefined>): void;
  updateCustomClass(
      request?: protos.google.cloud.speech.v1.IUpdateCustomClassRequest,
      optionsOrCallback?: CallOptions|Callback<
          protos.google.cloud.speech.v1.ICustomClass,
          protos.google.cloud.speech.v1.IUpdateCustomClassRequest|null|undefined,
          {}|null|undefined>,
      callback?: Callback<
          protos.google.cloud.speech.v1.ICustomClass,
          protos.google.cloud.speech.v1.IUpdateCustomClassRequest|null|undefined,
          {}|null|undefined>):
      Promise<[
        protos.google.cloud.speech.v1.ICustomClass,
        protos.google.cloud.speech.v1.IUpdateCustomClassRequest|undefined, {}|undefined
      ]>|void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    }
    else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'custom_class.name': request.customClass!.name ?? '',
    });
    this.initialize().catch(err => {throw err});
    this._log.info('updateCustomClass request %j', request);
    const wrappedCallback: Callback<
        protos.google.cloud.speech.v1.ICustomClass,
        protos.google.cloud.speech.v1.IUpdateCustomClassRequest|null|undefined,
        {}|null|undefined>|undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('updateCustomClass response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls.updateCustomClass(request, options, wrappedCallback)
      ?.then(([response, options, rawResponse]: [
        protos.google.cloud.speech.v1.ICustomClass,
        protos.google.cloud.speech.v1.IUpdateCustomClassRequest|undefined,
        {}|undefined
      ]) => {
        this._log.info('updateCustomClass response %j', response);
        return [response, options, rawResponse];
      }).catch((error: any) => {
        if (error && 'statusDetails' in error && error.statusDetails instanceof Array) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(jsonProtos) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(error.statusDetails, protos);
        }
        throw error;
      });
  }
/**
 * Delete a custom class.
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.name
 *   Required. The name of the custom class to delete. Format:
 *
 *   `projects/{project}/locations/{location}/customClasses/{custom_class}`
 *
 *   Speech-to-Text supports three locations: `global`, `us` (US North America),
 *   and `eu` (Europe). If you are calling the `speech.googleapis.com`
 *   endpoint, use the `global` location. To specify a region, use a
 *   [regional endpoint](https://cloud.google.com/speech-to-text/docs/endpoints)
 *   with matching `us` or `eu` location value.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Promise} - The promise which resolves to an array.
 *   The first element of the array is an object representing {@link protos.google.protobuf.Empty|Empty}.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods | documentation }
 *   for more details and examples.
 * @example <caption>include:samples/generated/v1/adaptation.delete_custom_class.js</caption>
 * region_tag:speech_v1_generated_Adaptation_DeleteCustomClass_async
 */
  deleteCustomClass(
      request?: protos.google.cloud.speech.v1.IDeleteCustomClassRequest,
      options?: CallOptions):
      Promise<[
        protos.google.protobuf.IEmpty,
        protos.google.cloud.speech.v1.IDeleteCustomClassRequest|undefined, {}|undefined
      ]>;
  deleteCustomClass(
      request: protos.google.cloud.speech.v1.IDeleteCustomClassRequest,
      options: CallOptions,
      callback: Callback<
          protos.google.protobuf.IEmpty,
          protos.google.cloud.speech.v1.IDeleteCustomClassRequest|null|undefined,
          {}|null|undefined>): void;
  deleteCustomClass(
      request: protos.google.cloud.speech.v1.IDeleteCustomClassRequest,
      callback: Callback<
          protos.google.protobuf.IEmpty,
          protos.google.cloud.speech.v1.IDeleteCustomClassRequest|null|undefined,
          {}|null|undefined>): void;
  deleteCustomClass(
      request?: protos.google.cloud.speech.v1.IDeleteCustomClassRequest,
      optionsOrCallback?: CallOptions|Callback<
          protos.google.protobuf.IEmpty,
          protos.google.cloud.speech.v1.IDeleteCustomClassRequest|null|undefined,
          {}|null|undefined>,
      callback?: Callback<
          protos.google.protobuf.IEmpty,
          protos.google.cloud.speech.v1.IDeleteCustomClassRequest|null|undefined,
          {}|null|undefined>):
      Promise<[
        protos.google.protobuf.IEmpty,
        protos.google.cloud.speech.v1.IDeleteCustomClassRequest|undefined, {}|undefined
      ]>|void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    }
    else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'name': request.name ?? '',
    });
    this.initialize().catch(err => {throw err});
    this._log.info('deleteCustomClass request %j', request);
    const wrappedCallback: Callback<
        protos.google.protobuf.IEmpty,
        protos.google.cloud.speech.v1.IDeleteCustomClassRequest|null|undefined,
        {}|null|undefined>|undefined = callback
      ? (error, response, options, rawResponse) => {
          this._log.info('deleteCustomClass response %j', response);
          callback!(error, response, options, rawResponse); // We verified callback above.
        }
      : undefined;
    return this.innerApiCalls.deleteCustomClass(request, options, wrappedCallback)
      ?.then(([response, options, rawResponse]: [
        protos.google.protobuf.IEmpty,
        protos.google.cloud.speech.v1.IDeleteCustomClassRequest|undefined,
        {}|undefined
      ]) => {
        this._log.info('deleteCustomClass response %j', response);
        return [response, options, rawResponse];
      }).catch((error: any) => {
        if (error && 'statusDetails' in error && error.statusDetails instanceof Array) {
          const protos = this._gaxModule.protobuf.Root.fromJSON(jsonProtos) as unknown as gax.protobuf.Type;
          error.statusDetails = decodeAnyProtosInArray(error.statusDetails, protos);
        }
        throw error;
      });
  }

 /**
 * List phrase sets.
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.parent
 *   Required. The parent, which owns this collection of phrase set. Format:
 *
 *   `projects/{project}/locations/{location}`
 *
 *   Speech-to-Text supports three locations: `global`, `us` (US North America),
 *   and `eu` (Europe). If you are calling the `speech.googleapis.com`
 *   endpoint, use the `global` location. To specify a region, use a
 *   [regional endpoint](https://cloud.google.com/speech-to-text/docs/endpoints)
 *   with matching `us` or `eu` location value.
 * @param {number} request.pageSize
 *   The maximum number of phrase sets to return. The service may return
 *   fewer than this value. If unspecified, at most 50 phrase sets will be
 *   returned. The maximum value is 1000; values above 1000 will be coerced to
 *   1000.
 * @param {string} request.pageToken
 *   A page token, received from a previous `ListPhraseSet` call.
 *   Provide this to retrieve the subsequent page.
 *
 *   When paginating, all other parameters provided to `ListPhraseSet` must
 *   match the call that provided the page token.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Promise} - The promise which resolves to an array.
 *   The first element of the array is Array of {@link protos.google.cloud.speech.v1.PhraseSet|PhraseSet}.
 *   The client library will perform auto-pagination by default: it will call the API as many
 *   times as needed and will merge results from all the pages into this array.
 *   Note that it can affect your quota.
 *   We recommend using `listPhraseSetAsync()`
 *   method described below for async iteration which you can stop as needed.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#auto-pagination | documentation }
 *   for more details and examples.
 */
  listPhraseSet(
      request?: protos.google.cloud.speech.v1.IListPhraseSetRequest,
      options?: CallOptions):
      Promise<[
        protos.google.cloud.speech.v1.IPhraseSet[],
        protos.google.cloud.speech.v1.IListPhraseSetRequest|null,
        protos.google.cloud.speech.v1.IListPhraseSetResponse
      ]>;
  listPhraseSet(
      request: protos.google.cloud.speech.v1.IListPhraseSetRequest,
      options: CallOptions,
      callback: PaginationCallback<
          protos.google.cloud.speech.v1.IListPhraseSetRequest,
          protos.google.cloud.speech.v1.IListPhraseSetResponse|null|undefined,
          protos.google.cloud.speech.v1.IPhraseSet>): void;
  listPhraseSet(
      request: protos.google.cloud.speech.v1.IListPhraseSetRequest,
      callback: PaginationCallback<
          protos.google.cloud.speech.v1.IListPhraseSetRequest,
          protos.google.cloud.speech.v1.IListPhraseSetResponse|null|undefined,
          protos.google.cloud.speech.v1.IPhraseSet>): void;
  listPhraseSet(
      request?: protos.google.cloud.speech.v1.IListPhraseSetRequest,
      optionsOrCallback?: CallOptions|PaginationCallback<
          protos.google.cloud.speech.v1.IListPhraseSetRequest,
          protos.google.cloud.speech.v1.IListPhraseSetResponse|null|undefined,
          protos.google.cloud.speech.v1.IPhraseSet>,
      callback?: PaginationCallback<
          protos.google.cloud.speech.v1.IListPhraseSetRequest,
          protos.google.cloud.speech.v1.IListPhraseSetResponse|null|undefined,
          protos.google.cloud.speech.v1.IPhraseSet>):
      Promise<[
        protos.google.cloud.speech.v1.IPhraseSet[],
        protos.google.cloud.speech.v1.IListPhraseSetRequest|null,
        protos.google.cloud.speech.v1.IListPhraseSetResponse
      ]>|void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    }
    else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'parent': request.parent ?? '',
    });
    this.initialize().catch(err => {throw err});
    const wrappedCallback: PaginationCallback<
      protos.google.cloud.speech.v1.IListPhraseSetRequest,
      protos.google.cloud.speech.v1.IListPhraseSetResponse|null|undefined,
      protos.google.cloud.speech.v1.IPhraseSet>|undefined = callback
      ? (error, values, nextPageRequest, rawResponse) => {
          this._log.info('listPhraseSet values %j', values);
          callback!(error, values, nextPageRequest, rawResponse); // We verified callback above.
        }
      : undefined;
    this._log.info('listPhraseSet request %j', request);
    return this.innerApiCalls
      .listPhraseSet(request, options, wrappedCallback)
      ?.then(([response, input, output]: [
        protos.google.cloud.speech.v1.IPhraseSet[],
        protos.google.cloud.speech.v1.IListPhraseSetRequest|null,
        protos.google.cloud.speech.v1.IListPhraseSetResponse
      ]) => {
        this._log.info('listPhraseSet values %j', response);
        return [response, input, output];
      });
  }

/**
 * Equivalent to `listPhraseSet`, but returns a NodeJS Stream object.
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.parent
 *   Required. The parent, which owns this collection of phrase set. Format:
 *
 *   `projects/{project}/locations/{location}`
 *
 *   Speech-to-Text supports three locations: `global`, `us` (US North America),
 *   and `eu` (Europe). If you are calling the `speech.googleapis.com`
 *   endpoint, use the `global` location. To specify a region, use a
 *   [regional endpoint](https://cloud.google.com/speech-to-text/docs/endpoints)
 *   with matching `us` or `eu` location value.
 * @param {number} request.pageSize
 *   The maximum number of phrase sets to return. The service may return
 *   fewer than this value. If unspecified, at most 50 phrase sets will be
 *   returned. The maximum value is 1000; values above 1000 will be coerced to
 *   1000.
 * @param {string} request.pageToken
 *   A page token, received from a previous `ListPhraseSet` call.
 *   Provide this to retrieve the subsequent page.
 *
 *   When paginating, all other parameters provided to `ListPhraseSet` must
 *   match the call that provided the page token.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Stream}
 *   An object stream which emits an object representing {@link protos.google.cloud.speech.v1.PhraseSet|PhraseSet} on 'data' event.
 *   The client library will perform auto-pagination by default: it will call the API as many
 *   times as needed. Note that it can affect your quota.
 *   We recommend using `listPhraseSetAsync()`
 *   method described below for async iteration which you can stop as needed.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#auto-pagination | documentation }
 *   for more details and examples.
 */
  listPhraseSetStream(
      request?: protos.google.cloud.speech.v1.IListPhraseSetRequest,
      options?: CallOptions):
    Transform{
    request = request || {};
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'parent': request.parent ?? '',
    });
    const defaultCallSettings = this._defaults['listPhraseSet'];
    const callSettings = defaultCallSettings.merge(options);
    this.initialize().catch(err => {throw err});
    this._log.info('listPhraseSet stream %j', request);
    return this.descriptors.page.listPhraseSet.createStream(
      this.innerApiCalls.listPhraseSet as GaxCall,
      request,
      callSettings
    );
  }

/**
 * Equivalent to `listPhraseSet`, but returns an iterable object.
 *
 * `for`-`await`-`of` syntax is used with the iterable to get response elements on-demand.
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.parent
 *   Required. The parent, which owns this collection of phrase set. Format:
 *
 *   `projects/{project}/locations/{location}`
 *
 *   Speech-to-Text supports three locations: `global`, `us` (US North America),
 *   and `eu` (Europe). If you are calling the `speech.googleapis.com`
 *   endpoint, use the `global` location. To specify a region, use a
 *   [regional endpoint](https://cloud.google.com/speech-to-text/docs/endpoints)
 *   with matching `us` or `eu` location value.
 * @param {number} request.pageSize
 *   The maximum number of phrase sets to return. The service may return
 *   fewer than this value. If unspecified, at most 50 phrase sets will be
 *   returned. The maximum value is 1000; values above 1000 will be coerced to
 *   1000.
 * @param {string} request.pageToken
 *   A page token, received from a previous `ListPhraseSet` call.
 *   Provide this to retrieve the subsequent page.
 *
 *   When paginating, all other parameters provided to `ListPhraseSet` must
 *   match the call that provided the page token.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Object}
 *   An iterable Object that allows {@link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols | async iteration }.
 *   When you iterate the returned iterable, each element will be an object representing
 *   {@link protos.google.cloud.speech.v1.PhraseSet|PhraseSet}. The API will be called under the hood as needed, once per the page,
 *   so you can stop the iteration when you don't need more results.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#auto-pagination | documentation }
 *   for more details and examples.
 * @example <caption>include:samples/generated/v1/adaptation.list_phrase_set.js</caption>
 * region_tag:speech_v1_generated_Adaptation_ListPhraseSet_async
 */
  listPhraseSetAsync(
      request?: protos.google.cloud.speech.v1.IListPhraseSetRequest,
      options?: CallOptions):
    AsyncIterable<protos.google.cloud.speech.v1.IPhraseSet>{
    request = request || {};
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'parent': request.parent ?? '',
    });
    const defaultCallSettings = this._defaults['listPhraseSet'];
    const callSettings = defaultCallSettings.merge(options);
    this.initialize().catch(err => {throw err});
    this._log.info('listPhraseSet iterate %j', request);
    return this.descriptors.page.listPhraseSet.asyncIterate(
      this.innerApiCalls['listPhraseSet'] as GaxCall,
      request as {},
      callSettings
    ) as AsyncIterable<protos.google.cloud.speech.v1.IPhraseSet>;
  }
 /**
 * List custom classes.
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.parent
 *   Required. The parent, which owns this collection of custom classes. Format:
 *
 *   `projects/{project}/locations/{location}/customClasses`
 *
 *   Speech-to-Text supports three locations: `global`, `us` (US North America),
 *   and `eu` (Europe). If you are calling the `speech.googleapis.com`
 *   endpoint, use the `global` location. To specify a region, use a
 *   [regional endpoint](https://cloud.google.com/speech-to-text/docs/endpoints)
 *   with matching `us` or `eu` location value.
 * @param {number} request.pageSize
 *   The maximum number of custom classes to return. The service may return
 *   fewer than this value. If unspecified, at most 50 custom classes will be
 *   returned. The maximum value is 1000; values above 1000 will be coerced to
 *   1000.
 * @param {string} request.pageToken
 *   A page token, received from a previous `ListCustomClass` call.
 *   Provide this to retrieve the subsequent page.
 *
 *   When paginating, all other parameters provided to `ListCustomClass` must
 *   match the call that provided the page token.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Promise} - The promise which resolves to an array.
 *   The first element of the array is Array of {@link protos.google.cloud.speech.v1.CustomClass|CustomClass}.
 *   The client library will perform auto-pagination by default: it will call the API as many
 *   times as needed and will merge results from all the pages into this array.
 *   Note that it can affect your quota.
 *   We recommend using `listCustomClassesAsync()`
 *   method described below for async iteration which you can stop as needed.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#auto-pagination | documentation }
 *   for more details and examples.
 */
  listCustomClasses(
      request?: protos.google.cloud.speech.v1.IListCustomClassesRequest,
      options?: CallOptions):
      Promise<[
        protos.google.cloud.speech.v1.ICustomClass[],
        protos.google.cloud.speech.v1.IListCustomClassesRequest|null,
        protos.google.cloud.speech.v1.IListCustomClassesResponse
      ]>;
  listCustomClasses(
      request: protos.google.cloud.speech.v1.IListCustomClassesRequest,
      options: CallOptions,
      callback: PaginationCallback<
          protos.google.cloud.speech.v1.IListCustomClassesRequest,
          protos.google.cloud.speech.v1.IListCustomClassesResponse|null|undefined,
          protos.google.cloud.speech.v1.ICustomClass>): void;
  listCustomClasses(
      request: protos.google.cloud.speech.v1.IListCustomClassesRequest,
      callback: PaginationCallback<
          protos.google.cloud.speech.v1.IListCustomClassesRequest,
          protos.google.cloud.speech.v1.IListCustomClassesResponse|null|undefined,
          protos.google.cloud.speech.v1.ICustomClass>): void;
  listCustomClasses(
      request?: protos.google.cloud.speech.v1.IListCustomClassesRequest,
      optionsOrCallback?: CallOptions|PaginationCallback<
          protos.google.cloud.speech.v1.IListCustomClassesRequest,
          protos.google.cloud.speech.v1.IListCustomClassesResponse|null|undefined,
          protos.google.cloud.speech.v1.ICustomClass>,
      callback?: PaginationCallback<
          protos.google.cloud.speech.v1.IListCustomClassesRequest,
          protos.google.cloud.speech.v1.IListCustomClassesResponse|null|undefined,
          protos.google.cloud.speech.v1.ICustomClass>):
      Promise<[
        protos.google.cloud.speech.v1.ICustomClass[],
        protos.google.cloud.speech.v1.IListCustomClassesRequest|null,
        protos.google.cloud.speech.v1.IListCustomClassesResponse
      ]>|void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    }
    else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'parent': request.parent ?? '',
    });
    this.initialize().catch(err => {throw err});
    const wrappedCallback: PaginationCallback<
      protos.google.cloud.speech.v1.IListCustomClassesRequest,
      protos.google.cloud.speech.v1.IListCustomClassesResponse|null|undefined,
      protos.google.cloud.speech.v1.ICustomClass>|undefined = callback
      ? (error, values, nextPageRequest, rawResponse) => {
          this._log.info('listCustomClasses values %j', values);
          callback!(error, values, nextPageRequest, rawResponse); // We verified callback above.
        }
      : undefined;
    this._log.info('listCustomClasses request %j', request);
    return this.innerApiCalls
      .listCustomClasses(request, options, wrappedCallback)
      ?.then(([response, input, output]: [
        protos.google.cloud.speech.v1.ICustomClass[],
        protos.google.cloud.speech.v1.IListCustomClassesRequest|null,
        protos.google.cloud.speech.v1.IListCustomClassesResponse
      ]) => {
        this._log.info('listCustomClasses values %j', response);
        return [response, input, output];
      });
  }

/**
 * Equivalent to `listCustomClasses`, but returns a NodeJS Stream object.
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.parent
 *   Required. The parent, which owns this collection of custom classes. Format:
 *
 *   `projects/{project}/locations/{location}/customClasses`
 *
 *   Speech-to-Text supports three locations: `global`, `us` (US North America),
 *   and `eu` (Europe). If you are calling the `speech.googleapis.com`
 *   endpoint, use the `global` location. To specify a region, use a
 *   [regional endpoint](https://cloud.google.com/speech-to-text/docs/endpoints)
 *   with matching `us` or `eu` location value.
 * @param {number} request.pageSize
 *   The maximum number of custom classes to return. The service may return
 *   fewer than this value. If unspecified, at most 50 custom classes will be
 *   returned. The maximum value is 1000; values above 1000 will be coerced to
 *   1000.
 * @param {string} request.pageToken
 *   A page token, received from a previous `ListCustomClass` call.
 *   Provide this to retrieve the subsequent page.
 *
 *   When paginating, all other parameters provided to `ListCustomClass` must
 *   match the call that provided the page token.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Stream}
 *   An object stream which emits an object representing {@link protos.google.cloud.speech.v1.CustomClass|CustomClass} on 'data' event.
 *   The client library will perform auto-pagination by default: it will call the API as many
 *   times as needed. Note that it can affect your quota.
 *   We recommend using `listCustomClassesAsync()`
 *   method described below for async iteration which you can stop as needed.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#auto-pagination | documentation }
 *   for more details and examples.
 */
  listCustomClassesStream(
      request?: protos.google.cloud.speech.v1.IListCustomClassesRequest,
      options?: CallOptions):
    Transform{
    request = request || {};
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'parent': request.parent ?? '',
    });
    const defaultCallSettings = this._defaults['listCustomClasses'];
    const callSettings = defaultCallSettings.merge(options);
    this.initialize().catch(err => {throw err});
    this._log.info('listCustomClasses stream %j', request);
    return this.descriptors.page.listCustomClasses.createStream(
      this.innerApiCalls.listCustomClasses as GaxCall,
      request,
      callSettings
    );
  }

/**
 * Equivalent to `listCustomClasses`, but returns an iterable object.
 *
 * `for`-`await`-`of` syntax is used with the iterable to get response elements on-demand.
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.parent
 *   Required. The parent, which owns this collection of custom classes. Format:
 *
 *   `projects/{project}/locations/{location}/customClasses`
 *
 *   Speech-to-Text supports three locations: `global`, `us` (US North America),
 *   and `eu` (Europe). If you are calling the `speech.googleapis.com`
 *   endpoint, use the `global` location. To specify a region, use a
 *   [regional endpoint](https://cloud.google.com/speech-to-text/docs/endpoints)
 *   with matching `us` or `eu` location value.
 * @param {number} request.pageSize
 *   The maximum number of custom classes to return. The service may return
 *   fewer than this value. If unspecified, at most 50 custom classes will be
 *   returned. The maximum value is 1000; values above 1000 will be coerced to
 *   1000.
 * @param {string} request.pageToken
 *   A page token, received from a previous `ListCustomClass` call.
 *   Provide this to retrieve the subsequent page.
 *
 *   When paginating, all other parameters provided to `ListCustomClass` must
 *   match the call that provided the page token.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Object}
 *   An iterable Object that allows {@link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols | async iteration }.
 *   When you iterate the returned iterable, each element will be an object representing
 *   {@link protos.google.cloud.speech.v1.CustomClass|CustomClass}. The API will be called under the hood as needed, once per the page,
 *   so you can stop the iteration when you don't need more results.
 *   Please see the {@link https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#auto-pagination | documentation }
 *   for more details and examples.
 * @example <caption>include:samples/generated/v1/adaptation.list_custom_classes.js</caption>
 * region_tag:speech_v1_generated_Adaptation_ListCustomClasses_async
 */
  listCustomClassesAsync(
      request?: protos.google.cloud.speech.v1.IListCustomClassesRequest,
      options?: CallOptions):
    AsyncIterable<protos.google.cloud.speech.v1.ICustomClass>{
    request = request || {};
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = this._gaxModule.routingHeader.fromParams({
      'parent': request.parent ?? '',
    });
    const defaultCallSettings = this._defaults['listCustomClasses'];
    const callSettings = defaultCallSettings.merge(options);
    this.initialize().catch(err => {throw err});
    this._log.info('listCustomClasses iterate %j', request);
    return this.descriptors.page.listCustomClasses.asyncIterate(
      this.innerApiCalls['listCustomClasses'] as GaxCall,
      request as {},
      callSettings
    ) as AsyncIterable<protos.google.cloud.speech.v1.ICustomClass>;
  }
  // --------------------
  // -- Path templates --
  // --------------------

  /**
   * Return a fully-qualified customClass resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} custom_class
   * @returns {string} Resource name string.
   */
  customClassPath(project:string,location:string,customClass:string) {
    return this.pathTemplates.customClassPathTemplate.render({
      project: project,
      location: location,
      custom_class: customClass,
    });
  }

  /**
   * Parse the project from CustomClass resource.
   *
   * @param {string} customClassName
   *   A fully-qualified path representing CustomClass resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromCustomClassName(customClassName: string) {
    return this.pathTemplates.customClassPathTemplate.match(customClassName).project;
  }

  /**
   * Parse the location from CustomClass resource.
   *
   * @param {string} customClassName
   *   A fully-qualified path representing CustomClass resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromCustomClassName(customClassName: string) {
    return this.pathTemplates.customClassPathTemplate.match(customClassName).location;
  }

  /**
   * Parse the custom_class from CustomClass resource.
   *
   * @param {string} customClassName
   *   A fully-qualified path representing CustomClass resource.
   * @returns {string} A string representing the custom_class.
   */
  matchCustomClassFromCustomClassName(customClassName: string) {
    return this.pathTemplates.customClassPathTemplate.match(customClassName).custom_class;
  }

  /**
   * Return a fully-qualified location resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @returns {string} Resource name string.
   */
  locationPath(project:string,location:string) {
    return this.pathTemplates.locationPathTemplate.render({
      project: project,
      location: location,
    });
  }

  /**
   * Parse the project from Location resource.
   *
   * @param {string} locationName
   *   A fully-qualified path representing Location resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromLocationName(locationName: string) {
    return this.pathTemplates.locationPathTemplate.match(locationName).project;
  }

  /**
   * Parse the location from Location resource.
   *
   * @param {string} locationName
   *   A fully-qualified path representing Location resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromLocationName(locationName: string) {
    return this.pathTemplates.locationPathTemplate.match(locationName).location;
  }

  /**
   * Return a fully-qualified phraseSet resource name string.
   *
   * @param {string} project
   * @param {string} location
   * @param {string} phrase_set
   * @returns {string} Resource name string.
   */
  phraseSetPath(project:string,location:string,phraseSet:string) {
    return this.pathTemplates.phraseSetPathTemplate.render({
      project: project,
      location: location,
      phrase_set: phraseSet,
    });
  }

  /**
   * Parse the project from PhraseSet resource.
   *
   * @param {string} phraseSetName
   *   A fully-qualified path representing PhraseSet resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromPhraseSetName(phraseSetName: string) {
    return this.pathTemplates.phraseSetPathTemplate.match(phraseSetName).project;
  }

  /**
   * Parse the location from PhraseSet resource.
   *
   * @param {string} phraseSetName
   *   A fully-qualified path representing PhraseSet resource.
   * @returns {string} A string representing the location.
   */
  matchLocationFromPhraseSetName(phraseSetName: string) {
    return this.pathTemplates.phraseSetPathTemplate.match(phraseSetName).location;
  }

  /**
   * Parse the phrase_set from PhraseSet resource.
   *
   * @param {string} phraseSetName
   *   A fully-qualified path representing PhraseSet resource.
   * @returns {string} A string representing the phrase_set.
   */
  matchPhraseSetFromPhraseSetName(phraseSetName: string) {
    return this.pathTemplates.phraseSetPathTemplate.match(phraseSetName).phrase_set;
  }

  /**
   * Return a fully-qualified project resource name string.
   *
   * @param {string} project
   * @returns {string} Resource name string.
   */
  projectPath(project:string) {
    return this.pathTemplates.projectPathTemplate.render({
      project: project,
    });
  }

  /**
   * Parse the project from Project resource.
   *
   * @param {string} projectName
   *   A fully-qualified path representing Project resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromProjectName(projectName: string) {
    return this.pathTemplates.projectPathTemplate.match(projectName).project;
  }

  /**
   * Terminate the gRPC channel and close the client.
   *
   * The client will no longer be usable and all future behavior is undefined.
   * @returns {Promise} A promise that resolves when the client is closed.
   */
  close(): Promise<void> {
    if (this.adaptationStub && !this._terminated) {
      return this.adaptationStub.then(stub => {
        this._log.info('ending gRPC channel');
        this._terminated = true;
        stub.close();
      });
    }
    return Promise.resolve();
  }
}