// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.cloud.apphub.v1;

import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/timestamp.proto";

option csharp_namespace = "Google.Cloud.AppHub.V1";
option go_package = "cloud.google.com/go/apphub/apiv1/apphubpb;apphubpb";
option java_multiple_files = true;
option java_outer_classname = "BoundaryProto";
option java_package = "com.google.cloud.apphub.v1";
option php_namespace = "Google\\Cloud\\AppHub\\V1";
option ruby_package = "Google::Cloud::AppHub::V1";

// Application management boundary.
message Boundary {
  option (google.api.resource) = {
    type: "apphub.googleapis.com/Boundary"
    pattern: "projects/{project}/locations/{location}/boundary"
    plural: "boundaries"
    singular: "boundary"
  };

  // Boundary management type.
  enum Type {
    // Unspecified type.
    TYPE_UNSPECIFIED = 0;

    // The Boundary automatically includes all descendants of the CRM node.
    AUTOMATIC = 1;

    // The list of projects within the Boundary is managed by the user.
    MANUAL = 2;

    // The Boundary automatically includes all descendants of the CRM node,
    // which is set via App Management folder capability.
    MANAGED_AUTOMATIC = 3;
  }

  // The scope defining the boundary.
  oneof scope {
    // Optional. The resource name of the CRM node being attached to the
    // boundary.
    // Format: `projects/{project-number}` or `projects/{project-id}`
    string crm_node = 4 [(google.api.field_behavior) = OPTIONAL];
  }

  // Identifier. The resource name of the boundary.
  // Format: "projects/{project}/locations/{location}/boundary"
  string name = 1 [(google.api.field_behavior) = IDENTIFIER];

  // Output only. Create time.
  google.protobuf.Timestamp create_time = 2
      [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. Update time.
  google.protobuf.Timestamp update_time = 3
      [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. Boundary type.
  Type type = 5 [(google.api.field_behavior) = OUTPUT_ONLY];
}
