// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.cloud.apphub.v1;

import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/struct.proto";

option csharp_namespace = "Google.Cloud.AppHub.V1";
option go_package = "cloud.google.com/go/apphub/apiv1/apphubpb;apphubpb";
option java_multiple_files = true;
option java_outer_classname = "PropertiesProto";
option java_package = "com.google.cloud.apphub.v1";
option php_namespace = "Google\\Cloud\\AppHub\\V1";
option ruby_package = "Google::Cloud::AppHub::V1";

// The functional type of a service or workload.
message FunctionalType {
  // The functional type of a service or workload.
  enum Type {
    // Unspecified type.
    TYPE_UNSPECIFIED = 0;

    // Agent type.
    AGENT = 1;

    // MCP Server type.
    MCP_SERVER = 2;

    // Endpoint type.
    ENDPOINT = 3;
  }

  // Output only. The functional type of a service or workload.
  Type type = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
}

// The registration type of a service.
message RegistrationType {
  // The registration type of a service.
  enum Type {
    // Unspecified registration type. Defaults to EXCLUSIVE.
    TYPE_UNSPECIFIED = 0;

    // The service can only be registered to one application.
    EXCLUSIVE = 1;

    // The service can be registered to multiple applications.
    SHARED = 2;
  }

  // Output only. The registration type of a service.
  Type type = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
}

// Additional metadata for a Service or Workload.
message ExtendedMetadata {
  // Output only. The metadata contents.
  google.protobuf.Struct metadata_struct = 1
      [(google.api.field_behavior) = OUTPUT_ONLY];
}

// The identity associated with a service or workload.
message Identity {
  // Output only. The principal of the identity.
  //
  // Supported formats:
  //
  // * `sa://my-sa@PROJECT_ID.iam.gserviceaccount.com` for GCP Service Account
  // * `principal://POOL_ID.global.PROJECT_NUMBER.workload.id.goog/ns/NAMESPACE_ID/sa/MANAGED_IDENTITY_ID` for Managed Workload Identity
  string principal = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
}
