// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as v1p1beta1 from './v1p1beta1';
const AdaptationClient = v1p1beta1.AdaptationClient;
type AdaptationClient = v1p1beta1.AdaptationClient;
const SpeechClient = v1p1beta1.SpeechClient;
type SpeechClient = v1p1beta1.SpeechClient;
export {v1p1beta1, AdaptationClient, SpeechClient};
export default {v1p1beta1, AdaptationClient, SpeechClient};
import * as protos from '../protos/protos';
export {protos}
