type: google.api.Service
config_version: 3
name: cloudtasks.googleapis.com
title: Cloud Tasks API

apis:
- name: google.cloud.location.Locations
- name: google.cloud.tasks.v2beta3.CloudTasks
- name: google.longrunning.Operations

documentation:
  summary: Manages the execution of large numbers of distributed requests.
  overview: |-
    Cloud Tasks manages the execution of large numbers of distributed
    requests.

    For more information, see https://cloud.google.com/tasks/.
  rules:
  - selector: google.cloud.location.Locations.GetLocation
    description: Gets information about a location.

  - selector: google.cloud.location.Locations.ListLocations
    description: |-
      Lists information about the supported locations for this service.

      This method lists locations based on the resource scope provided in
      the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
      **Global locations**: If `name` is empty, the method lists the
      public locations available to all projects. * **Project-specific
      locations**: If `name` follows the format
      `projects/{project}`, the method lists locations visible to that
      specific project. This includes public, private, or other
      project-specific locations enabled for the project.

      For gRPC and client library implementations, the resource name is
      passed as the `name` field. For direct service calls, the resource
      name is
      incorporated into the request path based on the specific service
      implementation and version.

http:
  rules:
  - selector: google.cloud.location.Locations.GetLocation
    get: '/v2beta3/{name=projects/*/locations/*}'
  - selector: google.cloud.location.Locations.ListLocations
    get: '/v2beta3/{name=projects/*}/locations'
  - selector: google.longrunning.Operations.GetOperation
    get: '/v2beta3/{name=projects/*/locations/*/operations/*}'

authentication:
  rules:
  - selector: google.cloud.location.Locations.GetLocation
    oauth:
      canonical_scopes: |-
        https://www.googleapis.com/auth/cloud-platform
  - selector: google.cloud.location.Locations.ListLocations
    oauth:
      canonical_scopes: |-
        https://www.googleapis.com/auth/cloud-platform
  - selector: 'google.cloud.tasks.v2beta3.CloudTasks.*'
    oauth:
      canonical_scopes: |-
        https://www.googleapis.com/auth/cloud-platform
  - selector: google.longrunning.Operations.GetOperation
    oauth:
      canonical_scopes: |-
        https://www.googleapis.com/auth/cloud-platform
