// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.googleads.v25.enums;

option csharp_namespace = "Google.Ads.GoogleAds.V25.Enums";
option go_package = "google.golang.org/genproto/googleapis/ads/googleads/v25/enums;enums";
option java_multiple_files = true;
option java_outer_classname = "LoyaltyMembershipProto";
option java_package = "com.google.ads.googleads.v25.enums";
option objc_class_prefix = "GAA";
option php_namespace = "Google\\Ads\\GoogleAds\\V25\\Enums";
option ruby_package = "Google::Ads::GoogleAds::V25::Enums";

// Container for enumeration of loyalty membership.
message LoyaltyMembershipEnum {
  // Enumerates loyalty membership.
  enum LoyaltyMembership {
    // Not specified.
    UNSPECIFIED = 0;

    // Unknown.
    UNKNOWN = 1;

    // The user is not a member of the loyalty program.
    NONMEMBER = 2;

    // The user is a tier 1 member of the loyalty program.
    TIER1 = 3;

    // The user is a tier 2 member of the loyalty program.
    TIER2 = 4;

    // The user is a tier 3 member of the loyalty program.
    TIER3 = 5;

    // The user is a tier 4 member of the loyalty program.
    TIER4 = 6;

    // The user is a tier 5 member of the loyalty program.
    TIER5 = 7;

    // The user is a tier 6 member of the loyalty program.
    TIER6 = 8;

    // The user is a tier 7 member of the loyalty program.
    TIER7 = 9;
  }
}
