// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.googleads.v25.enums;

option csharp_namespace = "Google.Ads.GoogleAds.V25.Enums";
option go_package = "google.golang.org/genproto/googleapis/ads/googleads/v25/enums;enums";
option java_multiple_files = true;
option java_outer_classname = "SurveySubjectTypeProto";
option java_package = "com.google.ads.googleads.v25.enums";
option objc_class_prefix = "GAA";
option php_namespace = "Google\\Ads\\GoogleAds\\V25\\Enums";
option ruby_package = "Google::Ads::GoogleAds::V25::Enums";

// Container for enum
message SurveySubjectTypeEnum {
  // The enum
  enum SurveySubjectType {
    // Not specified.
    UNSPECIFIED = 0;

    // Unknown value.
    UNKNOWN = 1;

    // Generic Brand
    GENERIC_BRAND = 2;

    // Generic Product
    GENERIC_PRODUCT = 3;

    // Generic Service
    GENERIC_SERVICE = 4;

    // App
    APP = 5;

    // Apps Dating Services
    APPS_DATING_SERVICES = 6;

    // Apps Podcasts
    APPS_PODCASTS = 7;

    // Apps Digital Comics
    APPS_DIGITAL_COMICS = 8;

    // Automotive Battery
    AUTOMOTIVE_BATTERY = 9;

    // Automotive Brand
    AUTOMOTIVE_BRAND = 10;

    // Automotive Car Rental
    AUTOMOTIVE_CAR_RENTAL = 11;

    // Automotive Car Service
    AUTOMOTIVE_CAR_SERVICE = 12;

    // Automotive Electric Car Brand
    AUTOMOTIVE_ELECTRIC_CAR_BRAND = 13;

    // Automotive Gas Stations
    AUTOMOTIVE_GAS_STATIONS = 14;

    // Automotive Motorcycle
    AUTOMOTIVE_MOTORCYCLE = 15;

    // Automotive Oil
    AUTOMOTIVE_OIL = 16;

    // Automotive Product
    AUTOMOTIVE_PRODUCT = 17;

    // Automotive Tires Brand
    AUTOMOTIVE_TIRES_BRAND = 18;

    // Bim Company
    BIM_COMPANY = 19;

    // Bim Enterprise Services Company
    BIM_ENTERPRISE_SERVICES_COMPANY = 20;

    // Bim Job
    BIM_JOB = 21;

    // Bim Marketing Company
    BIM_MARKETING_COMPANY = 22;

    // Bim Recruiting
    BIM_RECRUITING = 23;

    // Bim Shipping
    BIM_SHIPPING = 24;

    // Cpg Baby Care Brand
    CPG_BABY_CARE_BRAND = 25;

    // Cpg Baby Care Product
    CPG_BABY_CARE_PRODUCT = 26;

    // Cpg Beauty Brand
    CPG_BEAUTY_BRAND = 27;

    // Cpg Beauty Product
    CPG_BEAUTY_PRODUCT = 28;

    // Cpg Beauty And Personal Care Brand
    CPG_BEAUTY_AND_PERSONAL_CARE_BRAND = 29;

    // Cpg Beauty And Personal Care Product
    CPG_BEAUTY_AND_PERSONAL_CARE_PRODUCT = 30;

    // Cpg Body Wash Brand
    CPG_BODY_WASH_BRAND = 31;

    // Cpg Body Wash Product
    CPG_BODY_WASH_PRODUCT = 32;

    // Cpg Drain Cleaners
    CPG_DRAIN_CLEANERS = 33;

    // Cpg Fragrance Brand
    CPG_FRAGRANCE_BRAND = 34;

    // Cpg Fragrance Product
    CPG_FRAGRANCE_PRODUCT = 35;

    // Cpg Hair Care Brand
    CPG_HAIR_CARE_BRAND = 36;

    // Cpg Hair Care Product
    CPG_HAIR_CARE_PRODUCT = 37;

    // Cpg Household Cleaning Brand
    CPG_HOUSEHOLD_CLEANING_BRAND = 38;

    // Cpg Household Cleaning Product
    CPG_HOUSEHOLD_CLEANING_PRODUCT = 39;

    // Cpg Laundry Brand
    CPG_LAUNDRY_BRAND = 40;

    // Cpg Make Up Brand
    CPG_MAKE_UP_BRAND = 41;

    // Cpg Make Up Product
    CPG_MAKE_UP_PRODUCT = 42;

    // Cpg Mouthwash Brand
    CPG_MOUTHWASH_BRAND = 43;

    // Cpg Office Supplies Brand
    CPG_OFFICE_SUPPLIES_BRAND = 44;

    // Cpg Office Supplies Product
    CPG_OFFICE_SUPPLIES_PRODUCT = 45;

    // Cpg Oral Care Brand
    CPG_ORAL_CARE_BRAND = 46;

    // Cpg Personal Care Brand
    CPG_PERSONAL_CARE_BRAND = 47;

    // Cpg Personal Care Product
    CPG_PERSONAL_CARE_PRODUCT = 48;

    // Cpg Skin Care Brand
    CPG_SKIN_CARE_BRAND = 49;

    // Cpg Skin Care Product
    CPG_SKIN_CARE_PRODUCT = 50;

    // Education Business Programs
    EDUCATION_BUSINESS_PROGRAMS = 51;

    // Education Masters Programs
    EDUCATION_MASTERS_PROGRAMS = 52;

    // Education Nursing Programs
    EDUCATION_NURSING_PROGRAMS = 53;

    // Education It Programs
    EDUCATION_IT_PROGRAMS = 54;

    // Education Offline
    EDUCATION_OFFLINE = 55;

    // Education Online
    EDUCATION_ONLINE = 56;

    // Education Program
    EDUCATION_PROGRAM = 57;

    // Education Test Preparation
    EDUCATION_TEST_PREPARATION = 58;

    // Fbr Beer Brand
    FBR_BEER_BRAND = 59;

    // Fbr Beverage Brand
    FBR_BEVERAGE_BRAND = 60;

    // Fbr Beverage Product
    FBR_BEVERAGE_PRODUCT = 61;

    // Fbr Breakfast Food Brand
    FBR_BREAKFAST_FOOD_BRAND = 62;

    // Fbr Breakfast Food Product
    FBR_BREAKFAST_FOOD_PRODUCT = 63;

    // Fbr Candy
    FBR_CANDY = 64;

    // Fbr Cheese
    FBR_CHEESE = 65;

    // Fbr Chips Brand
    FBR_CHIPS_BRAND = 66;

    // Fbr Chips Product
    FBR_CHIPS_PRODUCT = 67;

    // Fbr Chocolate Brand
    FBR_CHOCOLATE_BRAND = 68;

    // Fbr Chocolate Product
    FBR_CHOCOLATE_PRODUCT = 69;

    // Fbr Coffee Brand
    FBR_COFFEE_BRAND = 70;

    // Fbr Coffee Product
    FBR_COFFEE_PRODUCT = 71;

    // Fbr Cold Drink Brand
    FBR_COLD_DRINK_BRAND = 72;

    // Fbr Cold Drink Product
    FBR_COLD_DRINK_PRODUCT = 73;

    // Fbr Cookies
    FBR_COOKIES = 74;

    // Fbr Dogfood Brand
    FBR_DOGFOOD_BRAND = 75;

    // Fbr Dogfood Product
    FBR_DOGFOOD_PRODUCT = 76;

    // Fbr Dog Treats Brand
    FBR_DOG_TREATS_BRAND = 77;

    // Fbr Food Brand
    FBR_FOOD_BRAND = 78;

    // Fbr Food Delivery Brand
    FBR_FOOD_DELIVERY_BRAND = 79;

    // Fbr Food Product
    FBR_FOOD_PRODUCT = 80;

    // Fbr Ice Cream Brand
    FBR_ICE_CREAM_BRAND = 81;

    // Fbr Ice Cream Product
    FBR_ICE_CREAM_PRODUCT = 82;

    // Fbr Pet Food Brand
    FBR_PET_FOOD_BRAND = 83;

    // Fbr Pet Food Product
    FBR_PET_FOOD_PRODUCT = 84;

    // Fbr Pet Supply Brand
    FBR_PET_SUPPLY_BRAND = 85;

    // Fbr Pet Supply Product
    FBR_PET_SUPPLY_PRODUCT = 86;

    // Fbr Restaurant
    FBR_RESTAURANT = 87;

    // Fbr Restaurant Delivery Service Brand
    FBR_RESTAURANT_DELIVERY_SERVICE_BRAND = 88;

    // Fbr Restaurant Delivery Service Product
    FBR_RESTAURANT_DELIVERY_SERVICE_PRODUCT = 89;

    // Fbr Snacks Brand
    FBR_SNACKS_BRAND = 90;

    // Fbr Snacks Product
    FBR_SNACKS_PRODUCT = 91;

    // Fbr Soda Brand
    FBR_SODA_BRAND = 92;

    // Fbr Soda Product
    FBR_SODA_PRODUCT = 93;

    // Fbr Spirit Brand
    FBR_SPIRIT_BRAND = 94;

    // Fbr Spirit Product
    FBR_SPIRIT_PRODUCT = 95;

    // Fbr Whey Protein Brand
    FBR_WHEY_PROTEIN_BRAND = 96;

    // Fbr Wine
    FBR_WINE = 97;

    // Finance Accounting Brand
    FINANCE_ACCOUNTING_BRAND = 98;

    // Finance Bank
    FINANCE_BANK = 99;

    // Finance Credit Card Brand
    FINANCE_CREDIT_CARD_BRAND = 100;

    // Finance Credit Card Product
    FINANCE_CREDIT_CARD_PRODUCT = 101;

    // Finance Financial Services
    FINANCE_FINANCIAL_SERVICES = 102;

    // Finance Insurance
    FINANCE_INSURANCE = 103;

    // Finance Investment Services
    FINANCE_INVESTMENT_SERVICES = 104;

    // Finance Loan Provider
    FINANCE_LOAN_PROVIDER = 105;

    // Finance Mortgage Company
    FINANCE_MORTGAGE_COMPANY = 106;

    // Finance Payments Processing
    FINANCE_PAYMENTS_PROCESSING = 107;

    // Finance Payments Systems
    FINANCE_PAYMENTS_SYSTEMS = 108;

    // Finance Taxes Brand
    FINANCE_TAXES_BRAND = 109;

    // Finance Taxes Product
    FINANCE_TAXES_PRODUCT = 110;

    // Gambling Casino
    GAMBLING_CASINO = 111;

    // Gambling Daily Fantasy Sport
    GAMBLING_DAILY_FANTASY_SPORT = 112;

    // Gambling Gambling Site
    GAMBLING_GAMBLING_SITE = 113;

    // Gambling Lottery
    GAMBLING_LOTTERY = 114;

    // Gambling Sports Betting Site
    GAMBLING_SPORTS_BETTING_SITE = 115;

    // Government Anti Smoking
    GOVERNMENT_ANTI_SMOKING = 116;

    // Government Military
    GOVERNMENT_MILITARY = 117;

    // Government Organization
    GOVERNMENT_ORGANIZATION = 118;

    // Government Program
    GOVERNMENT_PROGRAM = 119;

    // Government Public Health Behaviors
    GOVERNMENT_PUBLIC_HEALTH_BEHAVIORS = 120;

    // Government Public Health Issue
    GOVERNMENT_PUBLIC_HEALTH_ISSUE = 121;

    // Government Public Health Topic
    GOVERNMENT_PUBLIC_HEALTH_TOPIC = 122;

    // Government Service
    GOVERNMENT_SERVICE = 123;

    // Healthcare Gyms
    HEALTHCARE_GYMS = 124;

    // Healthcare Health Insurance Brand
    HEALTHCARE_HEALTH_INSURANCE_BRAND = 125;

    // Healthcare Multivitamins
    HEALTHCARE_MULTIVITAMINS = 126;

    // Healthcare Sports Supplements
    HEALTHCARE_SPORTS_SUPPLEMENTS = 127;

    // Healthcare Weight Loss Brand
    HEALTHCARE_WEIGHT_LOSS_BRAND = 128;

    // Healthcare Weight Loss Product
    HEALTHCARE_WEIGHT_LOSS_PRODUCT = 129;

    // Home Services Cable Tv
    HOME_SERVICES_CABLE_TV = 130;

    // Home Services Energy Brand
    HOME_SERVICES_ENERGY_BRAND = 131;

    // Home Services Household Services Company
    HOME_SERVICES_HOUSEHOLD_SERVICES_COMPANY = 132;

    // Home Services Internet Service
    HOME_SERVICES_INTERNET_SERVICE = 133;

    // Home Services Mobile Phone
    HOME_SERVICES_MOBILE_PHONE = 134;

    // Home Services Pay Tv Channel
    HOME_SERVICES_PAY_TV_CHANNEL = 135;

    // Home Services Pay Tv Network
    HOME_SERVICES_PAY_TV_NETWORK = 136;

    // Local Charity
    LOCAL_CHARITY = 137;

    // Local Classifieds Site
    LOCAL_CLASSIFIEDS_SITE = 138;

    // Local Flower Brand
    LOCAL_FLOWER_BRAND = 139;

    // Local Job Classifieds Site
    LOCAL_JOB_CLASSIFIEDS_SITE = 140;

    // Local Law Firms
    LOCAL_LAW_FIRMS = 141;

    // Local Real Estate Site
    LOCAL_REAL_ESTATE_SITE = 142;

    // Media And Entertainment Download Site
    MEDIA_AND_ENTERTAINMENT_DOWNLOAD_SITE = 143;

    // Media And Entertainment Dvd
    MEDIA_AND_ENTERTAINMENT_DVD = 144;

    // Media And Entertainment Event
    MEDIA_AND_ENTERTAINMENT_EVENT = 145;

    // Media And Entertainment Game
    MEDIA_AND_ENTERTAINMENT_GAME = 146;

    // Media And Entertainment Gaming Products
    MEDIA_AND_ENTERTAINMENT_GAMING_PRODUCTS = 147;

    // Media And Entertainment Live Event
    MEDIA_AND_ENTERTAINMENT_LIVE_EVENT = 148;

    // Media And Entertainment Mobile Game
    MEDIA_AND_ENTERTAINMENT_MOBILE_GAME = 149;

    // Media And Entertainment Movie
    MEDIA_AND_ENTERTAINMENT_MOVIE = 150;

    // Media And Entertainment Movie Digital Download
    MEDIA_AND_ENTERTAINMENT_MOVIE_DIGITAL_DOWNLOAD = 151;

    // Media And Entertainment Music Artist
    MEDIA_AND_ENTERTAINMENT_MUSIC_ARTIST = 152;

    // Media And Entertainment Music Releases
    MEDIA_AND_ENTERTAINMENT_MUSIC_RELEASES = 153;

    // Media And Entertainment Playlists
    MEDIA_AND_ENTERTAINMENT_PLAYLISTS = 154;

    // Media And Entertainment Show
    MEDIA_AND_ENTERTAINMENT_SHOW = 155;

    // Media And Entertainment Show Digital Download
    MEDIA_AND_ENTERTAINMENT_SHOW_DIGITAL_DOWNLOAD = 156;

    // Media And Entertainment Sports
    MEDIA_AND_ENTERTAINMENT_SPORTS = 157;

    // Media And Entertainment Streaming Site
    MEDIA_AND_ENTERTAINMENT_STREAMING_SITE = 158;

    // Media And Entertainment Title Digital Download
    MEDIA_AND_ENTERTAINMENT_TITLE_DIGITAL_DOWNLOAD = 159;

    // Media And Entertainment Tv Channel
    MEDIA_AND_ENTERTAINMENT_TV_CHANNEL = 160;

    // Media And Entertainment Tv Show
    MEDIA_AND_ENTERTAINMENT_TV_SHOW = 161;

    // Media And Entertainment Tv Show Digital Download
    MEDIA_AND_ENTERTAINMENT_TV_SHOW_DIGITAL_DOWNLOAD = 162;

    // Media And Entertainment Video Game
    MEDIA_AND_ENTERTAINMENT_VIDEO_GAME = 163;

    // Media And Entertainment Video Game Dlc
    MEDIA_AND_ENTERTAINMENT_VIDEO_GAME_DLC = 164;

    // Media And Entertainment Web Series
    MEDIA_AND_ENTERTAINMENT_WEB_SERIES = 165;

    // Offer
    OFFER = 166;

    // Pharma Non Medical Condition Otc Drug
    PHARMA_NON_MEDICAL_CONDITION_OTC_DRUG = 167;

    // Politics Candidate
    POLITICS_CANDIDATE = 168;

    // Politics Get Out The Vote November Elections
    POLITICS_GET_OUT_THE_VOTE_NOVEMBER_ELECTIONS = 169;

    // Politics Get Out The Vote Primary Elections
    POLITICS_GET_OUT_THE_VOTE_PRIMARY_ELECTIONS = 170;

    // Politics Issue
    POLITICS_ISSUE = 171;

    // Politics Unfavorable Candidate
    POLITICS_UNFAVORABLE_CANDIDATE = 172;

    // Retail Apparel
    RETAIL_APPAREL = 173;

    // Retail Brick And Mortar
    RETAIL_BRICK_AND_MORTAR = 174;

    // Retail Furniture Brand
    RETAIL_FURNITURE_BRAND = 175;

    // Retail Furniture Product
    RETAIL_FURNITURE_PRODUCT = 176;

    // Retail Gifts Brand
    RETAIL_GIFTS_BRAND = 177;

    // Retail Gifts Product
    RETAIL_GIFTS_PRODUCT = 178;

    // Retail Home Goods
    RETAIL_HOME_GOODS = 179;

    // Retail Jewelry Brand
    RETAIL_JEWELRY_BRAND = 180;

    // Retail Online Retailers
    RETAIL_ONLINE_RETAILERS = 181;

    // Retail Shoe Brand
    RETAIL_SHOE_BRAND = 182;

    // Retail Store
    RETAIL_STORE = 183;

    // Retail Toy Shop
    RETAIL_TOY_SHOP = 184;

    // Technology Artificial Intelligence Brand
    TECHNOLOGY_ARTIFICIAL_INTELLIGENCE_BRAND = 185;

    // Technology Artificial Intelligence Product
    TECHNOLOGY_ARTIFICIAL_INTELLIGENCE_PRODUCT = 186;

    // Technology Brand
    TECHNOLOGY_BRAND = 187;

    // Technology Feature
    TECHNOLOGY_FEATURE = 188;

    // Technology Product
    TECHNOLOGY_PRODUCT = 189;

    // Technology Camera Brand
    TECHNOLOGY_CAMERA_BRAND = 190;

    // Technology Camera Product
    TECHNOLOGY_CAMERA_PRODUCT = 191;

    // Technology Control Plans
    TECHNOLOGY_CONTROL_PLANS = 192;

    // Technology Gaming Brand
    TECHNOLOGY_GAMING_BRAND = 193;

    // Technology Home Appliance Brand
    TECHNOLOGY_HOME_APPLIANCE_BRAND = 194;

    // Technology Home Appliance Product
    TECHNOLOGY_HOME_APPLIANCE_PRODUCT = 195;

    // Technology Laptop Brand
    TECHNOLOGY_LAPTOP_BRAND = 196;

    // Technology Laptop Product
    TECHNOLOGY_LAPTOP_PRODUCT = 197;

    // Technology Mobile Phone Plans
    TECHNOLOGY_MOBILE_PHONE_PLANS = 198;

    // Technology Online Safety Brand
    TECHNOLOGY_ONLINE_SAFETY_BRAND = 199;

    // Technology Online Safety Product
    TECHNOLOGY_ONLINE_SAFETY_PRODUCT = 200;

    // Technology Operating System
    TECHNOLOGY_OPERATING_SYSTEM = 201;

    // Technology Postpaid Telco Plan
    TECHNOLOGY_POSTPAID_TELCO_PLAN = 202;

    // Technology Prepaid Telco Plan
    TECHNOLOGY_PREPAID_TELCO_PLAN = 203;

    // Technology Printer Brand
    TECHNOLOGY_PRINTER_BRAND = 204;

    // Technology Search Engine
    TECHNOLOGY_SEARCH_ENGINE = 205;

    // Technology Small Home Appliance Brand
    TECHNOLOGY_SMALL_HOME_APPLIANCE_BRAND = 206;

    // Technology Small Home Appliance Product
    TECHNOLOGY_SMALL_HOME_APPLIANCE_PRODUCT = 207;

    // Technology Smart Home Device
    TECHNOLOGY_SMART_HOME_DEVICE = 208;

    // Technology Mobile Phone Brand
    TECHNOLOGY_SMARTPHONE_BRAND = 209;

    // Technology Mobile Phone Product
    TECHNOLOGY_SMARTPHONE_PRODUCT = 210;

    // Technology Social Media
    TECHNOLOGY_SOCIAL_MEDIA = 211;

    // Technology Tablet Brand
    TECHNOLOGY_TABLET_BRAND = 212;

    // Technology Tablet Product
    TECHNOLOGY_TABLET_PRODUCT = 213;

    // Technology Telecom Fiber Optic Internet
    TECHNOLOGY_TELECOM_FIBER_OPTIC_INTERNET = 214;

    // Technology Telecom Service Pack
    TECHNOLOGY_TELECOM_SERVICE_PACK = 215;

    // Technology Telco Network
    TECHNOLOGY_TELCO_NETWORK = 216;

    // Technology Tv Brand
    TECHNOLOGY_TV_BRAND = 217;

    // Technology Tv Product
    TECHNOLOGY_TV_PRODUCT = 218;

    // Technology Video On Demand
    TECHNOLOGY_VIDEO_ON_DEMAND = 219;

    // Technology Wearables Brand
    TECHNOLOGY_WEARABLES_BRAND = 220;

    // Technology Website
    TECHNOLOGY_WEBSITE = 221;

    // Travel Accommodations
    TRAVEL_ACCOMMODATIONS = 222;

    // Travel Airline
    TRAVEL_AIRLINE = 223;

    // Travel Booking Service
    TRAVEL_BOOKING_SERVICE = 224;

    // Travel Cruises
    TRAVEL_CRUISES = 225;

    // Travel Destination
    TRAVEL_DESTINATION = 226;

    // Travel Hotel
    TRAVEL_HOTEL = 227;

    // Travel Option
    TRAVEL_OPTION = 228;

    // Travel Vacation Rental Service
    TRAVEL_VACATION_RENTAL_SERVICE = 229;
  }
}
