// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.googleads.v25.enums;

option csharp_namespace = "Google.Ads.GoogleAds.V25.Enums";
option go_package = "google.golang.org/genproto/googleapis/ads/googleads/v25/enums;enums";
option java_multiple_files = true;
option java_outer_classname = "SurveyIntendedActionProto";
option java_package = "com.google.ads.googleads.v25.enums";
option objc_class_prefix = "GAA";
option php_namespace = "Google\\Ads\\GoogleAds\\V25\\Enums";
option ruby_package = "Google::Ads::GoogleAds::V25::Enums";

// Container for enum
message SurveyIntendedActionEnum {
  // The enum
  enum SurveyIntendedAction {
    // Not specified.
    UNSPECIFIED = 0;

    // Unknown value.
    UNKNOWN = 1;

    // Apply For
    APPLY_FOR = 2;

    // Apply To Work For
    APPLY_TO_WORK_FOR = 3;

    // Attend
    ATTEND = 4;

    // Book
    BOOK = 5;

    // Book With
    BOOK_WITH = 6;

    // Buy
    BUY = 7;

    // Buy Content From
    BUY_CONTENT_FROM = 8;

    // Buy Tickets For
    BUY_TICKETS_FOR = 9;

    // Care About
    CARE_ABOUT = 10;

    // Choose
    CHOOSE = 11;

    // Donate To
    DONATE_TO = 12;

    // Download
    DOWNLOAD = 13;

    // Download From
    DOWNLOAD_FROM = 14;

    // Eat
    EAT = 15;

    // Eat At
    EAT_AT = 16;

    // Have Unfavorable Opinion Of
    HAVE_UNFAVORABLE_OPINION_OF = 17;

    // Join
    JOIN = 18;

    // Learn
    LEARN = 19;

    // Listen To
    LISTEN_TO = 20;

    // None
    NONE = 21;

    // Order From
    ORDER_FROM = 22;

    // Participate In
    PARTICIPATE_IN = 23;

    // Play
    PLAY = 24;

    // Play At
    PLAY_AT = 25;

    // Play On
    PLAY_ON = 26;

    // Rent
    RENT = 27;

    // See
    SEE = 28;

    // See In Theaters
    SEE_IN_THEATERS = 29;

    // Shop
    SHOP = 30;

    // Sign Up For
    SIGN_UP_FOR = 31;

    // Subscribe To
    SUBSCRIBE_TO = 32;

    // Take Action On
    TAKE_ACTION_ON = 33;

    // Use
    USE = 34;

    // Visit
    VISIT = 35;

    // Vote For
    VOTE_FOR = 36;

    // Watch
    WATCH = 37;

    // Watch In Theaters
    WATCH_IN_THEATERS = 38;
  }
}
