// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.googleads.v25.enums;

option csharp_namespace = "Google.Ads.GoogleAds.V25.Enums";
option go_package = "google.golang.org/genproto/googleapis/ads/googleads/v25/enums;enums";
option java_multiple_files = true;
option java_outer_classname = "VideoCrawlSourcePlatformProto";
option java_package = "com.google.ads.googleads.v25.enums";
option objc_class_prefix = "GAA";
option php_namespace = "Google\\Ads\\GoogleAds\\V25\\Enums";
option ruby_package = "Google::Ads::GoogleAds::V25::Enums";

// Proto file describing video crawl source platform

// Container for enum describing the source platform of the crawled video.
message VideoCrawlSourcePlatformEnum {
  // The source platform of the crawled video.
  enum VideoCrawlSourcePlatform {
    // Not specified.
    UNSPECIFIED = 0;

    // Used as a return value only. Represents value unknown in this version.
    UNKNOWN = 1;

    // Landing page: Videos on advertiser's landing page.
    LANDING_PAGE = 2;

    // Organic Social Video: Videos found from social URLs linked in advertiser
    // landing page (Facebook, Instagram, X, LinkedIn, TikTok).
    SOCIAL = 3;

    // YouTube Channel Organic Videos: Videos from the advertiser's channel.
    YOUTUBE = 4;
  }
}
