// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "AdReviewCenterAdEnumsProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Wrapper message for
// [AdReviewCenterAdStatus][google.ads.admanager.v1.AdReviewCenterAdStatusEnum.AdReviewCenterAdStatus]
message AdReviewCenterAdStatusEnum {
  // Specifies the status of an AdReviewCenterAd.
  enum AdReviewCenterAdStatus {
    // Not specified value
    AD_REVIEW_CENTER_AD_STATUS_UNSPECIFIED = 0;

    // This ad has been explicitly allowed to serve.
    ALLOWED = 1;

    // This ad has been explicitly blocked from serving.
    BLOCKED = 2;

    // This ad is allowed to serve by default and has not been reviewed.
    UNREVIEWED = 3;
  }
}

// Wrapper message for
// [ManualAdReviewCenterAdStatus][google.ads.admanager.v1.ManualAdReviewCenterAdStatusEnum.ManualAdReviewCenterAdStatus]
message ManualAdReviewCenterAdStatusEnum {
  // Specifies the manual review status of a AdReviewCenterAd.
  enum ManualAdReviewCenterAdStatus {
    // Not specified value.
    MANUAL_AD_REVIEW_CENTER_AD_STATUS_UNSPECIFIED = 0;

    // This ad has been explicitly allowed to serve.
    ALLOWED = 1;

    // This ad has been explicitly blocked from serving.
    BLOCKED = 2;

    // This ad is implicitly blocked and has been reviewed.
    ARCHIVED = 3;

    // This ad is implicitly blocked and has not been reviewed.
    PENDING = 4;

    // This ad is allowed to serve by default and has not been reviewed.
    SERVING = 5;
  }
}

// Wrapper message for
// [ArcCreativeFormat][google.ads.admanager.v1.ArcCreativeFormatEnum.ArcCreativeFormat]
//
// Message representing the ad review center creative formats which is about how
// the creative is rendered for the end user.
message ArcCreativeFormatEnum {
  // Specifies the status of an ArcCreativeFormat.
  //
  // New values may be added in the future.
  enum ArcCreativeFormat {
    // Not specified value
    ARC_CREATIVE_FORMAT_UNSPECIFIED = 0;

    // Text based creatives.
    TEXT = 1;

    // Image creatives.
    IMAGE = 2;

    // Video creatives.
    VIDEO = 3;

    // Audio creatives.
    AUDIO = 4;

    // Creatives leading to mobile app stores.
    APP_INSTALLS = 5;

    // Creatives leading to rich media.
    RICH_MEDIA = 6;
  }
}
