// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

import "google/ads/admanager/v1/audience_segment_messages.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "AudienceSegmentServiceProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Provides methods for handling `AudienceSegment` objects.
service AudienceSegmentService {
  option (google.api.default_host) = "admanager.googleapis.com";
  option (google.api.oauth_scopes) =
      "https://www.googleapis.com/auth/admanager,"
      "https://www.googleapis.com/auth/admanager.readonly";

  // Retrieves an `AudienceSegment` object.
  rpc GetAudienceSegment(GetAudienceSegmentRequest) returns (AudienceSegment) {
    option (google.api.http) = {
      get: "/v1/{name=networks/*/audienceSegments/*}"
    };
    option (google.api.method_signature) = "name";
  }

  // Lists `AudienceSegment` objects.
  rpc ListAudienceSegments(ListAudienceSegmentsRequest)
      returns (ListAudienceSegmentsResponse) {
    option (google.api.http) = {
      get: "/v1/{parent=networks/*}/audienceSegments"
    };
    option (google.api.method_signature) = "parent";
  }

  // Activates `AudienceSegment` objects.
  rpc BatchActivateAudienceSegments(BatchActivateAudienceSegmentsRequest)
      returns (BatchActivateAudienceSegmentsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/audienceSegments:batchActivate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Deactivates `AudienceSegment` objects.
  rpc BatchDeactivateAudienceSegments(BatchDeactivateAudienceSegmentsRequest)
      returns (BatchDeactivateAudienceSegmentsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/audienceSegments:batchDeactivate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Approves `AudienceSegment` objects.
  rpc BatchApproveAudienceSegments(BatchApproveAudienceSegmentsRequest)
      returns (BatchApproveAudienceSegmentsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/audienceSegments:batchApprove"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Rejects `AudienceSegment` objects.
  rpc BatchRejectAudienceSegments(BatchRejectAudienceSegmentsRequest)
      returns (BatchRejectAudienceSegmentsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/audienceSegments:batchReject"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Populates `AudienceSegment` objects.
  rpc BatchPopulateAudienceSegments(BatchPopulateAudienceSegmentsRequest)
      returns (BatchPopulateAudienceSegmentsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/audienceSegments:batchPopulate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }
}

// Request object for `GetAudienceSegment` method.
message GetAudienceSegmentRequest {
  // Required. The resource name of the AudienceSegment.
  // Format: `networks/{network_code}/audienceSegments/{audience_segment_id}`
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/AudienceSegment"
    }
  ];
}

// Request object for `ListAudienceSegments` method.
message ListAudienceSegmentsRequest {
  // Required. The parent publisher network associated with these audience
  // segments. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Optional. The maximum number of `AudienceSegments` to return. The service
  // may return fewer than this value. If unspecified, at most 50
  // `AudienceSegments` will be returned. The maximum value is 1000; values
  // greater than 1000 will be coerced to 1000.
  int32 page_size = 2 [(google.api.field_behavior) = OPTIONAL];

  // Optional. A page token, received from a previous `ListAudienceSegments`
  // call. Provide this to retrieve the subsequent page.
  //
  // When paginating, all other parameters provided to `ListAudienceSegments`
  // must match the call that provided the page token.
  string page_token = 3 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to filter the response.
  //  See syntax details at
  //  https://developers.google.com/ad-manager/api/beta/filters
  //
  // **Filterable fields:**
  //
  // * `adIdSize`
  // * `categoryIds`
  // * `dataProviderDisplayName`
  // * `displayName`
  // * `idfaSize`
  // * `mobileWebSize`
  // * `ppidSize`
  // * `segmentType`
  // * `sharedId`
  // * `size`
  // * `status`
  // * `thirdPartyAudienceSegment.approvalStatus`
  // * `thirdPartyAudienceSegment.cost`
  // * `thirdPartyAudienceSegment.endTime`
  // * `thirdPartyAudienceSegment.startTime`
  string filter = 4 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to specify sorting order.
  // See syntax details at
  // https://developers.google.com/ad-manager/api/beta/filters#order
  string order_by = 5 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Number of individual resources to skip while paginating.
  int32 skip = 6 [(google.api.field_behavior) = OPTIONAL];
}

// Response object for `ListAudienceSegmentsRequest` containing matching
// `AudienceSegment` objects.
message ListAudienceSegmentsResponse {
  // The `AudienceSegment` objects from the specified network.
  repeated AudienceSegment audience_segments = 1;

  // A token, which can be sent as `page_token` to retrieve the next page.
  // If this field is omitted, there are no subsequent pages.
  string next_page_token = 2;

  // Total number of `AudienceSegment` objects.
  // If a filter was included in the request, this reflects the total number
  // after the filtering is applied.
  //
  // `total_size` won't be calculated in the response unless it has been
  // included in a response field mask. The response field mask can be provided
  // to the method by using the URL parameter `$fields` or `fields`, or by using
  // the HTTP/gRPC header `X-Goog-FieldMask`.
  //
  // For more information, see
  // https://developers.google.com/ad-manager/api/beta/field-masks
  int32 total_size = 3;
}

// Request message for `BatchActivateAudienceSegments` method.
message BatchActivateAudienceSegmentsRequest {
  // Required. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. Resource names for the AudienceSegments.
  // Format: `networks/{network_code}/audienceSegments/{audience_segment_id}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/AudienceSegment"
    }
  ];
}

// Response message for `BatchActivateAudienceSegments` method.
message BatchActivateAudienceSegmentsResponse {
  // Number of audience segments activated.
  int64 change_count = 1;
}

// Request message for `BatchDeactivateAudienceSegments` method.
message BatchDeactivateAudienceSegmentsRequest {
  // Required. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. Resource names for the AudienceSegments.
  // Format: `networks/{network_code}/audienceSegments/{audience_segment_id}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/AudienceSegment"
    }
  ];
}

// Response message for `BatchDeactivateAudienceSegments` method.
message BatchDeactivateAudienceSegmentsResponse {
  // Number of audience segments deactivated.
  int64 change_count = 1;
}

// Request message for `BatchApproveAudienceSegments` method.
message BatchApproveAudienceSegmentsRequest {
  // Required. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. Resource names for the AudienceSegments.
  // Format: `networks/{network_code}/audienceSegments/{audience_segment_id}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/AudienceSegment"
    }
  ];
}

// Response message for `BatchApproveAudienceSegments` method.
message BatchApproveAudienceSegmentsResponse {
  // Number of audience segments approved.
  int64 change_count = 1;
}

// Request message for `BatchRejectAudienceSegments` method.
message BatchRejectAudienceSegmentsRequest {
  // Required. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. Resource names for the AudienceSegments.
  // Format: `networks/{network_code}/audienceSegments/{audience_segment_id}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/AudienceSegment"
    }
  ];
}

// Response message for `BatchRejectAudienceSegments` method.
message BatchRejectAudienceSegmentsResponse {
  // Number of audience segments rejected.
  int64 change_count = 1;
}

// Request message for `BatchPopulateAudienceSegments` method.
message BatchPopulateAudienceSegmentsRequest {
  // Required. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. Resource names for the AudienceSegments.
  // Format: `networks/{network_code}/audienceSegments/{audience_segment_id}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/AudienceSegment"
    }
  ];
}

// Response message for `BatchPopulateAudienceSegments` method.
message BatchPopulateAudienceSegmentsResponse {
  // Number of audience segments populated.
  int64 change_count = 1;
}
