// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "ConversionEventEnumProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Wrapper message for
// [ConversionEvent][google.ads.admanager.v1.ConversionEventEnum.ConversionEvent]
message ConversionEventEnum {
  // All possible tracking event types. Not all events are supported by every
  // kind of creative.
  enum ConversionEvent {
    // Default value. This value is unused.
    CONVERSION_EVENT_UNSPECIFIED = 0;

    // Corresponds to the `acceptInvitation` tracking event.
    ACCEPT_INVITATION = 1;

    // Corresponds to the `Linear.VideoClicks.ClickTracking` node.
    CLICK_TRACKING = 2;

    // Corresponds to the `close` tracking event.
    CLOSE = 3;

    // Corresponds to the `collapse` tracking event.
    COLLAPSE = 4;

    // Corresponds to the `complete` tracking event.
    COMPLETE = 5;

    // Corresponds to the `creativeView` tracking event.
    CREATIVE_VIEW = 6;

    // Corresponds to the `Linear.VideoClicks.CustomClick` node.
    CUSTOM_CLICK = 7;

    // An event that is fired after 30 seconds of viewing the video
    // or when the video finished (if the video duration is less than 30
    // seconds). This event does not correspond to any VAST element and is
    // implemented using an extension.
    ENGAGED_VIEW = 8;

    // Corresponds to the `expand` tracking event.
    EXPAND = 9;

    // Corresponds to the `firstQuartile` tracking event.
    FIRST_QUARTILE = 10;

    // Corresponds to the `fullscreen` tracking event.
    FULLSCREEN = 11;

    // Corresponds to the `fullyViewableAudibleHalfDurationImpression` tracking
    // event.
    FULLY_VIEWABLE_AUDIBLE_HALF_DURATION_IMPRESSION = 12;

    // Corresponds to the `measurableImpression` tracking event.
    MEASURABLE_IMPRESSION = 13;

    // Corresponds to the `midpoint` tracking event.
    MIDPOINT = 14;

    // Corresponds to the `mute` tracking event.
    MUTE = 15;

    // Corresponds to the `pause` tracking event.
    PAUSE = 16;

    // Corresponds to the `resume` tracking event.
    RESUME = 17;

    // Corresponds to the `rewind` tracking event.
    REWIND = 18;

    // An event that is fired when a video was skipped.
    // This event does not correspond to any VAST element and is implemented
    // using an extension.
    SKIPPED = 19;

    // An event that is fired when a video skip button is shown,
    // usually after 5 seconds of viewing the video.
    // This event does not correspond to any VAST element and is implemented
    // using an extension.
    SKIP_SHOWN = 20;

    // Corresponds to the `start` tracking event.
    START = 21;

    // Corresponds to the `InLine.Survey` node.
    SURVEY = 22;

    // Corresponds to the `thirdQuartile` tracking event.
    THIRD_QUARTILE = 23;

    // Corresponds to the `unmute` tracking event.
    UNMUTE = 24;

    // Corresponds to the `abandon` tracking event.
    VIDEO_ABANDON = 25;

    // Corresponds to the `viewableImpression` tracking event.
    VIEWABLE_IMPRESSION = 26;
  }
}
