// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "CreativeEnumsProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Wrapper message for
// [CreativeLockedOrientation][google.ads.admanager.v1.CreativeLockedOrientationEnum.CreativeLockedOrientation].
message CreativeLockedOrientationEnum {
  // Describes the orientation that a creative should be served with.
  enum CreativeLockedOrientation {
    // Default value. This value is unused.
    CREATIVE_LOCKED_ORIENTATION_UNSPECIFIED = 0;

    // Landscape orientation.
    LANDSCAPE = 1;

    // Portrait orientation.
    PORTRAIT = 2;

    // Free orientation.
    FREE = 3;
  }
}

// Wrapper message for
// [CreativeDestinationUrlType][google.ads.admanager.v1.CreativeDestinationUrlTypeEnum.CreativeDestinationUrlType]
message CreativeDestinationUrlTypeEnum {
  // The valid actions that a destination URL may perform if the user clicks on
  // the ad.
  enum CreativeDestinationUrlType {
    // Default value. This value is unused.
    CREATIVE_DESTINATION_URL_TYPE_UNSPECIFIED = 0;

    // Start an application.
    CLICK_TO_APP = 1;

    // Make a phone call.
    CLICK_TO_CALL = 2;

    // Navigate to a web page. (a.k.a. "Click-through URL").
    CLICK_TO_WEB = 3;

    // Destination URL not present. Useful for video creatives where a landing
    // page or a product isn't necessarily applicable.
    NONE = 4;
  }
}

// Wrapper message for
// [CreativeSslOverride][google.ads.admanager.v1.CreativeSslOverrideEnum.CreativeSslOverride]
message CreativeSslOverrideEnum {
  // Enum to store the creative SSL compatibility manual override.
  // Its three states are similar to that of SslScanResult.
  enum CreativeSslOverride {
    // Default value. This value is unused.
    CREATIVE_SSL_OVERRIDE_UNSPECIFIED = 0;

    // The creative is manually overridden to be SSL-incompatible.
    NOT_SSL_COMPATIBLE = 1;

    // The creative's SSL compatibility is determined by the scan result.
    NO_OVERRIDE = 2;

    // The creative is manually overridden to be SSL-compatible.
    SSL_COMPATIBLE = 3;
  }
}

// Wrapper message for
// [CreativeSslScanResult][google.ads.admanager.v1.CreativeSslScanResultEnum.CreativeSslScanResult]
message CreativeSslScanResultEnum {
  // Enum to store the creative SSL compatibility scan result.
  enum CreativeSslScanResult {
    // Default value. This value is unused.
    CREATIVE_SSL_SCAN_RESULT_UNSPECIFIED = 0;

    // The creative was scanned and found to be SSL-incompatible.
    SCANNED_NON_SSL = 1;

    // The creative was scanned and found to be SSL-compatible.
    SCANNED_SSL = 2;

    // The creative has not been scanned for SSL compatibility.
    UNSCANNED = 3;
  }
}

// Wrapper message for
// [VastAdIdType][google.ads.admanager.v1.VastAdIdTypeEnum.VastAdIdType]
message VastAdIdTypeEnum {
  // The registry that an ad ID belongs to.
  enum VastAdIdType {
    // Default value. This value is unused.
    VAST_AD_ID_TYPE_UNSPECIFIED = 0;

    // Ad ID.
    AD_ID = 1;

    // The ad ID is registered with ARPP Pub-ID.
    ARPP = 2;

    // The ad ID is registered with clearcast.co.uk.
    CLEARCAST = 3;

    // The ad ID is registered with Auditel Spot ID.
    CUSV = 4;

    // None.
    NONE = 5;
  }
}
