// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

import "google/ads/admanager/v1/creative_wrapper_messages.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/field_mask.proto";

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "CreativeWrapperServiceProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Provides methods for handling `CreativeWrapper` objects.
service CreativeWrapperService {
  option (google.api.default_host) = "admanager.googleapis.com";
  option (google.api.oauth_scopes) =
      "https://www.googleapis.com/auth/admanager,"
      "https://www.googleapis.com/auth/admanager.readonly";

  // Retrieves a `CreativeWrapper` object.
  rpc GetCreativeWrapper(GetCreativeWrapperRequest) returns (CreativeWrapper) {
    option (google.api.http) = {
      get: "/v1/{name=networks/*/creativeWrappers/*}"
    };
    option (google.api.method_signature) = "name";
  }

  // Lists `CreativeWrapper` objects.
  rpc ListCreativeWrappers(ListCreativeWrappersRequest)
      returns (ListCreativeWrappersResponse) {
    option (google.api.http) = {
      get: "/v1/{parent=networks/*}/creativeWrappers"
    };
    option (google.api.method_signature) = "parent";
  }

  // Creates a `CreativeWrapper` object.
  rpc CreateCreativeWrapper(CreateCreativeWrapperRequest)
      returns (CreativeWrapper) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/creativeWrappers"
      body: "creative_wrapper"
    };
    option (google.api.method_signature) = "parent,creative_wrapper";
  }

  // Creates `CreativeWrapper` objects.
  rpc BatchCreateCreativeWrappers(BatchCreateCreativeWrappersRequest)
      returns (BatchCreateCreativeWrappersResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/creativeWrappers:batchCreate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,requests";
  }

  // Updates a `CreativeWrapper` object.
  rpc UpdateCreativeWrapper(UpdateCreativeWrapperRequest)
      returns (CreativeWrapper) {
    option (google.api.http) = {
      patch: "/v1/{creative_wrapper.name=networks/*/creativeWrappers/*}"
      body: "creative_wrapper"
    };
    option (google.api.method_signature) = "creative_wrapper,update_mask";
  }

  // Batch updates `CreativeWrapper` objects.
  rpc BatchUpdateCreativeWrappers(BatchUpdateCreativeWrappersRequest)
      returns (BatchUpdateCreativeWrappersResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/creativeWrappers:batchUpdate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,requests";
  }

  // Batch activates `CreativeWrapper` objects.
  rpc BatchActivateCreativeWrappers(BatchActivateCreativeWrappersRequest)
      returns (BatchActivateCreativeWrappersResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/creativeWrappers:batchActivate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Deactivates a list of `CreativeWrapper` objects.
  rpc BatchDeactivateCreativeWrappers(BatchDeactivateCreativeWrappersRequest)
      returns (BatchDeactivateCreativeWrappersResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/creativeWrappers:batchDeactivate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }
}

// Request object for `GetCreativeWrapper` method.
message GetCreativeWrapperRequest {
  // Required. The resource name of the CreativeWrapper.
  // Format: `networks/{network_code}/creativeWrappers/{creative_wrapper_id}`
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/CreativeWrapper"
    }
  ];
}

// Request object for `ListCreativeWrappers` method.
message ListCreativeWrappersRequest {
  // Required. The parent, which owns this collection of CreativeWrappers.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Optional. The maximum number of `CreativeWrappers` to return. The service
  // may return fewer than this value. If unspecified, at most 50
  // `CreativeWrappers` will be returned. The maximum value is 1000; values
  // greater than 1000 will be coerced to 1000.
  int32 page_size = 2 [(google.api.field_behavior) = OPTIONAL];

  // Optional. A page token, received from a previous `ListCreativeWrappers`
  // call. Provide this to retrieve the subsequent page.
  //
  // When paginating, all other parameters provided to `ListCreativeWrappers`
  // must match the call that provided the page token.
  string page_token = 3 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to filter the response.
  //  See syntax details at
  //  https://developers.google.com/ad-manager/api/beta/filters
  //
  // **Filterable fields:**
  //
  // * `creativeWrapperType`
  // * `label`
  // * `name`
  // * `ordering`
  // * `status`
  string filter = 4 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to specify sorting order.
  // See syntax details at
  // https://developers.google.com/ad-manager/api/beta/filters#order
  string order_by = 5 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Number of individual resources to skip while paginating.
  int32 skip = 6 [(google.api.field_behavior) = OPTIONAL];
}

// Response object for `ListCreativeWrappersRequest` containing matching
// `CreativeWrapper` objects.
message ListCreativeWrappersResponse {
  // The `CreativeWrapper` objects from the specified network.
  repeated CreativeWrapper creative_wrappers = 1;

  // A token, which can be sent as `page_token` to retrieve the next page.
  // If this field is omitted, there are no subsequent pages.
  string next_page_token = 2;

  // Total number of `CreativeWrapper` objects.
  // If a filter was included in the request, this reflects the total number
  // after the filtering is applied.
  //
  // `total_size` won't be calculated in the response unless it has been
  // included in a response field mask. The response field mask can be provided
  // to the method by using the URL parameter `$fields` or `fields`, or by using
  // the HTTP/gRPC header `X-Goog-FieldMask`.
  //
  // For more information, see
  // https://developers.google.com/ad-manager/api/beta/field-masks
  int32 total_size = 3;
}

// Request object for `CreateCreativeWrapper` method.
message CreateCreativeWrapperRequest {
  // Required. The parent resource where this `CreativeWrapper` will be created.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The `CreativeWrapper` to create.
  CreativeWrapper creative_wrapper = 2 [(google.api.field_behavior) = REQUIRED];
}

// Request object for `BatchCreateCreativeWrappers` method.
message BatchCreateCreativeWrappersRequest {
  // Required. The parent resource where `CreativeWrappers` will be created.
  // Format: `networks/{network_code}`
  // The parent field in the CreateCreativeWrapperRequest must match this
  // field.
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The `CreativeWrapper` objects to create.
  // A maximum of 100 objects can be created in a batch.
  repeated CreateCreativeWrapperRequest requests = 2
      [(google.api.field_behavior) = REQUIRED];
}

// Response object for `BatchCreateCreativeWrappers` method.
message BatchCreateCreativeWrappersResponse {
  // The `CreativeWrapper` objects created.
  repeated CreativeWrapper creative_wrappers = 1;
}

// Request object for `UpdateCreativeWrapper` method.
message UpdateCreativeWrapperRequest {
  // Required. The `CreativeWrapper` to update.
  //
  // The `CreativeWrapper`'s `name` is used to identify the `CreativeWrapper` to
  // update.
  CreativeWrapper creative_wrapper = 1 [(google.api.field_behavior) = REQUIRED];

  // Optional. The list of fields to update.
  google.protobuf.FieldMask update_mask = 2
      [(google.api.field_behavior) = OPTIONAL];
}

// Request object for `BatchUpdateCreativeWrappers` method.
message BatchUpdateCreativeWrappersRequest {
  // Required. The parent resource where `CreativeWrappers` will be updated.
  // Format: `networks/{network_code}`
  // The parent field in the UpdateCreativeWrapperRequest must match this
  // field.
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The `CreativeWrapper` objects to update.
  // A maximum of 100 objects can be updated in a batch.
  repeated UpdateCreativeWrapperRequest requests = 2
      [(google.api.field_behavior) = REQUIRED];
}

// Response object for `BatchUpdateCreativeWrappers` method.
message BatchUpdateCreativeWrappersResponse {
  // The `CreativeWrapper` objects updated.
  repeated CreativeWrapper creative_wrappers = 1;
}

// Request message to activate `CreativeWrapper` objects.
message BatchActivateCreativeWrappersRequest {
  // Required. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The resource names of the `CreativeWrapper` objects to activate.
  // Format: `networks/{network_code}/creativeWrappers/{creative_wrapper_id}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/CreativeWrapper"
    }
  ];
}

// Response message for `BatchActivateCreativeWrappers` method.
message BatchActivateCreativeWrappersResponse {}

// Request message to deactivate `CreativeWrapper` objects.
message BatchDeactivateCreativeWrappersRequest {
  // Required. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The resource names of the `CreativeWrapper` objects to
  // deactivate. Format:
  // `networks/{network_code}/creativeWrappers/{creative_wrapper_id}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/CreativeWrapper"
    }
  ];
}

// Response object for `BatchDeactivateCreativeWrappers` method.
message BatchDeactivateCreativeWrappersResponse {}
