// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "CreativeThirdPartyDataDeclarationStatusEnumProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Wrapper message for
// [CreativeThirdPartyDataDeclarationStatus][google.ads.admanager.v1.CreativeThirdPartyDataDeclarationStatusEnum.CreativeThirdPartyDataDeclarationStatus]
message CreativeThirdPartyDataDeclarationStatusEnum {
  // The "status" of the ThirdPartyDataDeclaration associated with a given
  // creative.
  //
  // This is calculated by comparing the companies detected by automated
  // scanning/parsing, with the companies the publisher has declared in the
  // ThirdPartyDataDeclaration.
  enum CreativeThirdPartyDataDeclarationStatus {
    // Default value. This value is unused.
    CREATIVE_THIRD_PARTY_DATA_DECLARATION_STATUS_UNSPECIFIED = 0;

    // All companies detected in scanning exist in the associated
    // ThirdPartyDataDeclaration.
    //
    // This could be because there were no detected companies, or all the
    // detected companies exist in the associated declaration.
    COMPLETE = 1;

    // There are companies detected in scanning that do not exist in the
    // associated ThirdPartyDataDeclaration.
    //
    // This could be because there is no declaration, at either the creative
    // level or network level, or the declaration is missing companies.
    INCOMPLETE = 2;

    // This entity has not been recently scanned.
    //
    // This can happen either because there is no scanning data for this
    // creative, or the scanning data is stale (because the creative is not
    // associated with any active line items / eligible to serve).
    UNSCANNED = 3;
  }
}
