// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "DaiEncodingProfileEnumsProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Wrapper message for
// [ContainerType][google.ads.admanager.v1.ContainerTypeEnum.ContainerType]
message ContainerTypeEnum {
  // The container type of the DaiEncodingProfile.
  enum ContainerType {
    // Not specified value.
    CONTAINER_TYPE_UNSPECIFIED = 0;

    // Transport stream (TS) container.
    TS = 1;

    // Fragmented MPEG-4 (fMP4) output container.
    FMP4 = 2;

    // HTTP live streaming (HLS) packed audio container.
    HLS_AUDIO = 3;
  }
}

// Wrapper message for
// [DaiEncodingProfileStatus][google.ads.admanager.v1.DaiEncodingProfileStatusEnum.DaiEncodingProfileStatus]
message DaiEncodingProfileStatusEnum {
  // The status of the DaiEncodingProfile.
  enum DaiEncodingProfileStatus {
    // Not specified value.
    DAI_ENCODING_PROFILE_STATUS_UNSPECIFIED = 0;

    // Indicates the DaiEncodingProfile has been created and is eligible for
    // streaming.
    ACTIVE = 1;

    // Indicates the DaiEncodingProfile has been archived.
    ARCHIVED = 2;
  }
}

// Wrapper message for
// [DaiEncodingProfileVariantType][google.ads.admanager.v1.DaiEncodingProfileVariantTypeEnum.DaiEncodingProfileVariantType]
message DaiEncodingProfileVariantTypeEnum {
  // The variant type of the DaiEncodingProfile.
  enum DaiEncodingProfileVariantType {
    // Not specified value.
    DAI_ENCODING_PROFILE_VARIANT_TYPE_UNSPECIFIED = 0;

    // Media variant playlist type. Media playlists may: contain audio only
    // video only, or audio and video.
    MEDIA = 1;

    // iFrame variant playlist type. iFrame playlists may: contain video or
    // contain audio and video (i.e. video must be present).
    IFRAME = 2;

    // Subtitles variant playlist type.
    SUBTITLES = 3;
  }
}
