// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "DaiAuthenticationKeyEnumsProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Wrapper message for
// [DaiAuthenticationKeyStatus][google.ads.admanager.v1.DaiAuthenticationKeyStatusEnum.DaiAuthenticationKeyStatus]
message DaiAuthenticationKeyStatusEnum {
  // Statuses associated with DaiAuthenticationKey objects.
  enum DaiAuthenticationKeyStatus {
    // Default value. This value is unused.
    DAI_AUTHENTICATION_KEY_STATUS_UNSPECIFIED = 0;

    // Indicates that the API key is actively in use and that the IMA SDK API
    // should accept it as a valid key in requests.
    ACTIVE = 1;

    // Indicates that the API key is no longer is use and that the IMA SDK API
    // should not accept it as a valid key in requests.
    INACTIVE = 2;
  }
}

// Wrapper message for
// [DaiAuthenticationKeyType][google.ads.admanager.v1.DaiAuthenticationKeyTypeEnum.DaiAuthenticationKeyType]
message DaiAuthenticationKeyTypeEnum {
  // Key types associated with DaiAuthenticationKey objects.
  enum DaiAuthenticationKeyType {
    // Default value. This value is unused.
    DAI_AUTHENTICATION_KEY_TYPE_UNSPECIFIED = 0;

    // Indicates that the key is a standard API key and should be used with the
    // api-key SDK parameter when authenticating stream create requests.
    API = 1;

    // Indicates that the key is an HMAC key and should be used to generate a
    // signature for the stream create request with the auth-token SDK
    // parameter.
    HMAC = 2;
  }
}
