// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

import "google/ads/admanager/v1/dai_authentication_key_messages.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/field_mask.proto";

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "DaiAuthenticationKeyServiceProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Provides methods for handling `DaiAuthenticationKey` objects.
service DaiAuthenticationKeyService {
  option (google.api.default_host) = "admanager.googleapis.com";
  option (google.api.oauth_scopes) =
      "https://www.googleapis.com/auth/admanager,"
      "https://www.googleapis.com/auth/admanager.readonly";

  // Retrieves a `DaiAuthenticationKey` object.
  rpc GetDaiAuthenticationKey(GetDaiAuthenticationKeyRequest)
      returns (DaiAuthenticationKey) {
    option (google.api.http) = {
      get: "/v1/{name=networks/*/daiAuthenticationKeys/*}"
    };
    option (google.api.method_signature) = "name";
  }

  // Lists `DaiAuthenticationKey` objects.
  rpc ListDaiAuthenticationKeys(ListDaiAuthenticationKeysRequest)
      returns (ListDaiAuthenticationKeysResponse) {
    option (google.api.http) = {
      get: "/v1/{parent=networks/*}/daiAuthenticationKeys"
    };
    option (google.api.method_signature) = "parent";
  }

  // Creates a `DaiAuthenticationKey` object.
  rpc CreateDaiAuthenticationKey(CreateDaiAuthenticationKeyRequest)
      returns (DaiAuthenticationKey) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/daiAuthenticationKeys"
      body: "dai_authentication_key"
    };
    option (google.api.method_signature) = "parent,dai_authentication_key";
  }

  // Batch creates `DaiAuthenticationKey` objects.
  rpc BatchCreateDaiAuthenticationKeys(BatchCreateDaiAuthenticationKeysRequest)
      returns (BatchCreateDaiAuthenticationKeysResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/daiAuthenticationKeys:batchCreate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,requests";
  }

  // Updates a `DaiAuthenticationKey` object.
  rpc UpdateDaiAuthenticationKey(UpdateDaiAuthenticationKeyRequest)
      returns (DaiAuthenticationKey) {
    option (google.api.http) = {
      patch: "/v1/{dai_authentication_key.name=networks/*/daiAuthenticationKeys/*}"
      body: "dai_authentication_key"
    };
    option (google.api.method_signature) = "dai_authentication_key,update_mask";
  }

  // Batch updates `DaiAuthenticationKey` objects.
  rpc BatchUpdateDaiAuthenticationKeys(BatchUpdateDaiAuthenticationKeysRequest)
      returns (BatchUpdateDaiAuthenticationKeysResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/daiAuthenticationKeys:batchUpdate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,requests";
  }

  // Activates a list of `DaiAuthenticationKey` objects.
  rpc BatchActivateDaiAuthenticationKeys(
      BatchActivateDaiAuthenticationKeysRequest)
      returns (BatchActivateDaiAuthenticationKeysResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/daiAuthenticationKeys:batchActivate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Deactivates a list of `DaiAuthenticationKey` objects.
  rpc BatchDeactivateDaiAuthenticationKeys(
      BatchDeactivateDaiAuthenticationKeysRequest)
      returns (BatchDeactivateDaiAuthenticationKeysResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/daiAuthenticationKeys:batchDeactivate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }
}

// Request object for `GetDaiAuthenticationKey` method.
message GetDaiAuthenticationKeyRequest {
  // Required. The resource name of the `DaiAuthenticationKey`.
  // Format:
  // `networks/{network_code}/daiAuthenticationKeys/{dai_authentication_key_id}`
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/DaiAuthenticationKey"
    }
  ];
}

// Request object for `ListDaiAuthenticationKeys` method.
message ListDaiAuthenticationKeysRequest {
  // Required. The parent, which owns this collection of DaiAuthenticationKeys.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Optional. The maximum number of `DaiAuthenticationKeys` to return. The
  // service may return fewer than this value. If unspecified, at most 50
  // `DaiAuthenticationKeys` will be returned. The maximum value is 1000; values
  // greater than 1000 will be coerced to 1000.
  int32 page_size = 2 [(google.api.field_behavior) = OPTIONAL];

  // Optional. A page token, received from a previous
  // `ListDaiAuthenticationKeys` call. Provide this to retrieve the subsequent
  // page.
  //
  // When paginating, all other parameters provided to
  // `ListDaiAuthenticationKeys` must match the call that provided the page
  // token.
  string page_token = 3 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to filter the response.
  //  See syntax details at
  //  https://developers.google.com/ad-manager/api/beta/filters
  //
  // **Filterable fields:**
  //
  // * `displayName`
  // * `name`
  // * `status`
  string filter = 4 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to specify sorting order.
  // See syntax details at
  // https://developers.google.com/ad-manager/api/beta/filters#order
  string order_by = 5 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Number of individual resources to skip while paginating.
  int32 skip = 6 [(google.api.field_behavior) = OPTIONAL];
}

// Response object for `ListDaiAuthenticationKeysRequest` containing matching
// `DaiAuthenticationKey` objects.
message ListDaiAuthenticationKeysResponse {
  // The `DaiAuthenticationKey` objects from the specified network.
  repeated DaiAuthenticationKey dai_authentication_keys = 1;

  // A token, which can be sent as `page_token` to retrieve the next page.
  // If this field is omitted, there are no subsequent pages.
  string next_page_token = 2;

  // Total number of `DaiAuthenticationKey` objects.
  // If a filter was included in the request, this reflects the total number
  // after the filtering is applied.
  //
  // `total_size` won't be calculated in the response unless it has been
  // included in a response field mask. The response field mask can be provided
  // to the method by using the URL parameter `$fields` or `fields`, or by using
  // the HTTP/gRPC header `X-Goog-FieldMask`.
  //
  // For more information, see
  // https://developers.google.com/ad-manager/api/beta/field-masks
  int32 total_size = 3;
}

// Request object for `CreateDaiAuthenticationKey` method.
message CreateDaiAuthenticationKeyRequest {
  // Required. The parent resource where this `DaiAuthenticationKey` will be
  // created. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The `DaiAuthenticationKey` to create.
  DaiAuthenticationKey dai_authentication_key = 2
      [(google.api.field_behavior) = REQUIRED];
}

// Request object for `BatchCreateDaiAuthenticationKeys` method.
message BatchCreateDaiAuthenticationKeysRequest {
  // Required. The parent resource where `DaiAuthenticationKeys` will be
  // created. Format: `networks/{network_code}` The parent field in the
  // CreateDaiAuthenticationKeyRequest must match this field.
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The `DaiAuthenticationKey` objects to create.
  // A maximum of 100 objects can be created in a batch.
  repeated CreateDaiAuthenticationKeyRequest requests = 2
      [(google.api.field_behavior) = REQUIRED];
}

// Response object for `BatchCreateDaiAuthenticationKeys` method.
message BatchCreateDaiAuthenticationKeysResponse {
  // The `DaiAuthenticationKey` objects created.
  repeated DaiAuthenticationKey dai_authentication_keys = 1;
}

// Request object for `UpdateDaiAuthenticationKey` method.
message UpdateDaiAuthenticationKeyRequest {
  // Required. The `DaiAuthenticationKey` to update.
  //
  // The `DaiAuthenticationKey`'s `name` is used to identify the
  // `DaiAuthenticationKey` to update.
  DaiAuthenticationKey dai_authentication_key = 1
      [(google.api.field_behavior) = REQUIRED];

  // Optional. The list of fields to update.
  google.protobuf.FieldMask update_mask = 2
      [(google.api.field_behavior) = OPTIONAL];
}

// Request object for `BatchUpdateDaiAuthenticationKeys` method.
message BatchUpdateDaiAuthenticationKeysRequest {
  // Required. The parent resource where `DaiAuthenticationKeys` will be
  // updated. Format: `networks/{network_code}` The parent field in the
  // UpdateDaiAuthenticationKeyRequest must match this field.
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The `DaiAuthenticationKey` objects to update.
  // A maximum of 100 objects can be updated in a batch.
  repeated UpdateDaiAuthenticationKeyRequest requests = 2
      [(google.api.field_behavior) = REQUIRED];
}

// Response object for `BatchUpdateDaiAuthenticationKeys` method.
message BatchUpdateDaiAuthenticationKeysResponse {
  // The `DaiAuthenticationKey` objects updated.
  repeated DaiAuthenticationKey dai_authentication_keys = 1;
}

// Request object for `BatchPerformDaiAuthenticationKeyAction` method.
message BatchActivateDaiAuthenticationKeysRequest {
  // Required. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. Resource names for the DaiAuthenticationKey.
  // Format:
  // `networks/{network_code}/daiAuthenticationKeys/{dai_authentication_key}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/DaiAuthenticationKey"
    }
  ];
}

// Response object for `BatchActivateDaiAuthenticationKeys` method.
message BatchActivateDaiAuthenticationKeysResponse {}

// Request object for `BatchPerformDaiAuthenticationKeyAction` method.
message BatchDeactivateDaiAuthenticationKeysRequest {
  // Required. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. Resource names for the DaiAuthenticationKey.
  // Format:
  // `networks/{network_code}/daiAuthenticationKeys/{dai_authentication_key}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/DaiAuthenticationKey"
    }
  ];
}

// Response object for `BatchDeactivateDaiAuthenticationKeys` method.
message BatchDeactivateDaiAuthenticationKeysResponse {}
