// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

import "google/ads/admanager/v1/line_item_messages.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "LineItemServiceProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Provides methods for handling `LineItem` objects.
service LineItemService {
  option (google.api.default_host) = "admanager.googleapis.com";
  option (google.api.oauth_scopes) =
      "https://www.googleapis.com/auth/admanager,"
      "https://www.googleapis.com/auth/admanager.readonly";

  // Retrieves a `LineItem` object.
  rpc GetLineItem(GetLineItemRequest) returns (LineItem) {
    option (google.api.http) = {
      get: "/v1/{name=networks/*/lineItems/*}"
    };
    option (google.api.method_signature) = "name";
  }

  // Lists `LineItem` objects.
  rpc ListLineItems(ListLineItemsRequest) returns (ListLineItemsResponse) {
    option (google.api.http) = {
      get: "/v1/{parent=networks/*}/lineItems"
    };
    option (google.api.method_signature) = "parent";
  }

  // Creates a `LineItem` object.
  rpc CreateLineItem(CreateLineItemRequest) returns (LineItem) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/lineItems"
      body: "line_item"
    };
    option (google.api.method_signature) = "parent,line_item";
  }

  // Creates `LineItem` objects.
  rpc BatchCreateLineItems(BatchCreateLineItemsRequest)
      returns (BatchCreateLineItemsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/lineItems:batchCreate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,requests";
  }

  // Updates a `LineItem` object.
  rpc UpdateLineItem(UpdateLineItemRequest) returns (LineItem) {
    option (google.api.http) = {
      patch: "/v1/{line_item.name=networks/*/lineItems/*}"
      body: "line_item"
    };
    option (google.api.method_signature) = "line_item,update_mask";
  }

  // Batch updates `LineItem` objects.
  rpc BatchUpdateLineItems(BatchUpdateLineItemsRequest)
      returns (BatchUpdateLineItemsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/lineItems:batchUpdate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,requests";
  }

  // Batch activates `LineItem` objects.
  rpc BatchActivateLineItems(BatchActivateLineItemsRequest)
      returns (BatchActivateLineItemsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/lineItems:batchActivate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Batch pauses `LineItem` objects.
  rpc BatchPauseLineItems(BatchPauseLineItemsRequest)
      returns (BatchPauseLineItemsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/lineItems:batchPause"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Batch resumes `LineItem` objects.
  rpc BatchResumeLineItems(BatchResumeLineItemsRequest)
      returns (BatchResumeLineItemsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/lineItems:batchResume"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Batch resumes and overbooks `LineItem` objects.
  rpc BatchResumeAndOverbookLineItems(BatchResumeAndOverbookLineItemsRequest)
      returns (BatchResumeAndOverbookLineItemsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/lineItems:batchResumeAndOverbook"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Batch deletes `LineItem` objects.
  rpc BatchDeleteLineItems(BatchDeleteLineItemsRequest)
      returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/lineItems:batchDelete"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Batch reserves `LineItem` objects.
  rpc BatchReserveLineItems(BatchReserveLineItemsRequest)
      returns (BatchReserveLineItemsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/lineItems:batchReserve"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Batch reserves and overbooks `LineItem` objects.
  rpc BatchReserveAndOverbookLineItems(BatchReserveAndOverbookLineItemsRequest)
      returns (BatchReserveAndOverbookLineItemsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/lineItems:batchReserveAndOverbook"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Batch releases `LineItem` objects.
  rpc BatchReleaseLineItems(BatchReleaseLineItemsRequest)
      returns (BatchReleaseLineItemsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/lineItems:batchRelease"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Batch archives `LineItem` objects.
  rpc BatchArchiveLineItems(BatchArchiveLineItemsRequest)
      returns (BatchArchiveLineItemsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/lineItems:batchArchive"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Batch unarchives `LineItem` objects.
  rpc BatchUnarchiveLineItems(BatchUnarchiveLineItemsRequest)
      returns (BatchUnarchiveLineItemsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/lineItems:batchUnarchive"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }
}

// Request object for `GetLineItem` method.
message GetLineItemRequest {
  // Required. The resource name of the LineItem.
  // Format: `networks/{network_code}/lineItems/{line_item_id}`
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/LineItem"
    }
  ];
}

// Request object for `ListLineItems` method.
message ListLineItemsRequest {
  // Required. The parent, which owns this collection of LineItems.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Optional. The maximum number of `LineItems` to return. The service may
  // return fewer than this value. If unspecified, at most 50 `LineItems` will
  // be returned. The maximum value is 1000; values greater than 1000 will be
  // coerced to 1000.
  int32 page_size = 2 [(google.api.field_behavior) = OPTIONAL];

  // Optional. A page token, received from a previous `ListLineItems` call.
  // Provide this to retrieve the subsequent page.
  //
  // When paginating, all other parameters provided to `ListLineItems` must
  // match the call that provided the page token.
  string page_token = 3 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to filter the response.
  //  See syntax details at
  //  https://developers.google.com/ad-manager/api/beta/filters
  //
  // **Filterable fields:**
  //
  // * `archived`
  // * `contractedUnitsBought`
  // * `costType`
  // * `createTime`
  // * `creativePlaceholders.size.canonicalName`
  // * `dealInfo.externalDealId`
  // * `deliveryRateType`
  // * `displayName`
  // * `endTime`
  // * `environmentType`
  // * `externalLineItemId`
  // * `goal.units`
  // * `grpSettings.growbirdNielsenEnabled`
  // * `grpSettings.inTargetRatioEstimateMilliPercent`
  // * `lineItemType`
  // * `missingCreatives`
  // * `name`
  // * `notes`
  // * `order`
  // * `orderDisplayName`
  // * `priority`
  // * `roadblockingType`
  // * `startTime`
  // * `stats.clickThroughRate`
  // * `stats.clicksDelivered`
  // * `stats.impressionsDelivered`
  // * `stats.viewableImpressionsDelivered`
  // * `status`
  // * `targeting.inventoryTargeting.targetedAdUnits.adUnit`
  // * `targeting.inventoryTargeting.targetedPlacements`
  // * `targeting.mobileApplicationTargeting.firstPartyTargeting.targetedApplications`
  // * `updateSource`
  // * `updateTime`
  // * `webPropertyCode`
  string filter = 4 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to specify sorting order.
  // See syntax details at
  // https://developers.google.com/ad-manager/api/beta/filters#order
  string order_by = 5 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Number of individual resources to skip while paginating.
  int32 skip = 6 [(google.api.field_behavior) = OPTIONAL];
}

// Response object for `ListLineItemsRequest` containing matching `LineItem`
// objects.
message ListLineItemsResponse {
  // The `LineItem` objects from the specified network.
  repeated LineItem line_items = 1;

  // A token, which can be sent as `page_token` to retrieve the next page.
  // If this field is omitted, there are no subsequent pages.
  string next_page_token = 2;

  // Total number of `LineItem` objects.
  // If a filter was included in the request, this reflects the total number
  // after the filtering is applied.
  //
  // `total_size` won't be calculated in the response unless it has been
  // included in a response field mask. The response field mask can be provided
  // to the method by using the URL parameter `$fields` or `fields`, or by using
  // the HTTP/gRPC header `X-Goog-FieldMask`.
  //
  // For more information, see
  // https://developers.google.com/ad-manager/api/beta/field-masks
  int32 total_size = 3;
}

// Request object for `CreateLineItem` method.
message CreateLineItemRequest {
  // Required. The parent resource where this `LineItem` will be created.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The `LineItem` to create.
  LineItem line_item = 2 [(google.api.field_behavior) = REQUIRED];
}

// Request object for `BatchCreateLineItems` method.
message BatchCreateLineItemsRequest {
  // Required. The parent resource where `LineItems` will be created.
  // Format: `networks/{network_code}`
  // The parent field in the CreateLineItemRequest must match this
  // field.
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The `LineItem` objects to create.
  // A maximum of 100 objects can be created in a batch.
  repeated CreateLineItemRequest requests = 2
      [(google.api.field_behavior) = REQUIRED];
}

// Response object for `BatchCreateLineItems` method.
message BatchCreateLineItemsResponse {
  // The `LineItem` objects created.
  repeated LineItem line_items = 1;
}

// Request object for `UpdateLineItem` method.
message UpdateLineItemRequest {
  // Required. The `LineItem` to update.
  //
  // The `LineItem`'s `name` is used to identify the `LineItem` to update.
  LineItem line_item = 1 [(google.api.field_behavior) = REQUIRED];

  // Optional. The list of fields to update.
  google.protobuf.FieldMask update_mask = 2
      [(google.api.field_behavior) = OPTIONAL];
}

// Request object for `BatchUpdateLineItems` method.
message BatchUpdateLineItemsRequest {
  // Required. The parent resource where `LineItems` will be updated.
  // Format: `networks/{network_code}`
  // The parent segment of the `line_item.name` in each `UpdateLineItemRequest`
  // must match this field.
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The `LineItem` objects to update.
  // A maximum of 100 objects can be updated in a batch.
  repeated UpdateLineItemRequest requests = 2
      [(google.api.field_behavior) = REQUIRED];
}

// Response object for `BatchUpdateLineItems` method.
message BatchUpdateLineItemsResponse {
  // The `LineItem` objects updated.
  repeated LineItem line_items = 1;
}

// Request object for `BatchActivateLineItems` method.
message BatchActivateLineItemsRequest {
  // Required. The parent resource where `LineItems` will be updated.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The names of the `LineItem` objects to activate.
  // Format: `networks/{network_code}/lineItems/{line_item}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/LineItem"
    }
  ];
}

// Response object for `BatchActivateLineItems` method.
message BatchActivateLineItemsResponse {}

// Request object for `BatchPauseLineItems` method.
message BatchPauseLineItemsRequest {
  // Required. The parent resource where `LineItems` will be updated.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The names of the `LineItem` objects to pause.
  // Format: `networks/{network_code}/lineItems/{line_item}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/LineItem"
    }
  ];
}

// Response object for `BatchPauseLineItems` method.
message BatchPauseLineItemsResponse {}

// Request object for `BatchResumeLineItems` method.
message BatchResumeLineItemsRequest {
  // Required. The parent resource where `LineItems` will be updated.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The names of the `LineItem` objects to resume.
  // Format: `networks/{network_code}/lineItems/{line_item}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/LineItem"
    }
  ];
}

// Response object for `BatchResumeLineItems` method.
message BatchResumeLineItemsResponse {}

// Request object for `BatchResumeAndOverbookLineItems` method.
message BatchResumeAndOverbookLineItemsRequest {
  // Required. The parent resource where `LineItems` will be updated.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The names of the `LineItem` objects to resume and overbook.
  // Format: `networks/{network_code}/lineItems/{line_item}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/LineItem"
    }
  ];
}

// Response object for `BatchResumeAndOverbookLineItems` method.
message BatchResumeAndOverbookLineItemsResponse {}

// Request object for `BatchDeleteLineItems` method.
message BatchDeleteLineItemsRequest {
  // Required. The parent resource where `LineItems` will be updated.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The names of the `LineItem` objects to delete.
  // Format: `networks/{network_code}/lineItems/{line_item}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/LineItem"
    }
  ];
}

// Request object for `BatchReserveLineItems` method.
message BatchReserveLineItemsRequest {
  // Required. The parent resource where `LineItems` will be updated.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The names of the `LineItem` objects to reserve.
  // Format: `networks/{network_code}/lineItems/{line_item}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/LineItem"
    }
  ];
}

// Response object for `BatchReserveLineItems` method.
message BatchReserveLineItemsResponse {}

// Request object for `BatchReserveAndOverbookLineItems` method.
message BatchReserveAndOverbookLineItemsRequest {
  // Required. The parent resource where `LineItems` will be updated.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The names of the `LineItem` objects to reserve and overbook.
  // Format: `networks/{network_code}/lineItems/{line_item}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/LineItem"
    }
  ];
}

// Response object for `BatchReserveAndOverbookLineItems` method.
message BatchReserveAndOverbookLineItemsResponse {}

// Request object for `BatchReleaseLineItems` method.
message BatchReleaseLineItemsRequest {
  // Required. The parent resource where `LineItems` will be updated.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The names of the `LineItem` objects to release.
  // Format: `networks/{network_code}/lineItems/{line_item}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/LineItem"
    }
  ];
}

// Response object for `BatchReleaseLineItems` method.
message BatchReleaseLineItemsResponse {}

// Request object for `BatchArchiveLineItems` method.
message BatchArchiveLineItemsRequest {
  // Required. The parent resource where `LineItems` will be updated.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The names of the `LineItem` objects to archive.
  // Format: `networks/{network_code}/lineItems/{line_item}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/LineItem"
    }
  ];
}

// Response object for `BatchArchiveLineItems` method.
message BatchArchiveLineItemsResponse {}

// Request object for `BatchUnarchiveLineItems` method.
message BatchUnarchiveLineItemsRequest {
  // Required. The parent resource where `LineItems` will be unarchived.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The names of the `LineItem` objects to extract.
  // Format: `networks/{network_code}/lineItems/{line_item}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/LineItem"
    }
  ];
}

// Response object for `BatchUnarchiveLineItems` method.
message BatchUnarchiveLineItemsResponse {}
