// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

import "google/ads/admanager/v1/native_style_enums.proto";
import "google/ads/admanager/v1/size.proto";
import "google/ads/admanager/v1/targeting.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "NativeStyleMessagesProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Used to define the look and feel of native ads, for both web and apps. Native
// styles determine how native creatives look for a segment of inventory.
message NativeStyle {
  option (google.api.resource) = {
    type: "admanager.googleapis.com/NativeStyle"
    pattern: "networks/{network_code}/nativeStyles/{native_style}"
    plural: "nativeStyles"
    singular: "nativeStyle"
  };

  // Identifier. The resource name of the `NativeStyle`.
  // Format: `networks/{network_code}/nativeStyles/{native_style_id}`
  string name = 1 [(google.api.field_behavior) = IDENTIFIER];

  // Required. Immutable. The creative template this native style is associated
  // with. Format:
  // "networks/{network_code}/creativeTemplates/{creative_template}"
  optional string creative_template = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.field_behavior) = IMMUTABLE,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/CreativeTemplate"
    }
  ];

  // Required. The display name of the native style. This attribute has a
  // maximum length of 255 characters.
  optional string display_name = 3 [(google.api.field_behavior) = REQUIRED];

  // Optional. The HTML snippet of the native style with placeholders for the
  // associated variables.
  optional string html_snippet = 4 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The CSS snippet of the native style, with placeholders for the
  // associated variables.
  optional string css_snippet = 5 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The targeting criteria for this native style.
  Targeting targeting = 9 [(google.api.field_behavior) = OPTIONAL];

  // Output only. The status of the native style.
  optional NativeStyleStatusEnum.NativeStyleStatus status = 10
      [(google.api.field_behavior) = OUTPUT_ONLY];

  // Required. The size of the native style.
  Size size = 12 [(google.api.field_behavior) = REQUIRED];
}
