// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

import "google/ads/admanager/v1/native_style_messages.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/field_mask.proto";

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "NativeStyleServiceProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Provides methods for handling `NativeStyle` objects.
service NativeStyleService {
  option (google.api.default_host) = "admanager.googleapis.com";
  option (google.api.oauth_scopes) =
      "https://www.googleapis.com/auth/admanager,"
      "https://www.googleapis.com/auth/admanager.readonly";

  // Retrieves a `NativeStyle` object.
  rpc GetNativeStyle(GetNativeStyleRequest) returns (NativeStyle) {
    option (google.api.http) = {
      get: "/v1/{name=networks/*/nativeStyles/*}"
    };
    option (google.api.method_signature) = "name";
  }

  // Lists `NativeStyle` objects.
  rpc ListNativeStyles(ListNativeStylesRequest)
      returns (ListNativeStylesResponse) {
    option (google.api.http) = {
      get: "/v1/{parent=networks/*}/nativeStyles"
    };
    option (google.api.method_signature) = "parent";
  }

  // Creates `NativeStyle` objects.
  rpc BatchCreateNativeStyles(BatchCreateNativeStylesRequest)
      returns (BatchCreateNativeStylesResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/nativeStyles:batchCreate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,requests";
  }

  // Batch updates `NativeStyle` objects.
  rpc BatchUpdateNativeStyles(BatchUpdateNativeStylesRequest)
      returns (BatchUpdateNativeStylesResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/nativeStyles:batchUpdate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,requests";
  }

  // Beginning of non-CRUD
  // Activates a list of `NativeStyle` objects.
  rpc BatchActivateNativeStyles(BatchActivateNativeStylesRequest)
      returns (BatchActivateNativeStylesResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/nativeStyles:batchActivate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Deactivates a list of `NativeStyle` objects.
  rpc BatchDeactivateNativeStyles(BatchDeactivateNativeStylesRequest)
      returns (BatchDeactivateNativeStylesResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/nativeStyles:batchDeactivate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }

  // Archives a list of `NativeStyle` objects.
  rpc BatchArchiveNativeStyles(BatchArchiveNativeStylesRequest)
      returns (BatchArchiveNativeStylesResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/nativeStyles:batchArchive"
      body: "*"
    };
    option (google.api.method_signature) = "parent,names";
  }
}

// Request object for `GetNativeStyle` method.
message GetNativeStyleRequest {
  // Required. The resource name of the NativeStyle.
  // Format: `networks/{network_code}/nativeStyles/{native_style_id}`
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/NativeStyle"
    }
  ];
}

// Request object for `ListNativeStyles` method.
message ListNativeStylesRequest {
  // Required. The parent, which owns this collection of NativeStyles.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Optional. The maximum number of `NativeStyles` to return. The service may
  // return fewer than this value. If unspecified, at most 50 `NativeStyles`
  // will be returned. The maximum value is 1000; values greater than 1000 will
  // be coerced to 1000.
  int32 page_size = 2 [(google.api.field_behavior) = OPTIONAL];

  // Optional. A page token, received from a previous `ListNativeStyles` call.
  // Provide this to retrieve the subsequent page.
  //
  // When paginating, all other parameters provided to `ListNativeStyles` must
  // match the call that provided the page token.
  string page_token = 3 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to filter the response.
  //  See syntax details at
  //  https://developers.google.com/ad-manager/api/beta/filters
  //
  // **Filterable fields:**
  //
  // * `creativeTemplate`
  // * `displayName`
  // * `name`
  // * `size.canonicalName`
  // * `status`
  string filter = 4 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to specify sorting order.
  // See syntax details at
  // https://developers.google.com/ad-manager/api/beta/filters#order
  string order_by = 5 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Number of individual resources to skip while paginating.
  int32 skip = 6 [(google.api.field_behavior) = OPTIONAL];
}

// Response object for `ListNativeStylesRequest` containing matching
// `NativeStyle` objects.
message ListNativeStylesResponse {
  // The `NativeStyle` objects from the specified network.
  repeated NativeStyle native_styles = 1;

  // A token, which can be sent as `page_token` to retrieve the next page.
  // If this field is omitted, there are no subsequent pages.
  string next_page_token = 2;

  // Total number of `NativeStyle` objects.
  // If a filter was included in the request, this reflects the total number
  // after the filtering is applied.
  //
  // `total_size` won't be calculated in the response unless it has been
  // included in a response field mask. The response field mask can be provided
  // to the method by using the URL parameter `$fields` or `fields`, or by using
  // the HTTP/gRPC header `X-Goog-FieldMask`.
  //
  // For more information, see
  // https://developers.google.com/ad-manager/api/beta/field-masks
  int32 total_size = 3;
}

// Request object for `CreateNativeStyle` method.
message CreateNativeStyleRequest {
  // Required. The parent resource where this `NativeStyle` will be created.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The `NativeStyle` to create.
  NativeStyle native_style = 2 [(google.api.field_behavior) = REQUIRED];
}

// Request object for `BatchCreateNativeStyles` method.
message BatchCreateNativeStylesRequest {
  // Required. The parent resource where `NativeStyles` will be created.
  // Format: `networks/{network_code}`
  // The parent field in the CreateNativeStyleRequest must match this
  // field.
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The `NativeStyle` objects to create.
  // A maximum of 100 objects can be created in a batch.
  repeated CreateNativeStyleRequest requests = 2
      [(google.api.field_behavior) = REQUIRED];
}

// Response object for `BatchCreateNativeStyles` method.
message BatchCreateNativeStylesResponse {
  // The `NativeStyle` objects created.
  repeated NativeStyle native_styles = 1;
}

// Request object for `UpdateNativeStyle` method.
message UpdateNativeStyleRequest {
  // Required. The `NativeStyle` to update.
  //
  // The `NativeStyle`'s `name` is used to identify the `NativeStyle` to update.
  NativeStyle native_style = 1 [(google.api.field_behavior) = REQUIRED];

  // Optional. The list of fields to update.
  google.protobuf.FieldMask update_mask = 2
      [(google.api.field_behavior) = OPTIONAL];
}

// Request object for `BatchUpdateNativeStyles` method.
message BatchUpdateNativeStylesRequest {
  // Required. The parent resource where `NativeStyles` will be updated.
  // Format: `networks/{network_code}`
  // The parent field in the UpdateNativeStyleRequest must match this
  // field.
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The `NativeStyle` objects to update.
  // A maximum of 100 objects can be updated in a batch.
  repeated UpdateNativeStyleRequest requests = 2
      [(google.api.field_behavior) = REQUIRED];
}

// Response object for `BatchUpdateNativeStyles` method.
message BatchUpdateNativeStylesResponse {
  // The `NativeStyle` objects updated.
  repeated NativeStyle native_styles = 1;
}

// Request object for `BatchActivateNativeStyles` method.
message BatchActivateNativeStylesRequest {
  // Required. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. Resource names for the `NativeStyle`s.
  // Format: `networks/{network_code}/nativeStyles/{native_style_id}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/NativeStyle"
    }
  ];
}

// Response object for `BatchActivateNativeStyles` method.
message BatchActivateNativeStylesResponse {}

// Request object for `BatchDeactivateNativeStyles` method.
message BatchDeactivateNativeStylesRequest {
  // Required. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. Resource names for the `NativeStyle`s.
  // Format: `networks/{network_code}/nativeStyles/{native_style_id}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/NativeStyle"
    }
  ];
}

// Response object for `BatchDeactivateNativeStyles` method.
message BatchDeactivateNativeStylesResponse {}

// Request object for `BatchArchiveNativeStyles` method.
message BatchArchiveNativeStylesRequest {
  // Required. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. Resource names for the `NativeStyle`s.
  // Format: `networks/{network_code}/nativeStyles/{native_style_id}`
  repeated string names = 2 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/NativeStyle"
    }
  ];
}

// Response object for `BatchArchiveNativeStyles` method.
message BatchArchiveNativeStylesResponse {}
