// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

import "google/ads/admanager/v1/partner_messages.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/field_mask.proto";

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "PartnerServiceProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Provides methods for handling [Partner][google.ads.admanager.v1.Partner]
// objects.
service PartnerService {
  option (google.api.default_host) = "admanager.googleapis.com";
  option (google.api.oauth_scopes) =
      "https://www.googleapis.com/auth/admanager,"
      "https://www.googleapis.com/auth/admanager.readonly";

  // Retrieves a [Partner][google.ads.admanager.v1.Partner] object.
  rpc GetPartner(GetPartnerRequest) returns (Partner) {
    option (google.api.http) = {
      get: "/v1/{name=networks/*/partners/*}"
    };
    option (google.api.method_signature) = "name";
  }

  // Lists [Partner][google.ads.admanager.v1.Partner] objects.
  rpc ListPartners(ListPartnersRequest) returns (ListPartnersResponse) {
    option (google.api.http) = {
      get: "/v1/{parent=networks/*}/partners"
    };
    option (google.api.method_signature) = "parent";
  }

  // Updates a [Partner][google.ads.admanager.v1.Partner] object.
  rpc UpdatePartner(UpdatePartnerRequest) returns (Partner) {
    option (google.api.http) = {
      patch: "/v1/{partner.name=networks/*/partners/*}"
      body: "partner"
    };
    option (google.api.method_signature) = "partner,update_mask";
  }

  // Batch updates [Partner][google.ads.admanager.v1.Partner] objects.
  rpc BatchUpdatePartners(BatchUpdatePartnersRequest)
      returns (BatchUpdatePartnersResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/partners:batchUpdate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,requests";
  }
}

// Request object for [GetPartner][] method.
message GetPartnerRequest {
  // Required. The resource name of the
  // [Partner][google.ads.admanager.v1.Partner]. Format:
  // `networks/{network_code}/partners/{partner_id}`
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Partner"
    }
  ];
}

// Request object for [ListPartners][] method.
message ListPartnersRequest {
  // Required. The parent, which owns this collection of
  // [Partner][google.ads.admanager.v1.Partner]s. Format:
  // `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Optional. The maximum number of [Partner][google.ads.admanager.v1.Partner]s
  // to return. The service may return fewer than this value. If unspecified, at
  // most 50 [Partner][google.ads.admanager.v1.Partner]s will be returned. The
  // maximum value is 1000; values greater than 1000 will be coerced to 1000.
  int32 page_size = 2 [(google.api.field_behavior) = OPTIONAL];

  // Optional. A page token, received from a previous [ListPartners][] call.
  // Provide this to retrieve the subsequent page.
  //
  // When paginating, all other parameters provided to [ListPartners][] must
  // match the call that provided the page token.
  string page_token = 3 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to filter the response.
  //  See syntax details at
  //  https://developers.google.com/ad-manager/api/beta/filters
  //
  // **Filterable fields:**
  //
  // * `address`
  // * `comment`
  // * `creditStatus`
  // * `displayName`
  // * `email`
  // * `externalId`
  // * `fax`
  // * `name`
  // * `phone`
  string filter = 4 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to specify sorting order.
  // See syntax details at
  // https://developers.google.com/ad-manager/api/beta/filters#order
  string order_by = 5 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Number of individual resources to skip while paginating.
  int32 skip = 6 [(google.api.field_behavior) = OPTIONAL];
}

// Response object for
// [ListPartnersRequest][google.ads.admanager.v1.ListPartnersRequest] containing
// matching [Partner][google.ads.admanager.v1.Partner] objects.
message ListPartnersResponse {
  // The [Partner][google.ads.admanager.v1.Partner] objects from the specified
  // network.
  repeated Partner partners = 1;

  // A token, which can be sent as `page_token` to retrieve the next page.
  // If this field is omitted, there are no subsequent pages.
  string next_page_token = 2;

  // Total number of [Partner][google.ads.admanager.v1.Partner] objects.
  // If a filter was included in the request, this reflects the total number
  // after the filtering is applied.
  //
  // `total_size` won't be calculated in the response unless it has been
  // included in a response field mask. The response field mask can be provided
  // to the method by using the URL parameter `$fields` or `fields`, or by using
  // the HTTP/gRPC header `X-Goog-FieldMask`.
  //
  // For more information, see
  // https://developers.google.com/ad-manager/api/beta/field-masks
  int32 total_size = 3;
}

// Request object for [UpdatePartner][] method.
message UpdatePartnerRequest {
  // Required. The [Partner][google.ads.admanager.v1.Partner] to update.
  //
  // The [Partner][google.ads.admanager.v1.Partner]'s `name` is used to identify
  // the [Partner][google.ads.admanager.v1.Partner] to update.
  Partner partner = 1 [(google.api.field_behavior) = REQUIRED];

  // Optional. The list of fields to update.
  google.protobuf.FieldMask update_mask = 2
      [(google.api.field_behavior) = OPTIONAL];
}

// Request object for [BatchUpdatePartners][] method.
message BatchUpdatePartnersRequest {
  // Required. The parent resource where
  // [Partner][google.ads.admanager.v1.Partner]s will be updated. Format:
  // `networks/{network_code}` The parent field in the
  // [UpdatePartnerRequest][google.ads.admanager.v1.UpdatePartnerRequest] must
  // match this field.
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The [Partner][google.ads.admanager.v1.Partner] objects to update.
  // A maximum of 100 objects can be updated in a batch.
  repeated UpdatePartnerRequest requests = 2
      [(google.api.field_behavior) = REQUIRED];
}

// Response object for [BatchUpdatePartners][] method.
message BatchUpdatePartnersResponse {
  // The [Partner][google.ads.admanager.v1.Partner] objects updated.
  repeated Partner partners = 1;
}
