// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

import "google/ads/admanager/v1/applied_label.proto";
import "google/ads/admanager/v1/company_enums.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/timestamp.proto";

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "PartnerMessagesProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// The [Partner][google.ads.admanager.v1.Partner] resource.
//
// Represents a publishing partner with established agreements to share
// inventory and revenue based on assignments.
//
// For more information, see [Add publishing partner assignments]
// (https://support.google.com/admanager/answer/7032752).
message Partner {
  option (google.api.resource) = {
    type: "admanager.googleapis.com/Partner"
    pattern: "networks/{network_code}/partners/{partner}"
    plural: "partners"
    singular: "partner"
  };

  // Identifier. The resource name of the
  // [Partner][google.ads.admanager.v1.Partner]. Format:
  // `networks/{network_code}/partners/{partner_id}`
  string name = 1 [(google.api.field_behavior) = IDENTIFIER];

  // Required. The display name of the
  // [Partner][google.ads.admanager.v1.Partner].
  optional string display_name = 3 [(google.api.field_behavior) = REQUIRED];

  // Optional. The address for the [Partner][google.ads.admanager.v1.Partner].
  //
  // This value has a maximum length of 1024 characters.
  optional string address = 4 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The email for the [Partner][google.ads.admanager.v1.Partner].
  //
  // This value has a maximum length of 128 characters.
  optional string email = 5 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The fax number for the
  // [Partner][google.ads.admanager.v1.Partner].
  //
  // This value has a maximum length of 63 characters.
  optional string fax = 6 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The phone number for the
  // [Partner][google.ads.admanager.v1.Partner].
  //
  // This value has a maximum length of 63 characters.
  optional string phone = 7 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The external ID for the
  // [Partner][google.ads.admanager.v1.Partner].
  //
  // This value has a maximum length of 255 characters.
  optional string external_id = 8 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Comments about the [Partner][google.ads.admanager.v1.Partner].
  //
  // This value has a maximum length of 1024 characters.
  optional string comment = 9 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The labels that are directly applied to the
  // [Partner][google.ads.admanager.v1.Partner].
  repeated AppliedLabel applied_labels = 10
      [(google.api.field_behavior) = OPTIONAL];

  // Optional. The resource names of primary Contact of the
  // [Partner][google.ads.admanager.v1.Partner]. Format:
  // "networks/{network_code}/contacts/{contact_id}"
  optional string primary_contact = 11 [
    (google.api.field_behavior) = OPTIONAL,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Contact"
    }
  ];

  // Optional. The resource names of Teams that are directly associated with the
  // [Partner][google.ads.admanager.v1.Partner].
  // Format: "networks/{network_code}/teams/{team_id}"
  repeated string applied_teams = 13 [
    (google.api.field_behavior) = OPTIONAL,
    (google.api.resource_reference) = { type: "admanager.googleapis.com/Team" }
  ];

  // Output only. The time the [Partner][google.ads.admanager.v1.Partner] was
  // last updated.
  google.protobuf.Timestamp update_time = 15
      [(google.api.field_behavior) = OUTPUT_ONLY];

  // Optional. The credit status of the
  // [Partner][google.ads.admanager.v1.Partner].
  //
  // This attribute defaults to [CompanyCreditStatus.ACTIVE][] if basic
  // settings are enabled and [CompanyCreditStatus.ON_HOLD][] if advance
  // settings are enabled.
  optional CompanyCreditStatusEnum.CompanyCreditStatus credit_status = 16
      [(google.api.field_behavior) = OPTIONAL];
}
