// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

import "google/ads/admanager/v1/rich_media_studio_child_asset_type_enum.proto";
import "google/api/field_behavior.proto";

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "RichMediaStudioMessagesProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Represents a child asset in RichMediaStudioCreative.
message RichMediaStudioChildAssetProperty {
  // Output only. The name of the asset as known by Rich Media Studio.
  optional string display_name = 1 [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. Required file type of the asset.
  optional RichMediaStudioChildAssetTypeEnum.RichMediaStudioChildAssetType
      type = 2 [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. The total size of the asset in bytes.
  optional int64 total_file_size = 3
      [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. Width of the widget in pixels.
  optional int32 width = 4 [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. Height of the widget in pixels.
  optional int32 height = 5 [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. The URL of the asset.
  optional string url = 6 [(google.api.field_behavior) = OUTPUT_ONLY];
}
