// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "RichMediaStudioCreativeFormatEnumProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Wrapper message for
// [RichMediaStudioCreativeFormat][google.ads.admanager.v1.RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat]
message RichMediaStudioCreativeFormatEnum {
  // Different creative format supported by Rich Media Studio creative.
  enum RichMediaStudioCreativeFormat {
    // Default value. This value is unused.
    RICH_MEDIA_STUDIO_CREATIVE_FORMAT_UNSPECIFIED = 0;

    // Expanding creatives expand/collapse on user interaction such as mouse
    // over. It consists of an initial, or collapsed and an expanded creative
    // area.
    EXPANDING = 1;

    // A Flash ad that renders in a Flash environment.  The adserver will serve
    // this using VAST, but it is not a proper VAST XML ad.  It's an
    // amalgamation of the proprietary InStream protocol, rendered inside VAST
    // so that we can capture some standard behavior such as companions.
    FLASH_IN_FLASH = 2;

    // An expanding flash ad that renders in a Flash environment. The adserver
    // will serve this using VAST, but it is not a proper VAST XML ad. It's an
    // amalgamation of the proprietary InStream protocol, rendered inside VAST
    // so that we can capture some standard behavior such as companions.
    FLASH_IN_FLASH_EXPANDING = 3;

    // Floating creatives float on top of publishers page and can be closed with
    // a close button.
    FLOATING = 4;

    // Creatives that are served in an instant messenger application such as
    // AOL Instant Messanger or Yahoo! Messenger. This can also be used in
    // desktop applications such as weatherbug.
    IM_EXPANDING = 5;

    // In-app creatives are served into an ad slot within a publisher's app.
    // In-app implies that they maintain a static size, e.g., 468x60 and
    // do not break out of these dimensions.
    IN_APP = 6;

    // In-page creatives are served into an ad slot on publishers page.
    // In-page implies that they maintain a static size, e.g., 468x60 and
    // do not break out of these dimensions.
    IN_PAGE = 7;

    // An In-Page with Floating creative is a dual-asset creative consisting of
    // an in-page asset and a floating asset. This creative type lets you
    // deliver a static primary ad to a webpage, while inviting a user to find
    // out more through a floating asset delivered when the user interacts with
    // the creative.
    IN_PAGE_WITH_FLOATING = 8;

    // Peel-down creatives show a glimpse of your ad in the corner of a web
    // page. When the user interacts, the rest of the ad peels down to reveal
    // the full message.
    PEEL_DOWN = 9;

    // A creative format that follows the VPAID 2.0 protocol. The ad appears in
    // the publisher's video player, and allows user interactivity with the
    // video ad. The linear format runs pre-roll, post-roll, or interrupts the
    // publisher's video content.
    VPAID_LINEAR = 10;

    // A creative format that follows the VPAID 2.0 protocol. The ad appears in
    // the publisher's video player, and allows user interactivity with the
    // video ad. The non-linear format runs parallel to the publisher's video
    // content.
    VPAID_NON_LINEAR = 11;
  }
}
