// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "RichMediaStudioCreativeBillingAttributeEnumProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Wrapper message for
// [RichMediaStudioCreativeBillingAttribute][google.ads.admanager.v1.RichMediaStudioCreativeBillingAttributeEnum.RichMediaStudioCreativeBillingAttribute]
message RichMediaStudioCreativeBillingAttributeEnum {
  // Rich Media Studio creative supported billing attributes.
  //
  // This is determined by Rich Media Studio based on the content
  // of the creative and is not updateable.
  enum RichMediaStudioCreativeBillingAttribute {
    // Default value. This value is unused.
    RICH_MEDIA_STUDIO_CREATIVE_BILLING_ATTRIBUTE_UNSPECIFIED = 0;

    // Applies to any
    // [RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.FLASH_IN_FLASH][google.ads.admanager.v1.RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.FLASH_IN_FLASH],
    // without Video.
    FLASH_IN_FLASH = 1;

    // Applies to any of the following
    // [RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat][google.ads.admanager.v1.RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat]
    // values, without Video:
    //
    // * [RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.EXPANDING][google.ads.admanager.v1.RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.EXPANDING]
    // * [RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.IM_EXPANDING][google.ads.admanager.v1.RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.IM_EXPANDING]
    // * [RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.FLOATING][google.ads.admanager.v1.RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.FLOATING]
    // * [RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.PEEL_DOWN][google.ads.admanager.v1.RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.PEEL_DOWN]
    // * [RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.IN_PAGE_WITH_FLOATING][google.ads.admanager.v1.RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.IN_PAGE_WITH_FLOATING]
    FLOATING_EXPANDING = 2;

    // Applies to any
    // [RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.IN_PAGE][google.ads.admanager.v1.RichMediaStudioCreativeFormatEnum.RichMediaStudioCreativeFormat.IN_PAGE],
    // without Video.
    IN_PAGE = 3;

    // Applies to any creatives that includes a video.
    VIDEO = 4;
  }
}
