// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

import "google/ads/admanager/v1/viewability_provider_messages.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/field_mask.proto";

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "ViewabilityProviderServiceProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// Provides methods for handling
// [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] objects.
service ViewabilityProviderService {
  option (google.api.default_host) = "admanager.googleapis.com";
  option (google.api.oauth_scopes) =
      "https://www.googleapis.com/auth/admanager,"
      "https://www.googleapis.com/auth/admanager.readonly";

  // Retrieves a
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] object.
  rpc GetViewabilityProvider(GetViewabilityProviderRequest)
      returns (ViewabilityProvider) {
    option (google.api.http) = {
      get: "/v1/{name=networks/*/viewabilityProviders/*}"
    };
    option (google.api.method_signature) = "name";
  }

  // Lists [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]
  // objects.
  rpc ListViewabilityProviders(ListViewabilityProvidersRequest)
      returns (ListViewabilityProvidersResponse) {
    option (google.api.http) = {
      get: "/v1/{parent=networks/*}/viewabilityProviders"
    };
    option (google.api.method_signature) = "parent";
  }

  // Creates a
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] object.
  rpc CreateViewabilityProvider(CreateViewabilityProviderRequest)
      returns (ViewabilityProvider) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/viewabilityProviders"
      body: "viewability_provider"
    };
    option (google.api.method_signature) = "parent,viewability_provider";
  }

  // Creates [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]
  // objects.
  rpc BatchCreateViewabilityProviders(BatchCreateViewabilityProvidersRequest)
      returns (BatchCreateViewabilityProvidersResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/viewabilityProviders:batchCreate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,requests";
  }

  // Updates a
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] object.
  rpc UpdateViewabilityProvider(UpdateViewabilityProviderRequest)
      returns (ViewabilityProvider) {
    option (google.api.http) = {
      patch: "/v1/{viewability_provider.name=networks/*/viewabilityProviders/*}"
      body: "viewability_provider"
    };
    option (google.api.method_signature) = "viewability_provider,update_mask";
  }

  // Batch updates
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] objects.
  rpc BatchUpdateViewabilityProviders(BatchUpdateViewabilityProvidersRequest)
      returns (BatchUpdateViewabilityProvidersResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=networks/*}/viewabilityProviders:batchUpdate"
      body: "*"
    };
    option (google.api.method_signature) = "parent,requests";
  }
}

// Request object for [GetViewabilityProvider][] method.
message GetViewabilityProviderRequest {
  // Required. The resource name of the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]. Format:
  // `networks/{network_code}/viewabilityProviders/{viewability_provider}`
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/ViewabilityProvider"
    }
  ];
}

// Request object for [ListViewabilityProviders][] method.
message ListViewabilityProvidersRequest {
  // Required. The parent, which owns this collection of
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]s.
  // Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Optional. The maximum number of
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]s to
  // return. The service may return fewer than this value. If unspecified, at
  // most 50 [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]s
  // will be returned. The maximum value is 1000; values above 1000 will be
  // coerced to 1000.
  int32 page_size = 2 [(google.api.field_behavior) = OPTIONAL];

  // Optional. A page token, received from a previous
  // [ListViewabilityProviders][] call. Provide this to retrieve the subsequent
  // page.
  //
  // When paginating, all other parameters provided to
  // [ListViewabilityProviders][] must match the call that provided the page
  // token.
  string page_token = 3 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to filter the response.
  //  See syntax details at
  //  https://developers.google.com/ad-manager/api/beta/filters
  //
  // **Filterable fields:**
  //
  // * `address`
  // * `comment`
  // * `displayName`
  // * `email`
  // * `externalId`
  // * `fax`
  // * `name`
  // * `phone`
  // * `primaryContact`
  // * `rejectionTrackerUrl`
  // * `vendorKey`
  // * `verificationScriptUrl`
  // * `verificationScriptUrlParameters`
  string filter = 4 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Expression to specify sorting order.
  // See syntax details at
  // https://developers.google.com/ad-manager/api/beta/filters#order
  string order_by = 5 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Number of individual resources to skip while paginating.
  int32 skip = 6 [(google.api.field_behavior) = OPTIONAL];
}

// Response object for [ListViewabilityProviders][] containing matching
// [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] objects.
message ListViewabilityProvidersResponse {
  // The [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]
  // objects from the specified network.
  repeated ViewabilityProvider viewability_providers = 1;

  // A token, which can be sent as `page_token` to retrieve the next page.
  // If this field is omitted, there are no subsequent pages.
  string next_page_token = 2;

  // Total number of
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] objects.
  // If a filter was included in the request, this reflects the total number
  // after the filtering is applied.
  //
  // `total_size` won't be calculated in the response unless it has been
  // included in a response field mask. The response field mask can be provided
  // to the method by using the URL parameter `$fields` or `fields`, or by using
  // the HTTP/gRPC header `X-Goog-FieldMask`.
  //
  // For more information, see
  // https://developers.google.com/ad-manager/api/beta/field-masks
  int32 total_size = 3;
}

// Request object for [CreateViewabilityProvider][] method.
message CreateViewabilityProviderRequest {
  // Required. The parent resource where this
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] will be
  // created. Format: `networks/{network_code}`
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] to
  // create.
  ViewabilityProvider viewability_provider = 2
      [(google.api.field_behavior) = REQUIRED];
}

// Request object for [BatchCreateViewabilityProviders][] method.
message BatchCreateViewabilityProvidersRequest {
  // Required. The parent resource where
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]s will be
  // created. Format: `networks/{network_code}` The parent field in the
  // CreateViewabilityProviderRequest must match this field.
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] objects
  // to create. A maximum of 100 objects can be created in a batch.
  repeated CreateViewabilityProviderRequest requests = 2
      [(google.api.field_behavior) = REQUIRED];
}

// Response object for [BatchCreateViewabilityProviders][] method.
message BatchCreateViewabilityProvidersResponse {
  // The [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]
  // objects created.
  repeated ViewabilityProvider viewability_providers = 1;
}

// Request object for [UpdateViewabilityProvider][] method.
message UpdateViewabilityProviderRequest {
  // Required. The
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] to
  // update.
  //
  // The [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]'s
  // `name` is used to identify the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] to
  // update.
  ViewabilityProvider viewability_provider = 1
      [(google.api.field_behavior) = REQUIRED];

  // Optional. The list of fields to update.
  google.protobuf.FieldMask update_mask = 2
      [(google.api.field_behavior) = OPTIONAL];
}

// Request object for [BatchUpdateViewabilityProviders][] method.
message BatchUpdateViewabilityProvidersRequest {
  // Required. The parent resource where
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]s will be
  // updated. Format: `networks/{network_code}` The parent field in the
  // UpdateViewabilityProviderRequest must match this field.
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Network"
    }
  ];

  // Required. The
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] objects
  // to update. A maximum of 100 objects can be updated in a batch.
  repeated UpdateViewabilityProviderRequest requests = 2
      [(google.api.field_behavior) = REQUIRED];
}

// Response object for [BatchUpdateViewabilityProviders][] method.
message BatchUpdateViewabilityProvidersResponse {
  // The [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]
  // objects updated.
  repeated ViewabilityProvider viewability_providers = 1;
}
