// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.ads.admanager.v1;

import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/timestamp.proto";

option csharp_namespace = "Google.Ads.AdManager.V1";
option go_package = "google.golang.org/genproto/googleapis/ads/admanager/v1;admanager";
option java_multiple_files = true;
option java_outer_classname = "ViewabilityProviderMessagesProto";
option java_package = "com.google.ads.admanager.v1";
option php_namespace = "Google\\Ads\\AdManager\\V1";
option ruby_package = "Google::Ads::AdManager::V1";

// The [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]
// resource.
//
// Represents a third-party company used to measure creative viewability.
message ViewabilityProvider {
  option (google.api.resource) = {
    type: "admanager.googleapis.com/ViewabilityProvider"
    pattern: "networks/{network_code}/viewabilityProviders/{viewability_provider}"
    plural: "viewabilityProviders"
    singular: "viewabilityProvider"
  };

  // Identifier. The resource name of the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]. Format:
  // `networks/{network_code}/viewabilityProviders/{viewability_provider}`
  string name = 1 [(google.api.field_behavior) = IDENTIFIER];

  // Required. The display name of the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider].
  optional string display_name = 3 [(google.api.field_behavior) = REQUIRED];

  // Required. The key for the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider].
  optional string vendor_key = 4 [(google.api.field_behavior) = REQUIRED];

  // Required. The URL that hosts the verification script for the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider].
  optional string verification_script_url = 5
      [(google.api.field_behavior) = REQUIRED];

  // Optional. The URL parameters that will be passed to the verification
  // script.
  optional string verification_script_url_parameters = 6
      [(google.api.field_behavior) = OPTIONAL];

  // Optional. The URL that should be pinged if the verification script cannot
  // be run.
  optional string rejection_tracker_url = 7
      [(google.api.field_behavior) = OPTIONAL];

  // Optional. The address of the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider].
  optional string address = 8 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The email of the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider].
  optional string email = 9 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The fax number of the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider].
  optional string fax = 10 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The phone number of the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider].
  optional string phone = 11 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The external ID of the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider].
  optional string external_id = 12 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Comment about the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider].
  optional string comment = 13 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The resource name of primary Contact of the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider]. Format:
  // "networks/{network_code}/contacts/{contact_id}"
  optional string primary_contact = 14 [
    (google.api.field_behavior) = OPTIONAL,
    (google.api.resource_reference) = {
      type: "admanager.googleapis.com/Contact"
    }
  ];

  // Optional. The resource names of Teams that are directly associated with the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider].
  // Format: "networks/{network_code}/teams/{team_id}"
  repeated string applied_teams = 16 [
    (google.api.field_behavior) = OPTIONAL,
    (google.api.resource_reference) = { type: "admanager.googleapis.com/Team" }
  ];

  // Output only. The time the
  // [ViewabilityProvider][google.ads.admanager.v1.ViewabilityProvider] was last
  // updated.
  google.protobuf.Timestamp update_time = 18
      [(google.api.field_behavior) = OUTPUT_ONLY];
}
