// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.chat.v1;

import "google/api/field_behavior.proto";
import "google/chat/v1/cited_source.proto";

option csharp_namespace = "Google.Apps.Chat.V1";
option go_package = "cloud.google.com/go/chat/apiv1/chatpb;chatpb";
option java_multiple_files = true;
option java_outer_classname = "CitationProto";
option java_package = "com.google.chat.v1";
option php_namespace = "Google\\Apps\\Chat\\V1";
option ruby_package = "Google::Apps::Chat::V1";

// [Developer Preview](https://developers.google.com/workspace/preview):
// Citations are inline references that can provide users more detailed
// information about the inline reference. Corresponding inline citations
// should be present in the message text in a markup format of
// `<chat-citation data-id="{id}">{text}</chat-citation>`. Citations are
// only supported when the message's `markup_syntax` is set to `MARKDOWN`.
//
// Unreferenced citations in `Elements.citations` (those without a matching
// `<chat-citation>` tag in the message text) are ignored and do not cause the
// message to be rejected.
message Citation {
  // Required. App defined id. Must contain only ASCII letters and numbers, and
  // less than 63 characters.
  string id = 1 [(google.api.field_behavior) = REQUIRED];

  // Optional. A list of sources that are relevant to the citation. Sources are
  // displayed in the citation hover card.
  repeated CitedSource cited_sources = 3
      [(google.api.field_behavior) = OPTIONAL];
}
