// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.chat.v1;

import "google/api/field_behavior.proto";
import "google/chat/v1/elements_common.proto";

option csharp_namespace = "Google.Apps.Chat.V1";
option go_package = "cloud.google.com/go/chat/apiv1/chatpb;chatpb";
option java_multiple_files = true;
option java_outer_classname = "CitedSourceProto";
option java_package = "com.google.chat.v1";
option php_namespace = "Google\\Apps\\Chat\\V1";
option ruby_package = "Google::Apps::Chat::V1";

// [Developer Preview](https://developers.google.com/workspace/preview):
// A reference to a source of information.
message CitedSource {
  // [Developer Preview](https://developers.google.com/workspace/preview):
  // A snippet object representing an excerpt from a larger corpus.
  message Snippet {
    // Optional. A short plaintext excerpt directly from the corpus that might
    // be rendered in Chat. Does not support markdown format.
    string text = 1 [(google.api.field_behavior) = OPTIONAL];

    // Optional. Image preview of the snippet provided as an input when creating
    // the citation.
    ElementsImage image_preview = 2 [(google.api.field_behavior) = OPTIONAL];
  }

  // [Developer Preview](https://developers.google.com/workspace/preview):
  // A footer for a source, used for attribution.
  message Footer {
    // Optional. The text to display in the footer.
    string text = 1 [(google.api.field_behavior) = OPTIONAL];
  }

  // Required. The plaintext title of the `CitedSource`. This field does not
  // support formatting.
  string title = 1 [(google.api.field_behavior) = REQUIRED];

  // Required. The URI pointing to the resource referenced by this
  // `CitedSource`.
  string uri = 2 [(google.api.field_behavior) = REQUIRED];

  // Optional. Snippet containing information directly from the source.
  Snippet snippet = 3 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Additional information to show alongside the snippet in the form
  // of a footer.
  Footer footer = 5 [(google.api.field_behavior) = OPTIONAL];
}
