// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.cloud.bigquery.v2;

option go_package = "cloud.google.com/go/bigquery/v2/apiv2/bigquerypb;bigquerypb";
option java_multiple_files = true;
option java_outer_classname = "ArrowProto";
option java_package = "com.google.cloud.bigquery.v2";

// Arrow schema as specified
// in https://arrow.apache.org/docs/python/api/datatypes.html and serialized to
// bytes using IPC:
// https://arrow.apache.org/docs/format/Columnar.html#serialization-and-interprocess-communication-ipc
//
// See code samples on how this message can be deserialized.
//
// This feature is not yet available.
message ArrowSchema {
  // IPC serialized Arrow schema.
  bytes serialized_schema = 1;
}

// Arrow RecordBatch.
//
// This feature is not yet available.
message ArrowRecordBatch {
  // IPC-serialized Arrow RecordBatch.
  bytes serialized_record_batch = 1;
}

// Contains options specific to Arrow Serialization.
//
// This feature is not yet available.
message ArrowSerializationOptions {
  // Compression codec's supported by Arrow.
  enum CompressionCodec {
    // If unspecified no compression will be used.
    COMPRESSION_UNSPECIFIED = 0;

    // LZ4 Frame (https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md)
    LZ4_FRAME = 1;

    // Zstandard compression.
    ZSTD = 2;
  }

  // The precision of the timestamp value in the Avro message. This precision
  // will **only** be applied to the column(s) with the `TIMESTAMP_PICOS` type.
  enum PicosTimestampPrecision {
    // Unspecified timestamp precision. The default precision is microseconds.
    PICOS_TIMESTAMP_PRECISION_UNSPECIFIED = 0;

    // Timestamp values returned in the results will be truncated to microsecond
    // level precision. The value will be encoded as Arrow TIMESTAMP type in a
    // 64 bit integer.
    TIMESTAMP_PRECISION_MICROS = 1;

    // Timestamp values returned in the results will be truncated to nanosecond
    // level precision. The value will be encoded as Arrow TIMESTAMP type in a
    // 64 bit integer.
    TIMESTAMP_PRECISION_NANOS = 2;

    // Timestamp values returned in the results will contain full precision
    // picosecond value. The value will be encoded as a string which conforms to
    // ISO 8601 format.
    TIMESTAMP_PRECISION_PICOS = 3;
  }

  // The compression codec to use for Arrow buffers in serialized record
  // batches.
  CompressionCodec buffer_compression = 2;

  // Optional. Set timestamp precision option. If not set, the default precision
  // is microseconds.
  PicosTimestampPrecision picos_timestamp_precision = 3;
}
