#! /bin/bash

# ⚠️  This makes a LOT of assumptions. It will probably break for you.

if [ "$#" -ne 2 ]; then
  echo "Usage: ./script/edit [api_name] [api_version]"
  echo
  echo 'Opens the relevant GAPIC configuration file in your $EDITOR'
  echo
  echo "Your editor is set to: $EDITOR"
fi

API_NAME="$1"
API_VERSION="$2"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CODE_SAMPLES_DIR="$( dirname "$SCRIPT_DIR" )"
GOOGLEAPIS_DIR="$( dirname "$CODE_SAMPLES_DIR" )"
GOOGLE_DIR="$GOOGLEAPIS_DIR/google"

GAPIC_CONFIG="$( find "$GOOGLE_DIR" -type f -name "${API_NAME}_gapic.yaml" | grep "/$API_VERSION/" )"

if [ -n "$GAPIC_CONFIG" ]; then
  $EDITOR "$GAPIC_CONFIG"
else
  echo "No GAPIC configuration file found for $API_NAME $API_VERSION"
fi
