#! /bin/bash

# Pulls down the generator repository into script/.go-generator-repo
# and installs the binary for `gen-go-sample`
#
# The .go-generator-repo directory is in .gitignore

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$SCRIPT_DIR"

REPO_FOLDER=.go-generator-repo

if [ -d "$REPO_FOLDER" ]; then
  echo "gapic-generator-go is already cloned to script/$REPO_FOLDER"
  echo "to re-install, please rm -rf script/$REPO_FOLDER and run again."
  echo "You may want to 'go clean -i ./cmd/gen-go-sample' first."
  exit 1
fi

git clone https://github.com/googleapis/gapic-generator-go $REPO_FOLDER
cd $REPO_FOLDER
go install ./cmd/gen-go-sample

if which gen-go-sample > /dev/null; then
  echo "gen-go-sample installed (`which gen-go-sample`)"
else
  echo "Something went wrong, gen-go-sample not in PATH"
fi
