#! /bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage: ./script/run [path-to-sample-script]"
fi

##

SAMPLE_SCRIPT="$1"

if [[ $SAMPLE_SCRIPT == *.py ]]; then
  cd "$(dirname $SAMPLE_SCRIPT)"
  virtualenv --python python3 env > /dev/null
  source env/bin/activate
  pip install -r requirements.txt > /dev/null
  python "$(basename $SAMPLE_SCRIPT)"
elif [[ $SAMPLE_SCRIPT == *.php ]]; then
  cd "$(dirname $SAMPLE_SCRIPT)"
  composer install
  python "$(basename $SAMPLE_SCRIPT)"
else
  echo "Unsure how to run sample script: $SAMPLE_SCRIPT"
  echo "Expected one of: .php .py"
  exit 1
fi
