#! /usr/bin/env ruby

require "yaml"

unless ARGV.length == 2
  puts "Usage: ./script/sample-yaml [gapic.yaml] [region tag]"
end

config_file, region_tag = ARGV.shift, ARGV.shift

puts config_file
puts region_tag

config = YAML.load_file config_file

config["interfaces"].each do |interface|
  interface["methods"].each do |method|
    if method.has_key? "sample_value_sets"
      method["sample_value_sets"].each do |sample|
        if sample["id"] == region_tag
          puts sample.to_yaml
          exit
        end
      end
    end
  end
end
