#! /bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage: ./script/test [folder with YAML test files]"
fi

TEST_DIR="$1"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
TEST_SAMPLE_PY="$SCRIPT_DIR/pysampletester/test_sample.py"

$TEST_SAMPLE_PY $TEST_DIR/*.yaml
