common:
  batch_apis: '*'
  batch_languages: '*'
  api_config_pattern: ${THISDIR}/../api/artman_*.yaml
  artman_language_yaml: ${THISDIR}/../lang/common.yaml
  batch_output_dir: ${REPOROOT}/staging-repo-test/generated
