common:
  apis: '*'
  languages: '*'
  api_config_pattern: '${REPOROOT}/googleapis/gapic/api/artman_*.yaml'
  artman_language_yaml: '${REPOROOT}/googleapis/gapic/lang/common.yaml'
  batch_output_dir: '${REPOROOT}/staging-repo-test/generated'
