// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.cloud.chronicle.v1beta;

import "backstory/collection.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/cloud/chronicle/v1beta/data_access_control.proto";
import "google/cloud/chronicle/v1beta/entity.proto";
import "google/cloud/chronicle/v1beta/event.proto";
import "google/cloud/chronicle/v1beta/simulated_data.proto";
import "google/longrunning/operations.proto";
import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";
import "google/rpc/status.proto";
import "google/type/date.proto";
import "google/type/interval.proto";

option csharp_namespace = "Google.Cloud.Chronicle.V1Beta";
option go_package = "cloud.google.com/go/chronicle/apiv1beta/chroniclepb;chroniclepb";
option java_multiple_files = true;
option java_outer_classname = "SearchProto";
option java_package = "com.google.cloud.chronicle.v1beta";
option php_namespace = "Google\\Cloud\\Chronicle\\V1beta";
option ruby_package = "Google::Cloud::Chronicle::V1beta";

// SearchService provides methods for searching data in Chronicle.
service SearchService {
  option (google.api.default_host) = "chronicle.googleapis.com";
  option (google.api.oauth_scopes) =
      "https://www.googleapis.com/auth/chronicle,"
      "https://www.googleapis.com/auth/chronicle.readonly,"
      "https://www.googleapis.com/auth/cloud-platform";

  // Initiates a long-running search operation.
  rpc Search(SearchRequest) returns (google.longrunning.Operation) {
    option (google.api.http) = {
      post: "/v1beta/{parent=projects/*/locations/*/instances/*}:search"
      body: "*"
    };
    option (google.api.method_signature) = "parent,query,time_range";
    option (google.longrunning.operation_info) = {
      response_type: "SearchSession"
      metadata_type: "SearchOperationMetadata"
    };
  }

  // Retrieves results from a completed Search operation.
  rpc ListSearchedResults(ListSearchedResultsRequest)
      returns (ListSearchedResultsResponse) {
    option (google.api.http) = {
      get: "/v1beta/{parent=projects/*/locations/*/instances/*/searchSessions/*}/searchedResults"
    };
    option (google.api.method_signature) = "parent";
  }
}

// Specifies the dialect the Search Query is written in.
enum QueryDialect {
  // Defaults to YL2.
  QUERY_DIALECT_UNSPECIFIED = 0;

  // YL2 query dialect.
  YL2 = 1;

  // SQL query dialect.
  SQL = 2;
}

// SearchSession represents an asynchronous search session.
// Next ID: 7
message SearchSession {
  option (google.api.resource) = {
    type: "chronicle.googleapis.com/SearchSession"
    pattern: "projects/{project}/locations/{location}/instances/{instance}/searchSessions/{search_session}"
    plural: "searchSessions"
    singular: "searchSession"
  };

  // Identifier. The resource name of the search session.
  // Format:
  // projects/{project}/locations/{location}/instances/{instance}/searchSessions/{search_session}
  string name = 1 [(google.api.field_behavior) = IDENTIFIER];

  // Required. The YL2/SQL query used for searching.
  // Example: 'ip=/172.*/ AND metadata.event_type!="NETWORK_CONNECTION" AND (
  // target.ip = "3.225.179.73" OR target.ip = "23.47.48.70")'
  string query = 2 [(google.api.field_behavior) = REQUIRED];

  // Required. Time range to search for [Inclusive start time, exclusive end
  // time).
  google.type.Interval time_range = 3 [(google.api.field_behavior) = REQUIRED];

  // Optional. Specifies how to parse the 'query' string. If not specified, the
  // query will be parsed as YL2.
  QueryDialect dialect = 4 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Data access scope used to filter events. This is intended to be
  // used by admins to preview in-development scopes. Should only be called by
  // users with global access.  If the caller does not have global access, the
  // request will fail.
  DataAccessScope draft_data_access_scope = 5
      [(google.api.field_behavior) = OPTIONAL];

  // Output only. Metadata about the search session.
  SearchSessionMetadata metadata = 6
      [(google.api.field_behavior) = OUTPUT_ONLY];
}

// SearchedResult contains the results of a Search operation.
// Next ID: 4
message SearchedResult {
  option (google.api.resource) = {
    type: "chronicle.googleapis.com/SearchedResult"
    pattern: "projects/{project}/locations/{location}/instances/{instance}/searchSessions/{search_session}/searchedResults/{searched_result}"
    plural: "searchedResults"
    singular: "searchedResult"
  };

  // Identifier. The resource name of the search results.
  // Format:
  // projects/{project}/locations/{location}/instances/{instance}/searchSessions/{search_session}/searchedResults/{searched_result}
  string name = 1 [(google.api.field_behavior) = IDENTIFIER];

  // Contains a flexible row which can support a standard UDM Event, Stats,
  // Entity Context, Join result, Data Table, etc.
  ResultRow result_row = 2;
}

// Request message for the Search method.
// Next ID: 8
message SearchRequest {
  // Required. The resource name of the instance on which to perform the search.
  // Format: projects/{project}/locations/{location}/instances/{instance}
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "chronicle.googleapis.com/Instance"
    }
  ];

  // Required. The YL2/SQL query used for searching.
  // Example: 'ip=/172.*/ AND metadata.event_type!="NETWORK_CONNECTION" AND (
  // target.ip = "3.225.179.73" OR target.ip = "23.47.48.70")'
  string query = 2 [(google.api.field_behavior) = REQUIRED];

  // Required. Time range to search for [Inclusive start time, exclusive end
  // time).
  google.type.Interval time_range = 3 [(google.api.field_behavior) = REQUIRED];

  // Optional. Specifies the dialect the Search Query is written in. If not
  // specified, the query will be parsed as YL2.
  QueryDialect dialect = 4 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Data access scope used to filter events. This is intended to be
  // used by admins to preview in-development scopes. Should only be called by
  // users with global access.  If the caller does not have global access, the
  // request will fail.
  DataAccessScope draft_data_access_scope = 5
      [(google.api.field_behavior) = OPTIONAL];

  // Optional. Requested maximum number of rows to materialize. The service may
  // return fewer. If unspecified, a server-side default of 10,000 is used. The
  // maximum value is 1,000,000.
  int32 result_limit = 6 [(google.api.field_behavior) = OPTIONAL];

  // Optional. Specifies visibility of simulated data to include in search
  // results.
  SimulatedDataVisibility simulated_data_visibility = 7
      [(google.api.field_behavior) = OPTIONAL];
}

// Request message for the ListSearchedResults method.
// Next ID: 6
message ListSearchedResultsRequest {
  // Required. The parent SearchSession resource name.
  // Format:
  // projects/{project}/locations/{location}/instances/{instance}/searchSessions/{search_session}
  string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "chronicle.googleapis.com/SearchSession"
    }
  ];

  // Optional. The maximum number of results to return. The service may return
  // fewer. If unspecified, at most 100 results will be returned. The maximum
  // value is 1000.
  int32 page_size = 2 [(google.api.field_behavior) = OPTIONAL];

  // Optional. A page token, received from a previous `ListSearchedResults`
  // call. Provide this to retrieve the subsequent page.
  string page_token = 3 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The column to sort the results on. Example: "event_timestamp
  // desc", "principal.hostname asc". Multi-columnar sorting is not supported.
  string order_by = 4 [(google.api.field_behavior) = OPTIONAL];

  // Optional. The number of results to skip before starting to return results.
  // This field should not be used in conjunction with page_token.
  int32 skip = 5 [(google.api.field_behavior) = OPTIONAL];
}

// Response message for the ListSearchedResults method.
// Next ID: 6
message ListSearchedResultsResponse {
  // List of Searched Results.
  repeated SearchedResult searched_results = 1;

  // Total number of rows in the result set of the search query.
  int32 total_size = 2;

  // List of column names for the outcome section of the query result.
  ColumnNames column_names = 3;

  // Column schema for the results based on the query columns. Contains metadata
  // like data source, event_name etc.
  ColumnSchema column_schema = 4;

  // A token, which can be sent as `page_token` to retrieve the next page.
  // If this field is omitted, there are no subsequent pages.
  string next_page_token = 5;
}

// Metadata about the search session.
// Next ID: 7
message SearchSessionMetadata {
  // Output only. The operation id corresponding to the search session which can
  // be used to poll the operation resource to know its state and progress.
  string operation_id = 1 [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. The start time of the session.
  google.protobuf.Timestamp start_time = 2
      [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. The end time of the session, if done.
  google.protobuf.Timestamp end_time = 3
      [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. The time when the search results expire.
  google.protobuf.Timestamp expire_time = 4
      [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. Total number of rows returned in the search session.
  int32 result_row_count = 5 [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. If true, there are more search results available than what can
  // be returned and have been omitted.
  bool more_data_available = 6 [(google.api.field_behavior) = OUTPUT_ONLY];
}

// Metadata for the google.longrunning.Operation returned by the Search
// method.
// Next ID: 7
message SearchOperationMetadata {
  // State of the Search operation.
  enum State {
    // Unspecified state.
    STATE_UNSPECIFIED = 0;

    // Initial state, Search operation is running.
    RUNNING = 1;

    // Search operation completed, results are available.
    SUCCEEDED = 2;

    // Search operation failed.
    FAILED = 3;

    // Search operation was cancelled.
    CANCELLED = 4;

    // Search operation expired.
    EXPIRED = 5;
  }

  // Output only. State of the Search operation.
  State state = 1 [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. The start time of the search.
  google.protobuf.Timestamp start_time = 2
      [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. The end time of the search, if done.
  google.protobuf.Timestamp end_time = 3
      [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. The time when the search results expire.
  google.protobuf.Timestamp expire_time = 4
      [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. Progress Percentage of the search LRO, ranges from 0 to 100.
  int32 progress = 5 [(google.api.field_behavior) = OUTPUT_ONLY];

  // Output only. Metadata of the data table export operation if the search
  // results are written to a Data Table.
  DataTableExportMetadata datatable_export_metadata = 6
      [(google.api.field_behavior) = OUTPUT_ONLY];
}

// Metadata about a DataTable export operation.
// Next ID: 4
message DataTableExportMetadata {
  // The result of the export operation.
  message ResultMetadata {
    // The operation ID of the export operation.
    string datatable_export_operation_id = 1;

    // The number of rows exported to the datatable.
    int32 rows_count = 2;
  }

  // Result or error of the export operation.
  oneof result_metadata_or_error {
    // The error result of the export operation in case of failure.
    google.rpc.Status error = 2;

    // Metadata about the export operation's result in case of success.
    ResultMetadata result_metadata = 3;
  }

  // The name of the DataTable.
  string data_table = 1;
}

// Metadata about a table used in a query.
message TableMetadata {
  // The type of data source.
  enum DataSource {
    // Unspecified data source.
    DATA_SOURCE_UNSPECIFIED = 0;

    // UDM events.
    EVENTS = 1;

    // Entity context.
    ENTITY_CONTEXT = 2;

    // Data tables.
    DATA_TABLES = 3;

    // Detections.
    DETECTIONS = 4;

    // SOAR cases.
    SOAR_CASE = 5;

    // SOAR case histories.
    SOAR_CASE_HISTORY = 6;
  }

  // The alias of the table in the query.
  string table = 1;

  // The type of data source.
  DataSource data_source = 2;

  // The index of the table in the query.
  int32 index = 3;
}

// Schema of the tables used in a query.
// Next ID: 2
message ColumnSchema {
  // Metadata about the tables used in the query.
  repeated TableMetadata metadata = 1;
}

// List of column names for the outcome section of the query result.
// Next ID: 2
message ColumnNames {
  // List of column names.
  repeated string names = 1;
}

// ResultRow is a flexible collection that captures a search result row. It can
// currently support UDM Events, Entity Contexts, Data Tables, Join results,
// etc. and will support all other data sources in the future.
// Next ID: 10
message ResultRow {
  // A result row of the search query.
  oneof result {
    // UDM event.
    EventRecord event_record = 1;

    // Stats record.
    StatsRecord stats_record = 2;

    // Entity context graph.
    EntityContextRecord entity_context_record = 3;

    // Join results.
    JoinRecord join_record = 4;

    // Detection.
    DetectionRecord detection_record = 5;

    // Data table.
    DataTableRecord data_table_record = 6;
  }

  reserved 8, 9;
  reserved "case_record", "case_history_record";

  // Outcome fields for an event specified in query request.
  repeated ColumnType outcomes = 7;
}

// StatsRecord contains a row in the response of a stats query.
// Next ID: 2
message StatsRecord {
  // Contains all columns resulting from a stats query and one row of values.
  repeated StatsColumnData results = 1;
}

// Represents a single column with a single cell in the set of columns
// returned as the stats query result.
// Next ID: 3
message StatsColumnData {
  // Used to store column names.
  string column = 1;

  // Store the values in a single column.
  ColumnType values = 2;
}

// Singular vs list of values in a single column.
// Next ID: 3
message ColumnType {
  // Represents a single value in the set of values returned as the query
  // result.
  // Next ID: 11
  message ColumnValue {
    // Value of the column based on data type.
    oneof value {
      // True if the value is NULL.
      bool null_val = 1;

      // Boolean value.
      bool bool_val = 2;

      // Bytes value.
      bytes bytes_val = 3;

      // Double value.
      double double_val = 4;

      // Integer value (signed).
      int64 int64_val = 5;

      // Un-signed integer value.
      uint64 uint64_val = 6;

      // String value. Enum values are returned as strings.
      string string_val = 7;

      // Timestamp values.
      google.protobuf.Timestamp timestamp_val = 8;

      // Date values.
      google.type.Date date_val = 9;

      // For any proto values that are not any of the above.
      google.protobuf.Any proto_val = 10;
    }
  }

  // Store list of values for a single column.
  // Next ID: 2
  message ColumnValueList {
    // List of values in one cell of the column.
    repeated ColumnValue values = 1;
  }

  // Store single value or list of values in a column.
  oneof type {
    // Single value in a column.
    ColumnValue value = 1;

    // List of values in a column e.g. IPs.
    ColumnValueList list = 2;
  }
}

// Contains a key-value pair of column name and its value. It represents a cell
// in the Data Table.
// Next ID: 3
message SearchDataTableRowCell {
  // The name of the column.
  string column = 1;

  // The value of the column.
  string value = 2;
}

// DataTableRecord contains information about a Data table.
// Next ID: 3
message DataTableRecord {
  // The resource name of the Data table.
  // Format:
  // projects/{project_id}/locations/{location}/instances/{instances}/dataTables/{data_table}
  string data_table = 1 [(google.api.resource_reference) = {
    type: "chronicle.googleapis.com/DataTable"
  }];

  // Stores information about a single row of a Data table.
  repeated SearchDataTableRowCell cells = 2;
}

// EventRecord stores information about a UDM event.
// Next ID: 8
message EventRecord {
  // Annotation for an event.
  enum Annotation {
    // Unspecified - no annotation to display.
    ANNOTATION_UNSPECIFIED = 0;

    // Event is associated with one or more alerts.
    ANNOTATION_ALERT = 1;
  }

  // The UDM Event.
  Event event = 1;

  // Raw log tokens mapped to the event. Can be used to locate the raw log entry
  // that generated the event.
  bytes event_log_token = 2;

  // If the event should be treated as an alert, the unique identifier for the
  // alert.
  int32 alert_number = 3;

  // Alert View specific Id. Helps create a link to Alert View.
  bytes alert_view_id = 4;

  // Annotations added to an event.
  repeated Annotation annotations = 5;

  // Detections associated with an event.
  repeated backstory.Collection detections = 6;

  // User defined table name for the event in joins query.
  string table = 7;
}

// EntityContextRecord stores information about a entity context graph.
// Next ID: 5
message EntityContextRecord {
  // The entity information to be retrieved with UDM ECG search.
  Entity entity = 1;

  // Raw log tokens mapped to the event that created the entity. This is only
  // for entity context events.
  string event_log_token = 2;

  // If the entity is timed or not.
  bool timed = 3;

  // User defined table name for the entity in joins query.
  string table = 4;
}

// JoinRecord stores information about a join result.
// Next ID: 6
message JoinRecord {
  // The events that are joined.
  repeated EventRecord events = 1;

  // The entities that are joined.
  repeated EntityContextRecord entities = 2;

  // The data tables that are joined.
  repeated DataTableRecord data_tables = 3;

  reserved 4, 5;
  reserved "cases", "case_histories";
}

// DetectionRecord stores information about a detection.
// Next ID: 3
message DetectionRecord {
  // The ID of the detection.
  bytes id = 1;

  // The detection.
  backstory.Collection collection = 2;
}

