// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package google.cloud.lustre.v1;

import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/resource.proto";
import "google/cloud/lustre/v1/directory_policy.proto";
import "google/cloud/lustre/v1/instance.proto";
import "google/cloud/lustre/v1/mirror.proto";
import "google/cloud/lustre/v1/transfer.proto";
import "google/longrunning/operations.proto";
import "google/protobuf/empty.proto";

option go_package = "cloud.google.com/go/lustre/apiv1/lustrepb;lustrepb";
option java_multiple_files = true;
option java_outer_classname = "LustreProto";
option java_package = "com.google.cloud.lustre.v1";
option (google.api.resource_definition) = {
  type: "iam.googleapis.com/ServiceAccount"
  pattern: "projects/{project}/serviceAccounts/{service_account}"
};
option (google.api.resource_definition) = {
  type: "compute.googleapis.com/Network"
  pattern: "projects/{project}/global/networks/{network}"
};
option (google.api.resource_definition) = {
  type: "cloudkms.googleapis.com/CryptoKey"
  pattern: "projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}"
};
option (google.api.resource_definition) = {
  type: "compute.googleapis.com/ResourcePolicy"
  pattern: "projects/{project}/regions/{region}/resourcePolicies/{resource_policy}"
  pattern: "projects/{project}/locations/{location}/resourcePolicies/{resource_policy}"
};

// Service describing handlers for resources
service Lustre {
  option (google.api.default_host) = "lustre.googleapis.com";
  option (google.api.oauth_scopes) =
      "https://www.googleapis.com/auth/cloud-platform";

  // Lists instances in a given project and location.
  rpc ListInstances(ListInstancesRequest) returns (ListInstancesResponse) {
    option (google.api.http) = {
      get: "/v1/{parent=projects/*/locations/*}/instances"
    };
    option (google.api.method_signature) = "parent";
  }

  // Gets details of a single instance.
  rpc GetInstance(GetInstanceRequest) returns (Instance) {
    option (google.api.http) = {
      get: "/v1/{name=projects/*/locations/*/instances/*}"
    };
    option (google.api.method_signature) = "name";
  }

  // Creates a new instance in a given project and location.
  rpc CreateInstance(CreateInstanceRequest)
      returns (google.longrunning.Operation) {
    option (google.api.http) = {
      post: "/v1/{parent=projects/*/locations/*}/instances"
      body: "instance"
    };
    option (google.api.method_signature) = "parent,instance,instance_id";
    option (google.longrunning.operation_info) = {
      response_type: "Instance"
      metadata_type: "OperationMetadata"
    };
  }

  // Updates the parameters of a single instance.
  rpc UpdateInstance(UpdateInstanceRequest)
      returns (google.longrunning.Operation) {
    option (google.api.http) = {
      patch: "/v1/{instance.name=projects/*/locations/*/instances/*}"
      body: "instance"
    };
    option (google.api.method_signature) = "instance,update_mask";
    option (google.longrunning.operation_info) = {
      response_type: "Instance"
      metadata_type: "OperationMetadata"
    };
  }

  // Deletes a single instance.
  rpc DeleteInstance(DeleteInstanceRequest)
      returns (google.longrunning.Operation) {
    option (google.api.http) = {
      delete: "/v1/{name=projects/*/locations/*/instances/*}"
    };
    option (google.api.method_signature) = "name";
    option (google.longrunning.operation_info) = {
      response_type: "google.protobuf.Empty"
      metadata_type: "OperationMetadata"
    };
  }

  // Reschedules a planned maintenance event for a specific instance.
  rpc RescheduleMaintenance(RescheduleMaintenanceRequest)
      returns (google.longrunning.Operation) {
    option (google.api.http) = {
      post: "/v1/{name=projects/*/locations/*/instances/*}:rescheduleMaintenance"
      body: "*"
    };
    option (google.api.method_signature) = "name,reschedule";
    option (google.longrunning.operation_info) = {
      response_type: "Instance"
      metadata_type: "OperationMetadata"
    };
  }

  // Imports data from Cloud Storage to a Managed Lustre instance.
  rpc ImportData(ImportDataRequest) returns (google.longrunning.Operation) {
    option (google.api.http) = {
      post: "/v1/{name=projects/*/locations/*/instances/*}:importData"
      body: "*"
    };
    option (google.api.method_signature) = "name";
    option (google.longrunning.operation_info) = {
      response_type: "ImportDataResponse"
      metadata_type: "ImportDataMetadata"
    };
  }

  // Exports data from a Managed Lustre instance to Cloud Storage.
  rpc ExportData(ExportDataRequest) returns (google.longrunning.Operation) {
    option (google.api.http) = {
      post: "/v1/{name=projects/*/locations/*/instances/*}:exportData"
      body: "*"
    };
    option (google.longrunning.operation_info) = {
      response_type: "ExportDataResponse"
      metadata_type: "ExportDataMetadata"
    };
  }

  // Creates a new mirror in a given instance.
  rpc CreateMirror(CreateMirrorRequest) returns (google.longrunning.Operation) {
    option (google.api.http) = {
      post: "/v1/{parent=projects/*/locations/*/instances/*}/mirrors"
      body: "mirror"
    };
    option (google.api.method_signature) = "parent,mirror,mirror_id";
    option (google.longrunning.operation_info) = {
      response_type: "Mirror"
      metadata_type: "CreateMirrorMetadata"
    };
  }

  // Updates the parameters of a single mirror.
  rpc UpdateMirror(UpdateMirrorRequest) returns (google.longrunning.Operation) {
    option (google.api.http) = {
      patch: "/v1/{mirror.name=projects/*/locations/*/instances/*/mirrors/*}"
      body: "mirror"
    };
    option (google.api.method_signature) = "mirror,update_mask";
    option (google.longrunning.operation_info) = {
      response_type: "Mirror"
      metadata_type: "OperationMetadata"
    };
  }

  // Deletes a single mirror.
  rpc DeleteMirror(DeleteMirrorRequest) returns (google.longrunning.Operation) {
    option (google.api.http) = {
      delete: "/v1/{name=projects/*/locations/*/instances/*/mirrors/*}"
    };
    option (google.api.method_signature) = "name";
    option (google.longrunning.operation_info) = {
      response_type: "google.protobuf.Empty"
      metadata_type: "OperationMetadata"
    };
  }

  // Gets details of a single mirror.
  rpc GetMirror(GetMirrorRequest) returns (Mirror) {
    option (google.api.http) = {
      get: "/v1/{name=projects/*/locations/*/instances/*/mirrors/*}"
    };
    option (google.api.method_signature) = "name";
  }

  // Gets details of multiple mirrors under a given instance.
  rpc ListMirrors(ListMirrorsRequest) returns (ListMirrorsResponse) {
    option (google.api.http) = {
      get: "/v1/{parent=projects/*/locations/*/instances/*}/mirrors"
    };
    option (google.api.method_signature) = "parent";
  }

  // Creates a directory policy resource.
  rpc CreateDirectoryPolicy(CreateDirectoryPolicyRequest)
      returns (google.longrunning.Operation) {
    option (google.api.http) = {
      post: "/v1/{parent=projects/*/locations/*/instances/*}/directoryPolicies"
      body: "directory_policy"
    };
    option (google.api.method_signature) =
        "parent,directory_policy,directory_policy_id";
    option (google.longrunning.operation_info) = {
      response_type: "DirectoryPolicy"
      metadata_type: "OperationMetadata"
    };
  }

  // Deletes a directory policy resource.
  rpc DeleteDirectoryPolicy(DeleteDirectoryPolicyRequest)
      returns (google.longrunning.Operation) {
    option (google.api.http) = {
      delete: "/v1/{name=projects/*/locations/*/instances/*/directoryPolicies/*}"
    };
    option (google.api.method_signature) = "name";
    option (google.longrunning.operation_info) = {
      response_type: "google.protobuf.Empty"
      metadata_type: "OperationMetadata"
    };
  }

  // Gets details of a single directory policy.
  rpc GetDirectoryPolicy(GetDirectoryPolicyRequest) returns (DirectoryPolicy) {
    option (google.api.http) = {
      get: "/v1/{name=projects/*/locations/*/instances/*/directoryPolicies/*}"
    };
    option (google.api.method_signature) = "name";
  }

  // Gets details of multiple directory policies under a given instance.
  rpc ListDirectoryPolicies(ListDirectoryPoliciesRequest)
      returns (ListDirectoryPoliciesResponse) {
    option (google.api.http) = {
      get: "/v1/{parent=projects/*/locations/*/instances/*}/directoryPolicies"
    };
    option (google.api.method_signature) = "parent";
  }
}
