##
# The specification format is not yet formalized and may change in the future.
#
# You can build this sample composition using $ sample-composer
# 
# curl -LO https://gist.github.com/beccasaurus/66e22078a456c73e65abcc0f1af7baa7/raw/sample-composer
#
# Prototyped from gist. Official tooling will be provided.
##

# Sample Source Definitions
sample_compositions:

# Save samples in automl_gapic.yaml in legacy v1.1 format
- output: ../automl_gapic.yaml
  paths:
  - _templates/_common.yaml
  - _templates/managing_datasets/_samples.yaml
  - _templates/managing_datasets/_tests.yaml
  - _templates/managing_datasets/natural_language.yaml
  - _templates/managing_datasets/natural_language_sentiment.yaml
  - _templates/managing_datasets/translation.yaml
  - _templates/managing_datasets/vision.yaml

# Output individual sample files in v1.2 format in samples/ dir for generator
- output: .
  paths:
  - _templates/_common.yaml
  - _templates/managing_datasets/_samples.yaml
  - _templates/managing_datasets/_tests.yaml
  - _templates/managing_datasets/natural_language.yaml
  - _templates/managing_datasets/natural_language_sentiment.yaml
  - _templates/managing_datasets/translation.yaml
  - _templates/managing_datasets/vision.yaml
