# Sample Source Definitions
sample_compositions:

# Save samples in automl_gapic.yaml in legacy v1.1 format
- output: ../automl_gapic.yaml
  paths: _templates

# Output individual sample files in v1.2 format in samples/ dir for generator
- output: .
  paths: _templates
