# Sample Source Definitions
sample_compositions:

# Super insanely weird bug.
# If you pass _templates/
# then some templates don't load.
# No idea. Will figure it out later.

# Save samples in automl_gapic.yaml in legacy v1.1 format
- output: ../automl_gapic.yaml
  paths:
  - _templates/_common.yaml
  - _templates/managing_datasets/_samples.yaml
  - _templates/managing_datasets/_tests.yaml
  - _templates/managing_datasets/natural_language.yaml
  - _templates/managing_datasets/natural_language_sentiment.yaml
  - _templates/managing_datasets/translation.yaml
  - _templates/managing_datasets/vision.yaml

# Output individual sample files in v1.2 format in samples/ dir for generator
- output: .
  paths:
  - _templates/_common.yaml
  - _templates/managing_datasets/_samples.yaml
  - _templates/managing_datasets/_tests.yaml
  - _templates/managing_datasets/natural_language.yaml
  - _templates/managing_datasets/natural_language_sentiment.yaml
  - _templates/managing_datasets/translation.yaml
  - _templates/managing_datasets/vision.yaml
