name: Generate API Index
on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.0
    - name: Checkout googleapis (this repository)
      uses: actions/checkout@v2
      with:
        path: googleapis
    - name: Checkout index generator
      uses: actions/checkout@v2
      with:
        repository: googleapis/googleapis-api-index-generator
        path: gen
    - name: Generate API index
      run: |
        gen/scripts/generate-schema.sh
        gen/scripts/generate-index.sh $PWD/googleapis
        cp gen/tmp/api-index-v1.json $PWD/googleapis
    - name: Commit API index
      run: |
        cd googleapis
        [[ ! $(git diff --exit-code api-index-v1.json) ]] && echo "Nothing to commit." && exit 0
        git config user.name "Google APIs"
        git add api-index-v1.json
        git commit -m "chore: regenerate API index"
        git push
